/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FeatureService } from "../feature.service";
import { FeatureCreateInput } from "./FeatureCreateInput";
import { FeatureWhereInput } from "./FeatureWhereInput";
import { FeatureWhereUniqueInput } from "./FeatureWhereUniqueInput";
import { FeatureFindManyArgs } from "./FeatureFindManyArgs";
import { FeatureUpdateInput } from "./FeatureUpdateInput";
import { Feature } from "./Feature";
import { FeatureOrganizationFindManyArgs } from "../../featureOrganization/base/FeatureOrganizationFindManyArgs";
import { FeatureOrganization } from "../../featureOrganization/base/FeatureOrganization";
import { FeatureOrganizationWhereUniqueInput } from "../../featureOrganization/base/FeatureOrganizationWhereUniqueInput";

export class FeatureControllerBase {
  constructor(protected readonly service: FeatureService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Feature })
  async create(@common.Body() data: FeatureCreateInput): Promise<Feature> {
    return await this.service.create({
      data: {
        ...data,

        feature: data.feature
          ? {
              connect: data.feature,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        code: true,
        isPaid: true,
        description: true,
        image: true,
        link: true,
        status: true,
        icon: true,

        feature: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Feature] })
  @ApiNestedQuery(FeatureFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Feature[]> {
    const args = plainToClass(FeatureFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        code: true,
        isPaid: true,
        description: true,
        image: true,
        link: true,
        status: true,
        icon: true,

        feature: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Feature })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: FeatureWhereUniqueInput
  ): Promise<Feature | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        code: true,
        isPaid: true,
        description: true,
        image: true,
        link: true,
        status: true,
        icon: true,

        feature: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Feature })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: FeatureWhereUniqueInput,
    @common.Body() data: FeatureUpdateInput
  ): Promise<Feature | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          feature: data.feature
            ? {
                connect: data.feature,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          code: true,
          isPaid: true,
          description: true,
          image: true,
          link: true,
          status: true,
          icon: true,

          feature: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Feature })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: FeatureWhereUniqueInput
  ): Promise<Feature | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          code: true,
          isPaid: true,
          description: true,
          image: true,
          link: true,
          status: true,
          icon: true,

          feature: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/otherFeature")
  @ApiNestedQuery(FeatureFindManyArgs)
  async findManyOtherFeature(
    @common.Req() request: Request,
    @common.Param() params: FeatureWhereUniqueInput
  ): Promise<Feature[]> {
    const query = plainToClass(FeatureFindManyArgs, request.query);
    const results = await this.service.findOtherFeature(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        code: true,
        isPaid: true,
        description: true,
        image: true,
        link: true,
        status: true,
        icon: true,

        feature: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/otherFeature")
  async connectOtherFeature(
    @common.Param() params: FeatureWhereUniqueInput,
    @common.Body() body: FeatureWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      otherFeature: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/otherFeature")
  async updateOtherFeature(
    @common.Param() params: FeatureWhereUniqueInput,
    @common.Body() body: FeatureWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      otherFeature: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/otherFeature")
  async disconnectOtherFeature(
    @common.Param() params: FeatureWhereUniqueInput,
    @common.Body() body: FeatureWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      otherFeature: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/featureOrganization")
  @ApiNestedQuery(FeatureOrganizationFindManyArgs)
  async findManyFeatureOrganization(
    @common.Req() request: Request,
    @common.Param() params: FeatureWhereUniqueInput
  ): Promise<FeatureOrganization[]> {
    const query = plainToClass(FeatureOrganizationFindManyArgs, request.query);
    const results = await this.service.findFeatureOrganization(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isEnabled: true,

        organization: {
          select: {
            id: true,
          },
        },

        feature: {
          select: {
            id: true,
          },
        },

        tenant: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/featureOrganization")
  async connectFeatureOrganization(
    @common.Param() params: FeatureWhereUniqueInput,
    @common.Body() body: FeatureOrganizationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      featureOrganization: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/featureOrganization")
  async updateFeatureOrganization(
    @common.Param() params: FeatureWhereUniqueInput,
    @common.Body() body: FeatureOrganizationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      featureOrganization: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/featureOrganization")
  async disconnectFeatureOrganization(
    @common.Param() params: FeatureWhereUniqueInput,
    @common.Body() body: FeatureOrganizationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      featureOrganization: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
