import { StringFilter } from "../../util/StringFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { DecimalFilter } from "../../util/DecimalFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { OrganizationContactWhereUniqueInput } from "../organizationContact/OrganizationContactWhereUniqueInput";
import { ExpenseCategoryWhereUniqueInput } from "../expenseCategory/ExpenseCategoryWhereUniqueInput";
import { EmployeeWhereUniqueInput } from "../employee/EmployeeWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { OrganizationProjectWhereUniqueInput } from "../organizationProject/OrganizationProjectWhereUniqueInput";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { OrganizationVendorWhereUniqueInput } from "../organizationVendor/OrganizationVendorWhereUniqueInput";
import { InvoiceItemListRelationFilter } from "../invoiceItem/InvoiceItemListRelationFilter";
import { TagExpenseListRelationFilter } from "../tagExpense/TagExpenseListRelationFilter";

export type ExpenseWhereInput = {
  id?: StringFilter;
  createdAt?: DateTimeFilter;
  updatedAt?: DateTimeFilter;
  amount?: DecimalFilter;
  typeOfExpense?: StringNullableFilter;
  notes?: StringNullableFilter;
  currency?: StringFilter;
  valueDate?: DateTimeNullableFilter;
  purpose?: StringNullableFilter;
  taxType?: StringNullableFilter;
  taxLabel?: StringNullableFilter;
  rateValue?: DecimalNullableFilter;
  receipt?: StringNullableFilter;
  splitExpense?: BooleanNullableFilter;
  reference?: StringNullableFilter;
  status?: "INVOICED" | "UNINVOICED" | "PAID" | "NOT_BILLABLE";
  organizationContact?: OrganizationContactWhereUniqueInput;
  expenseCategory?: ExpenseCategoryWhereUniqueInput;
  employee?: EmployeeWhereUniqueInput;
  tenant?: TenantWhereUniqueInput;
  organizationProject?: OrganizationProjectWhereUniqueInput;
  organization?: OrganizationWhereUniqueInput;
  organizationVendor?: OrganizationVendorWhereUniqueInput;
  invoiceItem?: InvoiceItemListRelationFilter;
  tagExpense?: TagExpenseListRelationFilter;
};
