import { AccountingTemplateUpdateManyWithoutOrganizationsInput } from "./AccountingTemplateUpdateManyWithoutOrganizationsInput";
import { ActivityUpdateManyWithoutOrganizationsInput } from "./ActivityUpdateManyWithoutOrganizationsInput";
import { AppointmentEmployeeUpdateManyWithoutOrganizationsInput } from "./AppointmentEmployeeUpdateManyWithoutOrganizationsInput";
import { ApprovalPolicyUpdateManyWithoutOrganizationsInput } from "./ApprovalPolicyUpdateManyWithoutOrganizationsInput";
import { AvailabilitySlotUpdateManyWithoutOrganizationsInput } from "./AvailabilitySlotUpdateManyWithoutOrganizationsInput";
import { CandidateUpdateManyWithoutOrganizationsInput } from "./CandidateUpdateManyWithoutOrganizationsInput";
import { CandidateCriterionRatingUpdateManyWithoutOrganizationsInput } from "./CandidateCriterionRatingUpdateManyWithoutOrganizationsInput";
import { CandidateDocumentUpdateManyWithoutOrganizationsInput } from "./CandidateDocumentUpdateManyWithoutOrganizationsInput";
import { CandidateEducationUpdateManyWithoutOrganizationsInput } from "./CandidateEducationUpdateManyWithoutOrganizationsInput";
import { CandidateExperienceUpdateManyWithoutOrganizationsInput } from "./CandidateExperienceUpdateManyWithoutOrganizationsInput";
import { CandidateFeedbackUpdateManyWithoutOrganizationsInput } from "./CandidateFeedbackUpdateManyWithoutOrganizationsInput";
import { CandidateInterviewUpdateManyWithoutOrganizationsInput } from "./CandidateInterviewUpdateManyWithoutOrganizationsInput";
import { CandidateInterviewerUpdateManyWithoutOrganizationsInput } from "./CandidateInterviewerUpdateManyWithoutOrganizationsInput";
import { CandidatePersonalQualityUpdateManyWithoutOrganizationsInput } from "./CandidatePersonalQualityUpdateManyWithoutOrganizationsInput";
import { CandidateSkillUpdateManyWithoutOrganizationsInput } from "./CandidateSkillUpdateManyWithoutOrganizationsInput";
import { CandidateSourceUpdateManyWithoutOrganizationsInput } from "./CandidateSourceUpdateManyWithoutOrganizationsInput";
import { CandidateTechnologyUpdateManyWithoutOrganizationsInput } from "./CandidateTechnologyUpdateManyWithoutOrganizationsInput";
import { ChangelogUpdateManyWithoutOrganizationsInput } from "./ChangelogUpdateManyWithoutOrganizationsInput";
import { ContactUpdateManyWithoutOrganizationsInput } from "./ContactUpdateManyWithoutOrganizationsInput";
import { ContactWhereUniqueInput } from "../contact/ContactWhereUniqueInput";
import { CustomSmtpUpdateManyWithoutOrganizationsInput } from "./CustomSmtpUpdateManyWithoutOrganizationsInput";
import { DealUpdateManyWithoutOrganizationsInput } from "./DealUpdateManyWithoutOrganizationsInput";
import { EmailSentUpdateManyWithoutOrganizationsInput } from "./EmailSentUpdateManyWithoutOrganizationsInput";
import { EmailTemplateUpdateManyWithoutOrganizationsInput } from "./EmailTemplateUpdateManyWithoutOrganizationsInput";
import { EmployeeUpdateManyWithoutOrganizationsInput } from "./EmployeeUpdateManyWithoutOrganizationsInput";
import { EmployeeAppointmentUpdateManyWithoutOrganizationsInput } from "./EmployeeAppointmentUpdateManyWithoutOrganizationsInput";
import { EmployeeAwardUpdateManyWithoutOrganizationsInput } from "./EmployeeAwardUpdateManyWithoutOrganizationsInput";
import { EmployeeLevelUpdateManyWithoutOrganizationsInput } from "./EmployeeLevelUpdateManyWithoutOrganizationsInput";
import { EmployeePhoneUpdateManyWithoutOrganizationsInput } from "./EmployeePhoneUpdateManyWithoutOrganizationsInput";
import { EmployeeProposalTemplateUpdateManyWithoutOrganizationsInput } from "./EmployeeProposalTemplateUpdateManyWithoutOrganizationsInput";
import { EmployeeRecurringExpenseUpdateManyWithoutOrganizationsInput } from "./EmployeeRecurringExpenseUpdateManyWithoutOrganizationsInput";
import { EmployeeSettingUpdateManyWithoutOrganizationsInput } from "./EmployeeSettingUpdateManyWithoutOrganizationsInput";
import { EmployeeUpworkJobSearchCriterionUpdateManyWithoutOrganizationsInput } from "./EmployeeUpworkJobSearchCriterionUpdateManyWithoutOrganizationsInput";
import { EquipmentUpdateManyWithoutOrganizationsInput } from "./EquipmentUpdateManyWithoutOrganizationsInput";
import { EquipmentSharingUpdateManyWithoutOrganizationsInput } from "./EquipmentSharingUpdateManyWithoutOrganizationsInput";
import { EquipmentSharingPolicyUpdateManyWithoutOrganizationsInput } from "./EquipmentSharingPolicyUpdateManyWithoutOrganizationsInput";
import { EstimateEmailUpdateManyWithoutOrganizationsInput } from "./EstimateEmailUpdateManyWithoutOrganizationsInput";
import { EventTypeUpdateManyWithoutOrganizationsInput } from "./EventTypeUpdateManyWithoutOrganizationsInput";
import { ExpenseUpdateManyWithoutOrganizationsInput } from "./ExpenseUpdateManyWithoutOrganizationsInput";
import { ExpenseCategoryUpdateManyWithoutOrganizationsInput } from "./ExpenseCategoryUpdateManyWithoutOrganizationsInput";
import { FeatureOrganizationUpdateManyWithoutOrganizationsInput } from "./FeatureOrganizationUpdateManyWithoutOrganizationsInput";
import { GoalUpdateManyWithoutOrganizationsInput } from "./GoalUpdateManyWithoutOrganizationsInput";
import { GoalGeneralSettingUpdateManyWithoutOrganizationsInput } from "./GoalGeneralSettingUpdateManyWithoutOrganizationsInput";
import { GoalKpiUpdateManyWithoutOrganizationsInput } from "./GoalKpiUpdateManyWithoutOrganizationsInput";
import { GoalKpiTemplateUpdateManyWithoutOrganizationsInput } from "./GoalKpiTemplateUpdateManyWithoutOrganizationsInput";
import { GoalTemplateUpdateManyWithoutOrganizationsInput } from "./GoalTemplateUpdateManyWithoutOrganizationsInput";
import { GoalTimeFrameUpdateManyWithoutOrganizationsInput } from "./GoalTimeFrameUpdateManyWithoutOrganizationsInput";
import { ImageAssetUpdateManyWithoutOrganizationsInput } from "./ImageAssetUpdateManyWithoutOrganizationsInput";
import { ImageAssetWhereUniqueInput } from "../imageAsset/ImageAssetWhereUniqueInput";
import { IncomeUpdateManyWithoutOrganizationsInput } from "./IncomeUpdateManyWithoutOrganizationsInput";
import { IntegrationEntitySettingUpdateManyWithoutOrganizationsInput } from "./IntegrationEntitySettingUpdateManyWithoutOrganizationsInput";
import { IntegrationEntitySettingTiedUpdateManyWithoutOrganizationsInput } from "./IntegrationEntitySettingTiedUpdateManyWithoutOrganizationsInput";
import { IntegrationMapUpdateManyWithoutOrganizationsInput } from "./IntegrationMapUpdateManyWithoutOrganizationsInput";
import { IntegrationSettingUpdateManyWithoutOrganizationsInput } from "./IntegrationSettingUpdateManyWithoutOrganizationsInput";
import { IntegrationTenantUpdateManyWithoutOrganizationsInput } from "./IntegrationTenantUpdateManyWithoutOrganizationsInput";
import { InviteUpdateManyWithoutOrganizationsInput } from "./InviteUpdateManyWithoutOrganizationsInput";
import { InvoiceEstimateHistoryUpdateManyWithoutOrganizationsInput } from "./InvoiceEstimateHistoryUpdateManyWithoutOrganizationsInput";
import { InvoiceUpdateManyWithoutOrganizationsInput } from "./InvoiceUpdateManyWithoutOrganizationsInput";
import { InvoiceItemUpdateManyWithoutOrganizationsInput } from "./InvoiceItemUpdateManyWithoutOrganizationsInput";
import { IssueTypeUpdateManyWithoutOrganizationsInput } from "./IssueTypeUpdateManyWithoutOrganizationsInput";
import { JobPresetUpdateManyWithoutOrganizationsInput } from "./JobPresetUpdateManyWithoutOrganizationsInput";
import { JobPresetUpworkJobSearchCriterionUpdateManyWithoutOrganizationsInput } from "./JobPresetUpworkJobSearchCriterionUpdateManyWithoutOrganizationsInput";
import { JobSearchCategoryUpdateManyWithoutOrganizationsInput } from "./JobSearchCategoryUpdateManyWithoutOrganizationsInput";
import { JobSearchOccupationUpdateManyWithoutOrganizationsInput } from "./JobSearchOccupationUpdateManyWithoutOrganizationsInput";
import { KeyResultUpdateManyWithoutOrganizationsInput } from "./KeyResultUpdateManyWithoutOrganizationsInput";
import { KeyResultTemplateUpdateManyWithoutOrganizationsInput } from "./KeyResultTemplateUpdateManyWithoutOrganizationsInput";
import { KeyResultUpdateUpdateManyWithoutOrganizationsInput } from "./KeyResultUpdateUpdateManyWithoutOrganizationsInput";
import { KnowledgeBaseUpdateManyWithoutOrganizationsInput } from "./KnowledgeBaseUpdateManyWithoutOrganizationsInput";
import { KnowledgeBaseArticleUpdateManyWithoutOrganizationsInput } from "./KnowledgeBaseArticleUpdateManyWithoutOrganizationsInput";
import { KnowledgeBaseAuthorUpdateManyWithoutOrganizationsInput } from "./KnowledgeBaseAuthorUpdateManyWithoutOrganizationsInput";
import { MerchantUpdateManyWithoutOrganizationsInput } from "./MerchantUpdateManyWithoutOrganizationsInput";
import { OrganizationAwardUpdateManyWithoutOrganizationsInput } from "./OrganizationAwardUpdateManyWithoutOrganizationsInput";
import { OrganizationContactUpdateManyWithoutOrganizationsInput } from "./OrganizationContactUpdateManyWithoutOrganizationsInput";
import { OrganizationDepartmentUpdateManyWithoutOrganizationsInput } from "./OrganizationDepartmentUpdateManyWithoutOrganizationsInput";
import { OrganizationDocumentUpdateManyWithoutOrganizationsInput } from "./OrganizationDocumentUpdateManyWithoutOrganizationsInput";
import { OrganizationEmploymentTypeUpdateManyWithoutOrganizationsInput } from "./OrganizationEmploymentTypeUpdateManyWithoutOrganizationsInput";
import { OrganizationLanguageUpdateManyWithoutOrganizationsInput } from "./OrganizationLanguageUpdateManyWithoutOrganizationsInput";
import { OrganizationPositionUpdateManyWithoutOrganizationsInput } from "./OrganizationPositionUpdateManyWithoutOrganizationsInput";
import { OrganizationProjectUpdateManyWithoutOrganizationsInput } from "./OrganizationProjectUpdateManyWithoutOrganizationsInput";
import { OrganizationRecurringExpenseUpdateManyWithoutOrganizationsInput } from "./OrganizationRecurringExpenseUpdateManyWithoutOrganizationsInput";
import { OrganizationSprintUpdateManyWithoutOrganizationsInput } from "./OrganizationSprintUpdateManyWithoutOrganizationsInput";
import { OrganizationTaskSettingUpdateManyWithoutOrganizationsInput } from "./OrganizationTaskSettingUpdateManyWithoutOrganizationsInput";
import { OrganizationTeamUpdateManyWithoutOrganizationsInput } from "./OrganizationTeamUpdateManyWithoutOrganizationsInput";
import { OrganizationTeamEmployeeUpdateManyWithoutOrganizationsInput } from "./OrganizationTeamEmployeeUpdateManyWithoutOrganizationsInput";
import { OrganizationTeamJoinRequestUpdateManyWithoutOrganizationsInput } from "./OrganizationTeamJoinRequestUpdateManyWithoutOrganizationsInput";
import { OrganizationVendorUpdateManyWithoutOrganizationsInput } from "./OrganizationVendorUpdateManyWithoutOrganizationsInput";
import { PaymentUpdateManyWithoutOrganizationsInput } from "./PaymentUpdateManyWithoutOrganizationsInput";
import { PipelineUpdateManyWithoutOrganizationsInput } from "./PipelineUpdateManyWithoutOrganizationsInput";
import { PipelineStageUpdateManyWithoutOrganizationsInput } from "./PipelineStageUpdateManyWithoutOrganizationsInput";
import { ProductUpdateManyWithoutOrganizationsInput } from "./ProductUpdateManyWithoutOrganizationsInput";
import { ProductCategoryUpdateManyWithoutOrganizationsInput } from "./ProductCategoryUpdateManyWithoutOrganizationsInput";
import { ProductCategoryTranslationUpdateManyWithoutOrganizationsInput } from "./ProductCategoryTranslationUpdateManyWithoutOrganizationsInput";
import { ProductOptionUpdateManyWithoutOrganizationsInput } from "./ProductOptionUpdateManyWithoutOrganizationsInput";
import { ProductOptionGroupUpdateManyWithoutOrganizationsInput } from "./ProductOptionGroupUpdateManyWithoutOrganizationsInput";
import { ProductOptionGroupTranslationUpdateManyWithoutOrganizationsInput } from "./ProductOptionGroupTranslationUpdateManyWithoutOrganizationsInput";
import { ProductOptionTranslationUpdateManyWithoutOrganizationsInput } from "./ProductOptionTranslationUpdateManyWithoutOrganizationsInput";
import { ProductTranslationUpdateManyWithoutOrganizationsInput } from "./ProductTranslationUpdateManyWithoutOrganizationsInput";
import { ProductTypeUpdateManyWithoutOrganizationsInput } from "./ProductTypeUpdateManyWithoutOrganizationsInput";
import { ProductTypeTranslationUpdateManyWithoutOrganizationsInput } from "./ProductTypeTranslationUpdateManyWithoutOrganizationsInput";
import { ProductVariantUpdateManyWithoutOrganizationsInput } from "./ProductVariantUpdateManyWithoutOrganizationsInput";
import { ProductVariantPriceUpdateManyWithoutOrganizationsInput } from "./ProductVariantPriceUpdateManyWithoutOrganizationsInput";
import { ProductVariantSettingUpdateManyWithoutOrganizationsInput } from "./ProductVariantSettingUpdateManyWithoutOrganizationsInput";
import { ProposalUpdateManyWithoutOrganizationsInput } from "./ProposalUpdateManyWithoutOrganizationsInput";
import { ReportOrganizationUpdateManyWithoutOrganizationsInput } from "./ReportOrganizationUpdateManyWithoutOrganizationsInput";
import { RequestApprovalUpdateManyWithoutOrganizationsInput } from "./RequestApprovalUpdateManyWithoutOrganizationsInput";
import { RequestApprovalEmployeeUpdateManyWithoutOrganizationsInput } from "./RequestApprovalEmployeeUpdateManyWithoutOrganizationsInput";
import { RequestApprovalTeamUpdateManyWithoutOrganizationsInput } from "./RequestApprovalTeamUpdateManyWithoutOrganizationsInput";
import { ScreenshotUpdateManyWithoutOrganizationsInput } from "./ScreenshotUpdateManyWithoutOrganizationsInput";
import { SkillUpdateManyWithoutOrganizationsInput } from "./SkillUpdateManyWithoutOrganizationsInput";
import { SkillOrganizationUpdateManyWithoutOrganizationsInput } from "./SkillOrganizationUpdateManyWithoutOrganizationsInput";
import { TagUpdateManyWithoutOrganizationsInput } from "./TagUpdateManyWithoutOrganizationsInput";
import { TagOrganizationUpdateManyWithoutOrganizationsInput } from "./TagOrganizationUpdateManyWithoutOrganizationsInput";
import { TaskUpdateManyWithoutOrganizationsInput } from "./TaskUpdateManyWithoutOrganizationsInput";
import { TaskLinkedIssueUpdateManyWithoutOrganizationsInput } from "./TaskLinkedIssueUpdateManyWithoutOrganizationsInput";
import { TaskPriorityUpdateManyWithoutOrganizationsInput } from "./TaskPriorityUpdateManyWithoutOrganizationsInput";
import { TaskRelatedIssueTypeUpdateManyWithoutOrganizationsInput } from "./TaskRelatedIssueTypeUpdateManyWithoutOrganizationsInput";
import { TaskSizeUpdateManyWithoutOrganizationsInput } from "./TaskSizeUpdateManyWithoutOrganizationsInput";
import { TaskStatusUpdateManyWithoutOrganizationsInput } from "./TaskStatusUpdateManyWithoutOrganizationsInput";
import { TaskVersionUpdateManyWithoutOrganizationsInput } from "./TaskVersionUpdateManyWithoutOrganizationsInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { TimeLogUpdateManyWithoutOrganizationsInput } from "./TimeLogUpdateManyWithoutOrganizationsInput";
import { TimeOffPolicyUpdateManyWithoutOrganizationsInput } from "./TimeOffPolicyUpdateManyWithoutOrganizationsInput";
import { TimeOffRequestUpdateManyWithoutOrganizationsInput } from "./TimeOffRequestUpdateManyWithoutOrganizationsInput";
import { TimesheetUpdateManyWithoutOrganizationsInput } from "./TimesheetUpdateManyWithoutOrganizationsInput";
import { TimeSlotUpdateManyWithoutOrganizationsInput } from "./TimeSlotUpdateManyWithoutOrganizationsInput";
import { TimeSlotMinuteUpdateManyWithoutOrganizationsInput } from "./TimeSlotMinuteUpdateManyWithoutOrganizationsInput";
import { UserOrganizationUpdateManyWithoutOrganizationsInput } from "./UserOrganizationUpdateManyWithoutOrganizationsInput";
import { WarehouseUpdateManyWithoutOrganizationsInput } from "./WarehouseUpdateManyWithoutOrganizationsInput";
import { WarehouseProductUpdateManyWithoutOrganizationsInput } from "./WarehouseProductUpdateManyWithoutOrganizationsInput";
import { WarehouseProductVariantUpdateManyWithoutOrganizationsInput } from "./WarehouseProductVariantUpdateManyWithoutOrganizationsInput";

export type OrganizationUpdateInput = {
  accountingTemplate?: AccountingTemplateUpdateManyWithoutOrganizationsInput;
  activity?: ActivityUpdateManyWithoutOrganizationsInput;
  activityProofDuration?: number;
  allowDeleteTime?: boolean;
  allowManualTime?: boolean;
  allowModifyTime?: boolean;
  allowScreenshotCapture?: boolean;
  allowTrackInactivity?: boolean;
  appointmentEmployee?: AppointmentEmployeeUpdateManyWithoutOrganizationsInput;
  approvalPolicy?: ApprovalPolicyUpdateManyWithoutOrganizationsInput;
  availabilitySlot?: AvailabilitySlotUpdateManyWithoutOrganizationsInput;
  banner?: string | null;
  bonusPercentage?: number | null;
  bonusType?: string | null;
  brandColor?: string | null;
  candidate?: CandidateUpdateManyWithoutOrganizationsInput;
  candidateCriterionRating?: CandidateCriterionRatingUpdateManyWithoutOrganizationsInput;
  candidateDocument?: CandidateDocumentUpdateManyWithoutOrganizationsInput;
  candidateEducation?: CandidateEducationUpdateManyWithoutOrganizationsInput;
  candidateExperience?: CandidateExperienceUpdateManyWithoutOrganizationsInput;
  candidateFeedback?: CandidateFeedbackUpdateManyWithoutOrganizationsInput;
  candidateInterview?: CandidateInterviewUpdateManyWithoutOrganizationsInput;
  candidateInterviewer?: CandidateInterviewerUpdateManyWithoutOrganizationsInput;
  candidatePersonalQuality?: CandidatePersonalQualityUpdateManyWithoutOrganizationsInput;
  candidateSkill?: CandidateSkillUpdateManyWithoutOrganizationsInput;
  candidateSource?: CandidateSourceUpdateManyWithoutOrganizationsInput;
  candidateTechnology?: CandidateTechnologyUpdateManyWithoutOrganizationsInput;
  changelog?: ChangelogUpdateManyWithoutOrganizationsInput;
  clientFocus?: string | null;
  contactContactOrganizationIdToorganization?: ContactUpdateManyWithoutOrganizationsInput;
  contactOrganizationContactIdTocontact?: ContactWhereUniqueInput | null;
  convertAcceptedEstimates?: boolean | null;
  currency?: string;
  currencyPosition?: string;
  customSmtp?: CustomSmtpUpdateManyWithoutOrganizationsInput;
  dateFormat?: string | null;
  daysUntilDue?: number | null;
  deal?: DealUpdateManyWithoutOrganizationsInput;
  defaultAlignmentType?: string | null;
  defaultEndTime?: string | null;
  defaultInvoiceEstimateTerms?: string | null;
  defaultStartTime?: string | null;
  defaultValueDateType?: "TODAY" | "END_OF_MONTH" | "START_OF_MONTH" | null;
  discountAfterTax?: boolean | null;
  emailSent?: EmailSentUpdateManyWithoutOrganizationsInput;
  emailTemplate?: EmailTemplateUpdateManyWithoutOrganizationsInput;
  employee?: EmployeeUpdateManyWithoutOrganizationsInput;
  employeeAppointment?: EmployeeAppointmentUpdateManyWithoutOrganizationsInput;
  employeeAward?: EmployeeAwardUpdateManyWithoutOrganizationsInput;
  employeeLevel?: EmployeeLevelUpdateManyWithoutOrganizationsInput;
  employeePhone?: EmployeePhoneUpdateManyWithoutOrganizationsInput;
  employeeProposalTemplate?: EmployeeProposalTemplateUpdateManyWithoutOrganizationsInput;
  employeeRecurringExpense?: EmployeeRecurringExpenseUpdateManyWithoutOrganizationsInput;
  employeeSetting?: EmployeeSettingUpdateManyWithoutOrganizationsInput;
  employeeUpworkJobSearchCriterion?: EmployeeUpworkJobSearchCriterionUpdateManyWithoutOrganizationsInput;
  equipment?: EquipmentUpdateManyWithoutOrganizationsInput;
  equipmentSharing?: EquipmentSharingUpdateManyWithoutOrganizationsInput;
  equipmentSharingPolicy?: EquipmentSharingPolicyUpdateManyWithoutOrganizationsInput;
  estimateEmail?: EstimateEmailUpdateManyWithoutOrganizationsInput;
  eventType?: EventTypeUpdateManyWithoutOrganizationsInput;
  expense?: ExpenseUpdateManyWithoutOrganizationsInput;
  expenseCategory?: ExpenseCategoryUpdateManyWithoutOrganizationsInput;
  featureOrganization?: FeatureOrganizationUpdateManyWithoutOrganizationsInput;
  fiscalEndDate?: Date | null;
  fiscalInformation?: string | null;
  fiscalStartDate?: Date | null;
  futureDateAllowed?: boolean | null;
  goal?: GoalUpdateManyWithoutOrganizationsInput;
  goalGeneralSetting?: GoalGeneralSettingUpdateManyWithoutOrganizationsInput;
  goalKpi?: GoalKpiUpdateManyWithoutOrganizationsInput;
  goalKpiTemplate?: GoalKpiTemplateUpdateManyWithoutOrganizationsInput;
  goalTemplate?: GoalTemplateUpdateManyWithoutOrganizationsInput;
  goalTimeFrame?: GoalTimeFrameUpdateManyWithoutOrganizationsInput;
  imageAssetImageAssetOrganizationIdToorganization?: ImageAssetUpdateManyWithoutOrganizationsInput;
  imageAssetOrganizationImageIdToimageAsset?: ImageAssetWhereUniqueInput | null;
  imageUrl?: string | null;
  inactivityTimeLimit?: number;
  income?: IncomeUpdateManyWithoutOrganizationsInput;
  integrationEntitySetting?: IntegrationEntitySettingUpdateManyWithoutOrganizationsInput;
  integrationEntitySettingTied?: IntegrationEntitySettingTiedUpdateManyWithoutOrganizationsInput;
  integrationMap?: IntegrationMapUpdateManyWithoutOrganizationsInput;
  integrationSetting?: IntegrationSettingUpdateManyWithoutOrganizationsInput;
  integrationTenant?: IntegrationTenantUpdateManyWithoutOrganizationsInput;
  invite?: InviteUpdateManyWithoutOrganizationsInput;
  inviteExpiryPeriod?: number | null;
  invitesAllowed?: boolean | null;
  invoiceEstimateHistory?: InvoiceEstimateHistoryUpdateManyWithoutOrganizationsInput;
  invoiceInvoiceFromOrganizationIdToorganization?: InvoiceUpdateManyWithoutOrganizationsInput;
  invoiceInvoiceOrganizationIdToorganization?: InvoiceUpdateManyWithoutOrganizationsInput;
  invoiceItem?: InvoiceItemUpdateManyWithoutOrganizationsInput;
  isActive?: boolean;
  isDefault?: boolean;
  isRemoveIdleTime?: boolean;
  issueType?: IssueTypeUpdateManyWithoutOrganizationsInput;
  jobPreset?: JobPresetUpdateManyWithoutOrganizationsInput;
  jobPresetUpworkJobSearchCriterion?: JobPresetUpworkJobSearchCriterionUpdateManyWithoutOrganizationsInput;
  jobSearchCategory?: JobSearchCategoryUpdateManyWithoutOrganizationsInput;
  jobSearchOccupation?: JobSearchOccupationUpdateManyWithoutOrganizationsInput;
  keyResult?: KeyResultUpdateManyWithoutOrganizationsInput;
  keyResultTemplate?: KeyResultTemplateUpdateManyWithoutOrganizationsInput;
  keyResultUpdate?: KeyResultUpdateUpdateManyWithoutOrganizationsInput;
  knowledgeBase?: KnowledgeBaseUpdateManyWithoutOrganizationsInput;
  knowledgeBaseArticle?: KnowledgeBaseArticleUpdateManyWithoutOrganizationsInput;
  knowledgeBaseAuthor?: KnowledgeBaseAuthorUpdateManyWithoutOrganizationsInput;
  merchant?: MerchantUpdateManyWithoutOrganizationsInput;
  minimumProjectSize?: string | null;
  name?: string;
  numberFormat?: string | null;
  officialName?: string | null;
  organizationAward?: OrganizationAwardUpdateManyWithoutOrganizationsInput;
  organizationContact?: OrganizationContactUpdateManyWithoutOrganizationsInput;
  organizationDepartment?: OrganizationDepartmentUpdateManyWithoutOrganizationsInput;
  organizationDocument?: OrganizationDocumentUpdateManyWithoutOrganizationsInput;
  organizationEmploymentType?: OrganizationEmploymentTypeUpdateManyWithoutOrganizationsInput;
  organizationLanguage?: OrganizationLanguageUpdateManyWithoutOrganizationsInput;
  organizationPosition?: OrganizationPositionUpdateManyWithoutOrganizationsInput;
  organizationProject?: OrganizationProjectUpdateManyWithoutOrganizationsInput;
  organizationRecurringExpense?: OrganizationRecurringExpenseUpdateManyWithoutOrganizationsInput;
  organizationSprint?: OrganizationSprintUpdateManyWithoutOrganizationsInput;
  organizationTaskSetting?: OrganizationTaskSettingUpdateManyWithoutOrganizationsInput;
  organizationTeam?: OrganizationTeamUpdateManyWithoutOrganizationsInput;
  organizationTeamEmployee?: OrganizationTeamEmployeeUpdateManyWithoutOrganizationsInput;
  organizationTeamJoinRequest?: OrganizationTeamJoinRequestUpdateManyWithoutOrganizationsInput;
  organizationVendor?: OrganizationVendorUpdateManyWithoutOrganizationsInput;
  overview?: string | null;
  payment?: PaymentUpdateManyWithoutOrganizationsInput;
  pipeline?: PipelineUpdateManyWithoutOrganizationsInput;
  pipelineStage?: PipelineStageUpdateManyWithoutOrganizationsInput;
  product?: ProductUpdateManyWithoutOrganizationsInput;
  productCategory?: ProductCategoryUpdateManyWithoutOrganizationsInput;
  productCategoryTranslation?: ProductCategoryTranslationUpdateManyWithoutOrganizationsInput;
  productOption?: ProductOptionUpdateManyWithoutOrganizationsInput;
  productOptionGroup?: ProductOptionGroupUpdateManyWithoutOrganizationsInput;
  productOptionGroupTranslation?: ProductOptionGroupTranslationUpdateManyWithoutOrganizationsInput;
  productOptionTranslation?: ProductOptionTranslationUpdateManyWithoutOrganizationsInput;
  productTranslation?: ProductTranslationUpdateManyWithoutOrganizationsInput;
  productType?: ProductTypeUpdateManyWithoutOrganizationsInput;
  productTypeTranslation?: ProductTypeTranslationUpdateManyWithoutOrganizationsInput;
  productVariant?: ProductVariantUpdateManyWithoutOrganizationsInput;
  productVariantPrice?: ProductVariantPriceUpdateManyWithoutOrganizationsInput;
  productVariantSetting?: ProductVariantSettingUpdateManyWithoutOrganizationsInput;
  profileLink?: string | null;
  proposal?: ProposalUpdateManyWithoutOrganizationsInput;
  regionCode?: string | null;
  registrationDate?: Date | null;
  reportOrganization?: ReportOrganizationUpdateManyWithoutOrganizationsInput;
  requestApproval?: RequestApprovalUpdateManyWithoutOrganizationsInput;
  requestApprovalEmployee?: RequestApprovalEmployeeUpdateManyWithoutOrganizationsInput;
  requestApprovalTeam?: RequestApprovalTeamUpdateManyWithoutOrganizationsInput;
  requireClient?: boolean;
  requireDescription?: boolean;
  requireProject?: boolean;
  requireReason?: boolean;
  requireTask?: boolean;
  screenshot?: ScreenshotUpdateManyWithoutOrganizationsInput;
  separateInvoiceItemTaxAndDiscount?: boolean | null;
  shortDescription?: string | null;
  showBonusesPaid?: boolean | null;
  showClients?: boolean | null;
  showClientsCount?: boolean | null;
  showEmployeesCount?: boolean | null;
  showIncome?: boolean | null;
  showMinimumProjectSize?: boolean | null;
  showProfits?: boolean | null;
  showProjectsCount?: boolean | null;
  showTotalHours?: boolean | null;
  skill?: SkillUpdateManyWithoutOrganizationsInput;
  skillOrganization?: SkillOrganizationUpdateManyWithoutOrganizationsInput;
  startWeekOn?: string | null;
  tag?: TagUpdateManyWithoutOrganizationsInput;
  tagOrganization?: TagOrganizationUpdateManyWithoutOrganizationsInput;
  task?: TaskUpdateManyWithoutOrganizationsInput;
  taskLinkedIssues?: TaskLinkedIssueUpdateManyWithoutOrganizationsInput;
  taskPriority?: TaskPriorityUpdateManyWithoutOrganizationsInput;
  taskRelatedIssueType?: TaskRelatedIssueTypeUpdateManyWithoutOrganizationsInput;
  taskSize?: TaskSizeUpdateManyWithoutOrganizationsInput;
  taskStatus?: TaskStatusUpdateManyWithoutOrganizationsInput;
  taskVersion?: TaskVersionUpdateManyWithoutOrganizationsInput;
  taxId?: string | null;
  tenant?: TenantWhereUniqueInput | null;
  timeFormat?: number;
  timeLog?: TimeLogUpdateManyWithoutOrganizationsInput;
  timeOffPolicy?: TimeOffPolicyUpdateManyWithoutOrganizationsInput;
  timeOffRequest?: TimeOffRequestUpdateManyWithoutOrganizationsInput;
  timesheet?: TimesheetUpdateManyWithoutOrganizationsInput;
  timeSlot?: TimeSlotUpdateManyWithoutOrganizationsInput;
  timeSlotMinute?: TimeSlotMinuteUpdateManyWithoutOrganizationsInput;
  timeZone?: string | null;
  totalEmployees?: number | null;
  upworkOrganizationId?: string | null;
  userOrganization?: UserOrganizationUpdateManyWithoutOrganizationsInput;
  valueDate?: Date | null;
  warehouse?: WarehouseUpdateManyWithoutOrganizationsInput;
  warehouseProduct?: WarehouseProductUpdateManyWithoutOrganizationsInput;
  warehouseProductVariant?: WarehouseProductVariantUpdateManyWithoutOrganizationsInput;
  website?: string | null;
};
