import { AccountingTemplateCreateNestedManyWithoutOrganizationsInput } from "./AccountingTemplateCreateNestedManyWithoutOrganizationsInput";
import { ActivityCreateNestedManyWithoutOrganizationsInput } from "./ActivityCreateNestedManyWithoutOrganizationsInput";
import { AppointmentEmployeeCreateNestedManyWithoutOrganizationsInput } from "./AppointmentEmployeeCreateNestedManyWithoutOrganizationsInput";
import { ApprovalPolicyCreateNestedManyWithoutOrganizationsInput } from "./ApprovalPolicyCreateNestedManyWithoutOrganizationsInput";
import { AvailabilitySlotCreateNestedManyWithoutOrganizationsInput } from "./AvailabilitySlotCreateNestedManyWithoutOrganizationsInput";
import { CandidateCreateNestedManyWithoutOrganizationsInput } from "./CandidateCreateNestedManyWithoutOrganizationsInput";
import { CandidateCriterionRatingCreateNestedManyWithoutOrganizationsInput } from "./CandidateCriterionRatingCreateNestedManyWithoutOrganizationsInput";
import { CandidateDocumentCreateNestedManyWithoutOrganizationsInput } from "./CandidateDocumentCreateNestedManyWithoutOrganizationsInput";
import { CandidateEducationCreateNestedManyWithoutOrganizationsInput } from "./CandidateEducationCreateNestedManyWithoutOrganizationsInput";
import { CandidateExperienceCreateNestedManyWithoutOrganizationsInput } from "./CandidateExperienceCreateNestedManyWithoutOrganizationsInput";
import { CandidateFeedbackCreateNestedManyWithoutOrganizationsInput } from "./CandidateFeedbackCreateNestedManyWithoutOrganizationsInput";
import { CandidateInterviewCreateNestedManyWithoutOrganizationsInput } from "./CandidateInterviewCreateNestedManyWithoutOrganizationsInput";
import { CandidateInterviewerCreateNestedManyWithoutOrganizationsInput } from "./CandidateInterviewerCreateNestedManyWithoutOrganizationsInput";
import { CandidatePersonalQualityCreateNestedManyWithoutOrganizationsInput } from "./CandidatePersonalQualityCreateNestedManyWithoutOrganizationsInput";
import { CandidateSkillCreateNestedManyWithoutOrganizationsInput } from "./CandidateSkillCreateNestedManyWithoutOrganizationsInput";
import { CandidateSourceCreateNestedManyWithoutOrganizationsInput } from "./CandidateSourceCreateNestedManyWithoutOrganizationsInput";
import { CandidateTechnologyCreateNestedManyWithoutOrganizationsInput } from "./CandidateTechnologyCreateNestedManyWithoutOrganizationsInput";
import { ChangelogCreateNestedManyWithoutOrganizationsInput } from "./ChangelogCreateNestedManyWithoutOrganizationsInput";
import { ContactCreateNestedManyWithoutOrganizationsInput } from "./ContactCreateNestedManyWithoutOrganizationsInput";
import { ContactWhereUniqueInput } from "../contact/ContactWhereUniqueInput";
import { CustomSmtpCreateNestedManyWithoutOrganizationsInput } from "./CustomSmtpCreateNestedManyWithoutOrganizationsInput";
import { DealCreateNestedManyWithoutOrganizationsInput } from "./DealCreateNestedManyWithoutOrganizationsInput";
import { EmailSentCreateNestedManyWithoutOrganizationsInput } from "./EmailSentCreateNestedManyWithoutOrganizationsInput";
import { EmailTemplateCreateNestedManyWithoutOrganizationsInput } from "./EmailTemplateCreateNestedManyWithoutOrganizationsInput";
import { EmployeeCreateNestedManyWithoutOrganizationsInput } from "./EmployeeCreateNestedManyWithoutOrganizationsInput";
import { EmployeeAppointmentCreateNestedManyWithoutOrganizationsInput } from "./EmployeeAppointmentCreateNestedManyWithoutOrganizationsInput";
import { EmployeeAwardCreateNestedManyWithoutOrganizationsInput } from "./EmployeeAwardCreateNestedManyWithoutOrganizationsInput";
import { EmployeeLevelCreateNestedManyWithoutOrganizationsInput } from "./EmployeeLevelCreateNestedManyWithoutOrganizationsInput";
import { EmployeePhoneCreateNestedManyWithoutOrganizationsInput } from "./EmployeePhoneCreateNestedManyWithoutOrganizationsInput";
import { EmployeeProposalTemplateCreateNestedManyWithoutOrganizationsInput } from "./EmployeeProposalTemplateCreateNestedManyWithoutOrganizationsInput";
import { EmployeeRecurringExpenseCreateNestedManyWithoutOrganizationsInput } from "./EmployeeRecurringExpenseCreateNestedManyWithoutOrganizationsInput";
import { EmployeeSettingCreateNestedManyWithoutOrganizationsInput } from "./EmployeeSettingCreateNestedManyWithoutOrganizationsInput";
import { EmployeeUpworkJobSearchCriterionCreateNestedManyWithoutOrganizationsInput } from "./EmployeeUpworkJobSearchCriterionCreateNestedManyWithoutOrganizationsInput";
import { EquipmentCreateNestedManyWithoutOrganizationsInput } from "./EquipmentCreateNestedManyWithoutOrganizationsInput";
import { EquipmentSharingCreateNestedManyWithoutOrganizationsInput } from "./EquipmentSharingCreateNestedManyWithoutOrganizationsInput";
import { EquipmentSharingPolicyCreateNestedManyWithoutOrganizationsInput } from "./EquipmentSharingPolicyCreateNestedManyWithoutOrganizationsInput";
import { EstimateEmailCreateNestedManyWithoutOrganizationsInput } from "./EstimateEmailCreateNestedManyWithoutOrganizationsInput";
import { EventTypeCreateNestedManyWithoutOrganizationsInput } from "./EventTypeCreateNestedManyWithoutOrganizationsInput";
import { ExpenseCreateNestedManyWithoutOrganizationsInput } from "./ExpenseCreateNestedManyWithoutOrganizationsInput";
import { ExpenseCategoryCreateNestedManyWithoutOrganizationsInput } from "./ExpenseCategoryCreateNestedManyWithoutOrganizationsInput";
import { FeatureOrganizationCreateNestedManyWithoutOrganizationsInput } from "./FeatureOrganizationCreateNestedManyWithoutOrganizationsInput";
import { GoalCreateNestedManyWithoutOrganizationsInput } from "./GoalCreateNestedManyWithoutOrganizationsInput";
import { GoalGeneralSettingCreateNestedManyWithoutOrganizationsInput } from "./GoalGeneralSettingCreateNestedManyWithoutOrganizationsInput";
import { GoalKpiCreateNestedManyWithoutOrganizationsInput } from "./GoalKpiCreateNestedManyWithoutOrganizationsInput";
import { GoalKpiTemplateCreateNestedManyWithoutOrganizationsInput } from "./GoalKpiTemplateCreateNestedManyWithoutOrganizationsInput";
import { GoalTemplateCreateNestedManyWithoutOrganizationsInput } from "./GoalTemplateCreateNestedManyWithoutOrganizationsInput";
import { GoalTimeFrameCreateNestedManyWithoutOrganizationsInput } from "./GoalTimeFrameCreateNestedManyWithoutOrganizationsInput";
import { ImageAssetCreateNestedManyWithoutOrganizationsInput } from "./ImageAssetCreateNestedManyWithoutOrganizationsInput";
import { ImageAssetWhereUniqueInput } from "../imageAsset/ImageAssetWhereUniqueInput";
import { IncomeCreateNestedManyWithoutOrganizationsInput } from "./IncomeCreateNestedManyWithoutOrganizationsInput";
import { IntegrationEntitySettingCreateNestedManyWithoutOrganizationsInput } from "./IntegrationEntitySettingCreateNestedManyWithoutOrganizationsInput";
import { IntegrationEntitySettingTiedCreateNestedManyWithoutOrganizationsInput } from "./IntegrationEntitySettingTiedCreateNestedManyWithoutOrganizationsInput";
import { IntegrationMapCreateNestedManyWithoutOrganizationsInput } from "./IntegrationMapCreateNestedManyWithoutOrganizationsInput";
import { IntegrationSettingCreateNestedManyWithoutOrganizationsInput } from "./IntegrationSettingCreateNestedManyWithoutOrganizationsInput";
import { IntegrationTenantCreateNestedManyWithoutOrganizationsInput } from "./IntegrationTenantCreateNestedManyWithoutOrganizationsInput";
import { InviteCreateNestedManyWithoutOrganizationsInput } from "./InviteCreateNestedManyWithoutOrganizationsInput";
import { InvoiceEstimateHistoryCreateNestedManyWithoutOrganizationsInput } from "./InvoiceEstimateHistoryCreateNestedManyWithoutOrganizationsInput";
import { InvoiceCreateNestedManyWithoutOrganizationsInput } from "./InvoiceCreateNestedManyWithoutOrganizationsInput";
import { InvoiceItemCreateNestedManyWithoutOrganizationsInput } from "./InvoiceItemCreateNestedManyWithoutOrganizationsInput";
import { IssueTypeCreateNestedManyWithoutOrganizationsInput } from "./IssueTypeCreateNestedManyWithoutOrganizationsInput";
import { JobPresetCreateNestedManyWithoutOrganizationsInput } from "./JobPresetCreateNestedManyWithoutOrganizationsInput";
import { JobPresetUpworkJobSearchCriterionCreateNestedManyWithoutOrganizationsInput } from "./JobPresetUpworkJobSearchCriterionCreateNestedManyWithoutOrganizationsInput";
import { JobSearchCategoryCreateNestedManyWithoutOrganizationsInput } from "./JobSearchCategoryCreateNestedManyWithoutOrganizationsInput";
import { JobSearchOccupationCreateNestedManyWithoutOrganizationsInput } from "./JobSearchOccupationCreateNestedManyWithoutOrganizationsInput";
import { KeyResultCreateNestedManyWithoutOrganizationsInput } from "./KeyResultCreateNestedManyWithoutOrganizationsInput";
import { KeyResultTemplateCreateNestedManyWithoutOrganizationsInput } from "./KeyResultTemplateCreateNestedManyWithoutOrganizationsInput";
import { KeyResultUpdateCreateNestedManyWithoutOrganizationsInput } from "./KeyResultUpdateCreateNestedManyWithoutOrganizationsInput";
import { KnowledgeBaseCreateNestedManyWithoutOrganizationsInput } from "./KnowledgeBaseCreateNestedManyWithoutOrganizationsInput";
import { KnowledgeBaseArticleCreateNestedManyWithoutOrganizationsInput } from "./KnowledgeBaseArticleCreateNestedManyWithoutOrganizationsInput";
import { KnowledgeBaseAuthorCreateNestedManyWithoutOrganizationsInput } from "./KnowledgeBaseAuthorCreateNestedManyWithoutOrganizationsInput";
import { MerchantCreateNestedManyWithoutOrganizationsInput } from "./MerchantCreateNestedManyWithoutOrganizationsInput";
import { OrganizationAwardCreateNestedManyWithoutOrganizationsInput } from "./OrganizationAwardCreateNestedManyWithoutOrganizationsInput";
import { OrganizationContactCreateNestedManyWithoutOrganizationsInput } from "./OrganizationContactCreateNestedManyWithoutOrganizationsInput";
import { OrganizationDepartmentCreateNestedManyWithoutOrganizationsInput } from "./OrganizationDepartmentCreateNestedManyWithoutOrganizationsInput";
import { OrganizationDocumentCreateNestedManyWithoutOrganizationsInput } from "./OrganizationDocumentCreateNestedManyWithoutOrganizationsInput";
import { OrganizationEmploymentTypeCreateNestedManyWithoutOrganizationsInput } from "./OrganizationEmploymentTypeCreateNestedManyWithoutOrganizationsInput";
import { OrganizationLanguageCreateNestedManyWithoutOrganizationsInput } from "./OrganizationLanguageCreateNestedManyWithoutOrganizationsInput";
import { OrganizationPositionCreateNestedManyWithoutOrganizationsInput } from "./OrganizationPositionCreateNestedManyWithoutOrganizationsInput";
import { OrganizationProjectCreateNestedManyWithoutOrganizationsInput } from "./OrganizationProjectCreateNestedManyWithoutOrganizationsInput";
import { OrganizationRecurringExpenseCreateNestedManyWithoutOrganizationsInput } from "./OrganizationRecurringExpenseCreateNestedManyWithoutOrganizationsInput";
import { OrganizationSprintCreateNestedManyWithoutOrganizationsInput } from "./OrganizationSprintCreateNestedManyWithoutOrganizationsInput";
import { OrganizationTaskSettingCreateNestedManyWithoutOrganizationsInput } from "./OrganizationTaskSettingCreateNestedManyWithoutOrganizationsInput";
import { OrganizationTeamCreateNestedManyWithoutOrganizationsInput } from "./OrganizationTeamCreateNestedManyWithoutOrganizationsInput";
import { OrganizationTeamEmployeeCreateNestedManyWithoutOrganizationsInput } from "./OrganizationTeamEmployeeCreateNestedManyWithoutOrganizationsInput";
import { OrganizationTeamJoinRequestCreateNestedManyWithoutOrganizationsInput } from "./OrganizationTeamJoinRequestCreateNestedManyWithoutOrganizationsInput";
import { OrganizationVendorCreateNestedManyWithoutOrganizationsInput } from "./OrganizationVendorCreateNestedManyWithoutOrganizationsInput";
import { PaymentCreateNestedManyWithoutOrganizationsInput } from "./PaymentCreateNestedManyWithoutOrganizationsInput";
import { PipelineCreateNestedManyWithoutOrganizationsInput } from "./PipelineCreateNestedManyWithoutOrganizationsInput";
import { PipelineStageCreateNestedManyWithoutOrganizationsInput } from "./PipelineStageCreateNestedManyWithoutOrganizationsInput";
import { ProductCreateNestedManyWithoutOrganizationsInput } from "./ProductCreateNestedManyWithoutOrganizationsInput";
import { ProductCategoryCreateNestedManyWithoutOrganizationsInput } from "./ProductCategoryCreateNestedManyWithoutOrganizationsInput";
import { ProductCategoryTranslationCreateNestedManyWithoutOrganizationsInput } from "./ProductCategoryTranslationCreateNestedManyWithoutOrganizationsInput";
import { ProductOptionCreateNestedManyWithoutOrganizationsInput } from "./ProductOptionCreateNestedManyWithoutOrganizationsInput";
import { ProductOptionGroupCreateNestedManyWithoutOrganizationsInput } from "./ProductOptionGroupCreateNestedManyWithoutOrganizationsInput";
import { ProductOptionGroupTranslationCreateNestedManyWithoutOrganizationsInput } from "./ProductOptionGroupTranslationCreateNestedManyWithoutOrganizationsInput";
import { ProductOptionTranslationCreateNestedManyWithoutOrganizationsInput } from "./ProductOptionTranslationCreateNestedManyWithoutOrganizationsInput";
import { ProductTranslationCreateNestedManyWithoutOrganizationsInput } from "./ProductTranslationCreateNestedManyWithoutOrganizationsInput";
import { ProductTypeCreateNestedManyWithoutOrganizationsInput } from "./ProductTypeCreateNestedManyWithoutOrganizationsInput";
import { ProductTypeTranslationCreateNestedManyWithoutOrganizationsInput } from "./ProductTypeTranslationCreateNestedManyWithoutOrganizationsInput";
import { ProductVariantCreateNestedManyWithoutOrganizationsInput } from "./ProductVariantCreateNestedManyWithoutOrganizationsInput";
import { ProductVariantPriceCreateNestedManyWithoutOrganizationsInput } from "./ProductVariantPriceCreateNestedManyWithoutOrganizationsInput";
import { ProductVariantSettingCreateNestedManyWithoutOrganizationsInput } from "./ProductVariantSettingCreateNestedManyWithoutOrganizationsInput";
import { ProposalCreateNestedManyWithoutOrganizationsInput } from "./ProposalCreateNestedManyWithoutOrganizationsInput";
import { ReportOrganizationCreateNestedManyWithoutOrganizationsInput } from "./ReportOrganizationCreateNestedManyWithoutOrganizationsInput";
import { RequestApprovalCreateNestedManyWithoutOrganizationsInput } from "./RequestApprovalCreateNestedManyWithoutOrganizationsInput";
import { RequestApprovalEmployeeCreateNestedManyWithoutOrganizationsInput } from "./RequestApprovalEmployeeCreateNestedManyWithoutOrganizationsInput";
import { RequestApprovalTeamCreateNestedManyWithoutOrganizationsInput } from "./RequestApprovalTeamCreateNestedManyWithoutOrganizationsInput";
import { ScreenshotCreateNestedManyWithoutOrganizationsInput } from "./ScreenshotCreateNestedManyWithoutOrganizationsInput";
import { SkillCreateNestedManyWithoutOrganizationsInput } from "./SkillCreateNestedManyWithoutOrganizationsInput";
import { SkillOrganizationCreateNestedManyWithoutOrganizationsInput } from "./SkillOrganizationCreateNestedManyWithoutOrganizationsInput";
import { TagCreateNestedManyWithoutOrganizationsInput } from "./TagCreateNestedManyWithoutOrganizationsInput";
import { TagOrganizationCreateNestedManyWithoutOrganizationsInput } from "./TagOrganizationCreateNestedManyWithoutOrganizationsInput";
import { TaskCreateNestedManyWithoutOrganizationsInput } from "./TaskCreateNestedManyWithoutOrganizationsInput";
import { TaskLinkedIssueCreateNestedManyWithoutOrganizationsInput } from "./TaskLinkedIssueCreateNestedManyWithoutOrganizationsInput";
import { TaskPriorityCreateNestedManyWithoutOrganizationsInput } from "./TaskPriorityCreateNestedManyWithoutOrganizationsInput";
import { TaskRelatedIssueTypeCreateNestedManyWithoutOrganizationsInput } from "./TaskRelatedIssueTypeCreateNestedManyWithoutOrganizationsInput";
import { TaskSizeCreateNestedManyWithoutOrganizationsInput } from "./TaskSizeCreateNestedManyWithoutOrganizationsInput";
import { TaskStatusCreateNestedManyWithoutOrganizationsInput } from "./TaskStatusCreateNestedManyWithoutOrganizationsInput";
import { TaskVersionCreateNestedManyWithoutOrganizationsInput } from "./TaskVersionCreateNestedManyWithoutOrganizationsInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { TimeLogCreateNestedManyWithoutOrganizationsInput } from "./TimeLogCreateNestedManyWithoutOrganizationsInput";
import { TimeOffPolicyCreateNestedManyWithoutOrganizationsInput } from "./TimeOffPolicyCreateNestedManyWithoutOrganizationsInput";
import { TimeOffRequestCreateNestedManyWithoutOrganizationsInput } from "./TimeOffRequestCreateNestedManyWithoutOrganizationsInput";
import { TimesheetCreateNestedManyWithoutOrganizationsInput } from "./TimesheetCreateNestedManyWithoutOrganizationsInput";
import { TimeSlotCreateNestedManyWithoutOrganizationsInput } from "./TimeSlotCreateNestedManyWithoutOrganizationsInput";
import { TimeSlotMinuteCreateNestedManyWithoutOrganizationsInput } from "./TimeSlotMinuteCreateNestedManyWithoutOrganizationsInput";
import { UserOrganizationCreateNestedManyWithoutOrganizationsInput } from "./UserOrganizationCreateNestedManyWithoutOrganizationsInput";
import { WarehouseCreateNestedManyWithoutOrganizationsInput } from "./WarehouseCreateNestedManyWithoutOrganizationsInput";
import { WarehouseProductCreateNestedManyWithoutOrganizationsInput } from "./WarehouseProductCreateNestedManyWithoutOrganizationsInput";
import { WarehouseProductVariantCreateNestedManyWithoutOrganizationsInput } from "./WarehouseProductVariantCreateNestedManyWithoutOrganizationsInput";

export type OrganizationCreateInput = {
  accountingTemplate?: AccountingTemplateCreateNestedManyWithoutOrganizationsInput;
  activity?: ActivityCreateNestedManyWithoutOrganizationsInput;
  activityProofDuration: number;
  allowDeleteTime: boolean;
  allowManualTime: boolean;
  allowModifyTime: boolean;
  allowScreenshotCapture: boolean;
  allowTrackInactivity: boolean;
  appointmentEmployee?: AppointmentEmployeeCreateNestedManyWithoutOrganizationsInput;
  approvalPolicy?: ApprovalPolicyCreateNestedManyWithoutOrganizationsInput;
  availabilitySlot?: AvailabilitySlotCreateNestedManyWithoutOrganizationsInput;
  banner?: string | null;
  bonusPercentage?: number | null;
  bonusType?: string | null;
  brandColor?: string | null;
  candidate?: CandidateCreateNestedManyWithoutOrganizationsInput;
  candidateCriterionRating?: CandidateCriterionRatingCreateNestedManyWithoutOrganizationsInput;
  candidateDocument?: CandidateDocumentCreateNestedManyWithoutOrganizationsInput;
  candidateEducation?: CandidateEducationCreateNestedManyWithoutOrganizationsInput;
  candidateExperience?: CandidateExperienceCreateNestedManyWithoutOrganizationsInput;
  candidateFeedback?: CandidateFeedbackCreateNestedManyWithoutOrganizationsInput;
  candidateInterview?: CandidateInterviewCreateNestedManyWithoutOrganizationsInput;
  candidateInterviewer?: CandidateInterviewerCreateNestedManyWithoutOrganizationsInput;
  candidatePersonalQuality?: CandidatePersonalQualityCreateNestedManyWithoutOrganizationsInput;
  candidateSkill?: CandidateSkillCreateNestedManyWithoutOrganizationsInput;
  candidateSource?: CandidateSourceCreateNestedManyWithoutOrganizationsInput;
  candidateTechnology?: CandidateTechnologyCreateNestedManyWithoutOrganizationsInput;
  changelog?: ChangelogCreateNestedManyWithoutOrganizationsInput;
  clientFocus?: string | null;
  contactContactOrganizationIdToorganization?: ContactCreateNestedManyWithoutOrganizationsInput;
  contactOrganizationContactIdTocontact?: ContactWhereUniqueInput | null;
  convertAcceptedEstimates?: boolean | null;
  currency: string;
  currencyPosition: string;
  customSmtp?: CustomSmtpCreateNestedManyWithoutOrganizationsInput;
  dateFormat?: string | null;
  daysUntilDue?: number | null;
  deal?: DealCreateNestedManyWithoutOrganizationsInput;
  defaultAlignmentType?: string | null;
  defaultEndTime?: string | null;
  defaultInvoiceEstimateTerms?: string | null;
  defaultStartTime?: string | null;
  defaultValueDateType?: "TODAY" | "END_OF_MONTH" | "START_OF_MONTH" | null;
  discountAfterTax?: boolean | null;
  emailSent?: EmailSentCreateNestedManyWithoutOrganizationsInput;
  emailTemplate?: EmailTemplateCreateNestedManyWithoutOrganizationsInput;
  employee?: EmployeeCreateNestedManyWithoutOrganizationsInput;
  employeeAppointment?: EmployeeAppointmentCreateNestedManyWithoutOrganizationsInput;
  employeeAward?: EmployeeAwardCreateNestedManyWithoutOrganizationsInput;
  employeeLevel?: EmployeeLevelCreateNestedManyWithoutOrganizationsInput;
  employeePhone?: EmployeePhoneCreateNestedManyWithoutOrganizationsInput;
  employeeProposalTemplate?: EmployeeProposalTemplateCreateNestedManyWithoutOrganizationsInput;
  employeeRecurringExpense?: EmployeeRecurringExpenseCreateNestedManyWithoutOrganizationsInput;
  employeeSetting?: EmployeeSettingCreateNestedManyWithoutOrganizationsInput;
  employeeUpworkJobSearchCriterion?: EmployeeUpworkJobSearchCriterionCreateNestedManyWithoutOrganizationsInput;
  equipment?: EquipmentCreateNestedManyWithoutOrganizationsInput;
  equipmentSharing?: EquipmentSharingCreateNestedManyWithoutOrganizationsInput;
  equipmentSharingPolicy?: EquipmentSharingPolicyCreateNestedManyWithoutOrganizationsInput;
  estimateEmail?: EstimateEmailCreateNestedManyWithoutOrganizationsInput;
  eventType?: EventTypeCreateNestedManyWithoutOrganizationsInput;
  expense?: ExpenseCreateNestedManyWithoutOrganizationsInput;
  expenseCategory?: ExpenseCategoryCreateNestedManyWithoutOrganizationsInput;
  featureOrganization?: FeatureOrganizationCreateNestedManyWithoutOrganizationsInput;
  fiscalEndDate?: Date | null;
  fiscalInformation?: string | null;
  fiscalStartDate?: Date | null;
  futureDateAllowed?: boolean | null;
  goal?: GoalCreateNestedManyWithoutOrganizationsInput;
  goalGeneralSetting?: GoalGeneralSettingCreateNestedManyWithoutOrganizationsInput;
  goalKpi?: GoalKpiCreateNestedManyWithoutOrganizationsInput;
  goalKpiTemplate?: GoalKpiTemplateCreateNestedManyWithoutOrganizationsInput;
  goalTemplate?: GoalTemplateCreateNestedManyWithoutOrganizationsInput;
  goalTimeFrame?: GoalTimeFrameCreateNestedManyWithoutOrganizationsInput;
  imageAssetImageAssetOrganizationIdToorganization?: ImageAssetCreateNestedManyWithoutOrganizationsInput;
  imageAssetOrganizationImageIdToimageAsset?: ImageAssetWhereUniqueInput | null;
  imageUrl?: string | null;
  inactivityTimeLimit: number;
  income?: IncomeCreateNestedManyWithoutOrganizationsInput;
  integrationEntitySetting?: IntegrationEntitySettingCreateNestedManyWithoutOrganizationsInput;
  integrationEntitySettingTied?: IntegrationEntitySettingTiedCreateNestedManyWithoutOrganizationsInput;
  integrationMap?: IntegrationMapCreateNestedManyWithoutOrganizationsInput;
  integrationSetting?: IntegrationSettingCreateNestedManyWithoutOrganizationsInput;
  integrationTenant?: IntegrationTenantCreateNestedManyWithoutOrganizationsInput;
  invite?: InviteCreateNestedManyWithoutOrganizationsInput;
  inviteExpiryPeriod?: number | null;
  invitesAllowed?: boolean | null;
  invoiceEstimateHistory?: InvoiceEstimateHistoryCreateNestedManyWithoutOrganizationsInput;
  invoiceInvoiceFromOrganizationIdToorganization?: InvoiceCreateNestedManyWithoutOrganizationsInput;
  invoiceInvoiceOrganizationIdToorganization?: InvoiceCreateNestedManyWithoutOrganizationsInput;
  invoiceItem?: InvoiceItemCreateNestedManyWithoutOrganizationsInput;
  isActive: boolean;
  isDefault: boolean;
  isRemoveIdleTime: boolean;
  issueType?: IssueTypeCreateNestedManyWithoutOrganizationsInput;
  jobPreset?: JobPresetCreateNestedManyWithoutOrganizationsInput;
  jobPresetUpworkJobSearchCriterion?: JobPresetUpworkJobSearchCriterionCreateNestedManyWithoutOrganizationsInput;
  jobSearchCategory?: JobSearchCategoryCreateNestedManyWithoutOrganizationsInput;
  jobSearchOccupation?: JobSearchOccupationCreateNestedManyWithoutOrganizationsInput;
  keyResult?: KeyResultCreateNestedManyWithoutOrganizationsInput;
  keyResultTemplate?: KeyResultTemplateCreateNestedManyWithoutOrganizationsInput;
  keyResultUpdate?: KeyResultUpdateCreateNestedManyWithoutOrganizationsInput;
  knowledgeBase?: KnowledgeBaseCreateNestedManyWithoutOrganizationsInput;
  knowledgeBaseArticle?: KnowledgeBaseArticleCreateNestedManyWithoutOrganizationsInput;
  knowledgeBaseAuthor?: KnowledgeBaseAuthorCreateNestedManyWithoutOrganizationsInput;
  merchant?: MerchantCreateNestedManyWithoutOrganizationsInput;
  minimumProjectSize?: string | null;
  name: string;
  numberFormat?: string | null;
  officialName?: string | null;
  organizationAward?: OrganizationAwardCreateNestedManyWithoutOrganizationsInput;
  organizationContact?: OrganizationContactCreateNestedManyWithoutOrganizationsInput;
  organizationDepartment?: OrganizationDepartmentCreateNestedManyWithoutOrganizationsInput;
  organizationDocument?: OrganizationDocumentCreateNestedManyWithoutOrganizationsInput;
  organizationEmploymentType?: OrganizationEmploymentTypeCreateNestedManyWithoutOrganizationsInput;
  organizationLanguage?: OrganizationLanguageCreateNestedManyWithoutOrganizationsInput;
  organizationPosition?: OrganizationPositionCreateNestedManyWithoutOrganizationsInput;
  organizationProject?: OrganizationProjectCreateNestedManyWithoutOrganizationsInput;
  organizationRecurringExpense?: OrganizationRecurringExpenseCreateNestedManyWithoutOrganizationsInput;
  organizationSprint?: OrganizationSprintCreateNestedManyWithoutOrganizationsInput;
  organizationTaskSetting?: OrganizationTaskSettingCreateNestedManyWithoutOrganizationsInput;
  organizationTeam?: OrganizationTeamCreateNestedManyWithoutOrganizationsInput;
  organizationTeamEmployee?: OrganizationTeamEmployeeCreateNestedManyWithoutOrganizationsInput;
  organizationTeamJoinRequest?: OrganizationTeamJoinRequestCreateNestedManyWithoutOrganizationsInput;
  organizationVendor?: OrganizationVendorCreateNestedManyWithoutOrganizationsInput;
  overview?: string | null;
  payment?: PaymentCreateNestedManyWithoutOrganizationsInput;
  pipeline?: PipelineCreateNestedManyWithoutOrganizationsInput;
  pipelineStage?: PipelineStageCreateNestedManyWithoutOrganizationsInput;
  product?: ProductCreateNestedManyWithoutOrganizationsInput;
  productCategory?: ProductCategoryCreateNestedManyWithoutOrganizationsInput;
  productCategoryTranslation?: ProductCategoryTranslationCreateNestedManyWithoutOrganizationsInput;
  productOption?: ProductOptionCreateNestedManyWithoutOrganizationsInput;
  productOptionGroup?: ProductOptionGroupCreateNestedManyWithoutOrganizationsInput;
  productOptionGroupTranslation?: ProductOptionGroupTranslationCreateNestedManyWithoutOrganizationsInput;
  productOptionTranslation?: ProductOptionTranslationCreateNestedManyWithoutOrganizationsInput;
  productTranslation?: ProductTranslationCreateNestedManyWithoutOrganizationsInput;
  productType?: ProductTypeCreateNestedManyWithoutOrganizationsInput;
  productTypeTranslation?: ProductTypeTranslationCreateNestedManyWithoutOrganizationsInput;
  productVariant?: ProductVariantCreateNestedManyWithoutOrganizationsInput;
  productVariantPrice?: ProductVariantPriceCreateNestedManyWithoutOrganizationsInput;
  productVariantSetting?: ProductVariantSettingCreateNestedManyWithoutOrganizationsInput;
  profileLink?: string | null;
  proposal?: ProposalCreateNestedManyWithoutOrganizationsInput;
  regionCode?: string | null;
  registrationDate?: Date | null;
  reportOrganization?: ReportOrganizationCreateNestedManyWithoutOrganizationsInput;
  requestApproval?: RequestApprovalCreateNestedManyWithoutOrganizationsInput;
  requestApprovalEmployee?: RequestApprovalEmployeeCreateNestedManyWithoutOrganizationsInput;
  requestApprovalTeam?: RequestApprovalTeamCreateNestedManyWithoutOrganizationsInput;
  requireClient: boolean;
  requireDescription: boolean;
  requireProject: boolean;
  requireReason: boolean;
  requireTask: boolean;
  screenshot?: ScreenshotCreateNestedManyWithoutOrganizationsInput;
  separateInvoiceItemTaxAndDiscount?: boolean | null;
  shortDescription?: string | null;
  showBonusesPaid?: boolean | null;
  showClients?: boolean | null;
  showClientsCount?: boolean | null;
  showEmployeesCount?: boolean | null;
  showIncome?: boolean | null;
  showMinimumProjectSize?: boolean | null;
  showProfits?: boolean | null;
  showProjectsCount?: boolean | null;
  showTotalHours?: boolean | null;
  skill?: SkillCreateNestedManyWithoutOrganizationsInput;
  skillOrganization?: SkillOrganizationCreateNestedManyWithoutOrganizationsInput;
  startWeekOn?: string | null;
  tag?: TagCreateNestedManyWithoutOrganizationsInput;
  tagOrganization?: TagOrganizationCreateNestedManyWithoutOrganizationsInput;
  task?: TaskCreateNestedManyWithoutOrganizationsInput;
  taskLinkedIssues?: TaskLinkedIssueCreateNestedManyWithoutOrganizationsInput;
  taskPriority?: TaskPriorityCreateNestedManyWithoutOrganizationsInput;
  taskRelatedIssueType?: TaskRelatedIssueTypeCreateNestedManyWithoutOrganizationsInput;
  taskSize?: TaskSizeCreateNestedManyWithoutOrganizationsInput;
  taskStatus?: TaskStatusCreateNestedManyWithoutOrganizationsInput;
  taskVersion?: TaskVersionCreateNestedManyWithoutOrganizationsInput;
  taxId?: string | null;
  tenant?: TenantWhereUniqueInput | null;
  timeFormat: number;
  timeLog?: TimeLogCreateNestedManyWithoutOrganizationsInput;
  timeOffPolicy?: TimeOffPolicyCreateNestedManyWithoutOrganizationsInput;
  timeOffRequest?: TimeOffRequestCreateNestedManyWithoutOrganizationsInput;
  timesheet?: TimesheetCreateNestedManyWithoutOrganizationsInput;
  timeSlot?: TimeSlotCreateNestedManyWithoutOrganizationsInput;
  timeSlotMinute?: TimeSlotMinuteCreateNestedManyWithoutOrganizationsInput;
  timeZone?: string | null;
  totalEmployees?: number | null;
  upworkOrganizationId?: string | null;
  userOrganization?: UserOrganizationCreateNestedManyWithoutOrganizationsInput;
  valueDate?: Date | null;
  warehouse?: WarehouseCreateNestedManyWithoutOrganizationsInput;
  warehouseProduct?: WarehouseProductCreateNestedManyWithoutOrganizationsInput;
  warehouseProductVariant?: WarehouseProductVariantCreateNestedManyWithoutOrganizationsInput;
  website?: string | null;
};
