import { StringFilter } from "../../util/StringFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { OrganizationListRelationFilter } from "../organization/OrganizationListRelationFilter";
import { CandidateWhereUniqueInput } from "../candidate/CandidateWhereUniqueInput";
import { EmployeeWhereUniqueInput } from "../employee/EmployeeWhereUniqueInput";
import { MerchantWhereUniqueInput } from "../merchant/MerchantWhereUniqueInput";
import { OrganizationContactWhereUniqueInput } from "../organizationContact/OrganizationContactWhereUniqueInput";
import { WarehouseWhereUniqueInput } from "../warehouse/WarehouseWhereUniqueInput";

export type ContactWhereInput = {
  id?: StringFilter;
  createdAt?: DateTimeFilter;
  updatedAt?: DateTimeFilter;
  name?: StringNullableFilter;
  firstName?: StringNullableFilter;
  lastName?: StringNullableFilter;
  country?: StringNullableFilter;
  city?: StringNullableFilter;
  address?: StringNullableFilter;
  address2?: StringNullableFilter;
  postcode?: StringNullableFilter;
  regionCode?: StringNullableFilter;
  fax?: StringNullableFilter;
  fiscalInformation?: StringNullableFilter;
  website?: StringNullableFilter;
  latitude?: DecimalNullableFilter;
  longitude?: DecimalNullableFilter;
  tenant?: TenantWhereUniqueInput;
  organizationContactOrganizationIdToorganization?: OrganizationWhereUniqueInput;
  organizationOrganizationContactIdTocontact?: OrganizationListRelationFilter;
  candidate?: CandidateWhereUniqueInput;
  employee?: EmployeeWhereUniqueInput;
  merchant?: MerchantWhereUniqueInput;
  organizationContact?: OrganizationContactWhereUniqueInput;
  warehouse?: WarehouseWhereUniqueInput;
};
