/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { E3WhereInput } from "./E3WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class E3CountArgs {
  @ApiProperty({
    required: false,
    type: () => E3WhereInput,
  })
  @Field(() => E3WhereInput, { nullable: true })
  @Type(() => E3WhereInput)
  where?: E3WhereInput;
}

export { E3CountArgs as E3CountArgs };
