import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { ImageAssetWhereUniqueInput } from "../imageAsset/ImageAssetWhereUniqueInput";
import { ContactWhereUniqueInput } from "../contact/ContactWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { DealWhereUniqueInput } from "../deal/DealWhereUniqueInput";
import { ExpenseUpdateManyWithoutOrganizationContactsInput } from "./ExpenseUpdateManyWithoutOrganizationContactsInput";
import { IncomeUpdateManyWithoutOrganizationContactsInput } from "./IncomeUpdateManyWithoutOrganizationContactsInput";
import { InviteOrganizationContactUpdateManyWithoutOrganizationContactsInput } from "./InviteOrganizationContactUpdateManyWithoutOrganizationContactsInput";
import { InvoiceUpdateManyWithoutOrganizationContactsInput } from "./InvoiceUpdateManyWithoutOrganizationContactsInput";
import { OrganizationContactEmployeeUpdateManyWithoutOrganizationContactsInput } from "./OrganizationContactEmployeeUpdateManyWithoutOrganizationContactsInput";
import { OrganizationProjectUpdateManyWithoutOrganizationContactsInput } from "./OrganizationProjectUpdateManyWithoutOrganizationContactsInput";
import { PaymentUpdateManyWithoutOrganizationContactsInput } from "./PaymentUpdateManyWithoutOrganizationContactsInput";
import { ProposalUpdateManyWithoutOrganizationContactsInput } from "./ProposalUpdateManyWithoutOrganizationContactsInput";
import { TagOrganizationContactUpdateManyWithoutOrganizationContactsInput } from "./TagOrganizationContactUpdateManyWithoutOrganizationContactsInput";
import { TimeLogUpdateManyWithoutOrganizationContactsInput } from "./TimeLogUpdateManyWithoutOrganizationContactsInput";

export type OrganizationContactUpdateInput = {
  name?: string;
  primaryEmail?: string | null;
  primaryPhone?: string | null;
  notes?: string | null;
  imageUrl?: string | null;
  budget?: number | null;
  createdBy?: string | null;
  inviteStatus?: "NOT_INVITED" | "INVITED" | "ACCEPTED" | null;
  contactType?: "CLIENT" | "CUSTOMER" | "LEAD";
  budgetType?: "hours" | "cost" | null;
  organization?: OrganizationWhereUniqueInput | null;
  imageAsset?: ImageAssetWhereUniqueInput | null;
  contact?: ContactWhereUniqueInput | null;
  tenant?: TenantWhereUniqueInput | null;
  deal?: DealWhereUniqueInput | null;
  expense?: ExpenseUpdateManyWithoutOrganizationContactsInput;
  income?: IncomeUpdateManyWithoutOrganizationContactsInput;
  inviteOrganizationContact?: InviteOrganizationContactUpdateManyWithoutOrganizationContactsInput;
  invoice?: InvoiceUpdateManyWithoutOrganizationContactsInput;
  organizationContactEmployee?: OrganizationContactEmployeeUpdateManyWithoutOrganizationContactsInput;
  organizationProject?: OrganizationProjectUpdateManyWithoutOrganizationContactsInput;
  payment?: PaymentUpdateManyWithoutOrganizationContactsInput;
  proposal?: ProposalUpdateManyWithoutOrganizationContactsInput;
  tagOrganizationContact?: TagOrganizationContactUpdateManyWithoutOrganizationContactsInput;
  timeLog?: TimeLogUpdateManyWithoutOrganizationContactsInput;
};
