import { StringFilter } from "../../util/StringFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { ImageAssetWhereUniqueInput } from "../imageAsset/ImageAssetWhereUniqueInput";
import { ContactWhereUniqueInput } from "../contact/ContactWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { DealWhereUniqueInput } from "../deal/DealWhereUniqueInput";
import { ExpenseListRelationFilter } from "../expense/ExpenseListRelationFilter";
import { IncomeListRelationFilter } from "../income/IncomeListRelationFilter";
import { InviteOrganizationContactListRelationFilter } from "../inviteOrganizationContact/InviteOrganizationContactListRelationFilter";
import { InvoiceListRelationFilter } from "../invoice/InvoiceListRelationFilter";
import { OrganizationContactEmployeeListRelationFilter } from "../organizationContactEmployee/OrganizationContactEmployeeListRelationFilter";
import { OrganizationProjectListRelationFilter } from "../organizationProject/OrganizationProjectListRelationFilter";
import { PaymentListRelationFilter } from "../payment/PaymentListRelationFilter";
import { ProposalListRelationFilter } from "../proposal/ProposalListRelationFilter";
import { TagOrganizationContactListRelationFilter } from "../tagOrganizationContact/TagOrganizationContactListRelationFilter";
import { TimeLogListRelationFilter } from "../timeLog/TimeLogListRelationFilter";

export type OrganizationContactWhereInput = {
  id?: StringFilter;
  createdAt?: DateTimeFilter;
  updatedAt?: DateTimeFilter;
  name?: StringFilter;
  primaryEmail?: StringNullableFilter;
  primaryPhone?: StringNullableFilter;
  notes?: StringNullableFilter;
  imageUrl?: StringNullableFilter;
  budget?: IntNullableFilter;
  createdBy?: StringNullableFilter;
  inviteStatus?: "NOT_INVITED" | "INVITED" | "ACCEPTED";
  contactType?: "CLIENT" | "CUSTOMER" | "LEAD";
  budgetType?: "hours" | "cost";
  organization?: OrganizationWhereUniqueInput;
  imageAsset?: ImageAssetWhereUniqueInput;
  contact?: ContactWhereUniqueInput;
  tenant?: TenantWhereUniqueInput;
  deal?: DealWhereUniqueInput;
  expense?: ExpenseListRelationFilter;
  income?: IncomeListRelationFilter;
  inviteOrganizationContact?: InviteOrganizationContactListRelationFilter;
  invoice?: InvoiceListRelationFilter;
  organizationContactEmployee?: OrganizationContactEmployeeListRelationFilter;
  organizationProject?: OrganizationProjectListRelationFilter;
  payment?: PaymentListRelationFilter;
  proposal?: ProposalListRelationFilter;
  tagOrganizationContact?: TagOrganizationContactListRelationFilter;
  timeLog?: TimeLogListRelationFilter;
};
