import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { ImageAssetWhereUniqueInput } from "../imageAsset/ImageAssetWhereUniqueInput";
import { ContactWhereUniqueInput } from "../contact/ContactWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { DealWhereUniqueInput } from "../deal/DealWhereUniqueInput";
import { ExpenseCreateNestedManyWithoutOrganizationContactsInput } from "./ExpenseCreateNestedManyWithoutOrganizationContactsInput";
import { IncomeCreateNestedManyWithoutOrganizationContactsInput } from "./IncomeCreateNestedManyWithoutOrganizationContactsInput";
import { InviteOrganizationContactCreateNestedManyWithoutOrganizationContactsInput } from "./InviteOrganizationContactCreateNestedManyWithoutOrganizationContactsInput";
import { InvoiceCreateNestedManyWithoutOrganizationContactsInput } from "./InvoiceCreateNestedManyWithoutOrganizationContactsInput";
import { OrganizationContactEmployeeCreateNestedManyWithoutOrganizationContactsInput } from "./OrganizationContactEmployeeCreateNestedManyWithoutOrganizationContactsInput";
import { OrganizationProjectCreateNestedManyWithoutOrganizationContactsInput } from "./OrganizationProjectCreateNestedManyWithoutOrganizationContactsInput";
import { PaymentCreateNestedManyWithoutOrganizationContactsInput } from "./PaymentCreateNestedManyWithoutOrganizationContactsInput";
import { ProposalCreateNestedManyWithoutOrganizationContactsInput } from "./ProposalCreateNestedManyWithoutOrganizationContactsInput";
import { TagOrganizationContactCreateNestedManyWithoutOrganizationContactsInput } from "./TagOrganizationContactCreateNestedManyWithoutOrganizationContactsInput";
import { TimeLogCreateNestedManyWithoutOrganizationContactsInput } from "./TimeLogCreateNestedManyWithoutOrganizationContactsInput";

export type OrganizationContactCreateInput = {
  name: string;
  primaryEmail?: string | null;
  primaryPhone?: string | null;
  notes?: string | null;
  imageUrl?: string | null;
  budget?: number | null;
  createdBy?: string | null;
  inviteStatus?: "NOT_INVITED" | "INVITED" | "ACCEPTED" | null;
  contactType: "CLIENT" | "CUSTOMER" | "LEAD";
  budgetType?: "hours" | "cost" | null;
  organization?: OrganizationWhereUniqueInput | null;
  imageAsset?: ImageAssetWhereUniqueInput | null;
  contact?: ContactWhereUniqueInput | null;
  tenant?: TenantWhereUniqueInput | null;
  deal?: DealWhereUniqueInput | null;
  expense?: ExpenseCreateNestedManyWithoutOrganizationContactsInput;
  income?: IncomeCreateNestedManyWithoutOrganizationContactsInput;
  inviteOrganizationContact?: InviteOrganizationContactCreateNestedManyWithoutOrganizationContactsInput;
  invoice?: InvoiceCreateNestedManyWithoutOrganizationContactsInput;
  organizationContactEmployee?: OrganizationContactEmployeeCreateNestedManyWithoutOrganizationContactsInput;
  organizationProject?: OrganizationProjectCreateNestedManyWithoutOrganizationContactsInput;
  payment?: PaymentCreateNestedManyWithoutOrganizationContactsInput;
  proposal?: ProposalCreateNestedManyWithoutOrganizationContactsInput;
  tagOrganizationContact?: TagOrganizationContactCreateNestedManyWithoutOrganizationContactsInput;
  timeLog?: TimeLogCreateNestedManyWithoutOrganizationContactsInput;
};
