import { Organization } from "../organization/Organization";
import { ImageAsset } from "../imageAsset/ImageAsset";
import { Contact } from "../contact/Contact";
import { Tenant } from "../tenant/Tenant";
import { Deal } from "../deal/Deal";
import { Expense } from "../expense/Expense";
import { Income } from "../income/Income";
import { InviteOrganizationContact } from "../inviteOrganizationContact/InviteOrganizationContact";
import { Invoice } from "../invoice/Invoice";
import { OrganizationContactEmployee } from "../organizationContactEmployee/OrganizationContactEmployee";
import { OrganizationProject } from "../organizationProject/OrganizationProject";
import { Payment } from "../payment/Payment";
import { Proposal } from "../proposal/Proposal";
import { TagOrganizationContact } from "../tagOrganizationContact/TagOrganizationContact";
import { TimeLog } from "../timeLog/TimeLog";

export type OrganizationContact = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  name: string;
  primaryEmail: string | null;
  primaryPhone: string | null;
  notes: string | null;
  imageUrl: string | null;
  budget: number | null;
  createdBy: string | null;
  inviteStatus?: "NOT_INVITED" | "INVITED" | "ACCEPTED" | null;
  contactType?: "CLIENT" | "CUSTOMER" | "LEAD";
  budgetType?: "hours" | "cost" | null;
  organization?: Organization | null;
  imageAsset?: ImageAsset | null;
  contact?: Contact | null;
  tenant?: Tenant | null;
  deal?: Deal | null;
  expense?: Array<Expense>;
  income?: Array<Income>;
  inviteOrganizationContact?: Array<InviteOrganizationContact>;
  invoice?: Array<Invoice>;
  organizationContactEmployee?: Array<OrganizationContactEmployee>;
  organizationProject?: Array<OrganizationProject>;
  payment?: Array<Payment>;
  proposal?: Array<Proposal>;
  tagOrganizationContact?: Array<TagOrganizationContact>;
  timeLog?: Array<TimeLog>;
};
