/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ScreenshotService } from "../screenshot.service";
import { ScreenshotCreateInput } from "./ScreenshotCreateInput";
import { ScreenshotWhereInput } from "./ScreenshotWhereInput";
import { ScreenshotWhereUniqueInput } from "./ScreenshotWhereUniqueInput";
import { ScreenshotFindManyArgs } from "./ScreenshotFindManyArgs";
import { ScreenshotUpdateInput } from "./ScreenshotUpdateInput";
import { Screenshot } from "./Screenshot";

export class ScreenshotControllerBase {
  constructor(protected readonly service: ScreenshotService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Screenshot })
  async create(
    @common.Body() data: ScreenshotCreateInput
  ): Promise<Screenshot> {
    return await this.service.create({
      data: {
        ...data,

        organization: data.organization
          ? {
              connect: data.organization,
            }
          : undefined,

        tenant: data.tenant
          ? {
              connect: data.tenant,
            }
          : undefined,

        timeSlot: data.timeSlot
          ? {
              connect: data.timeSlot,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        file: true,
        thumb: true,
        recordedAt: true,
        deletedAt: true,
        storageProvider: true,

        organization: {
          select: {
            id: true,
          },
        },

        tenant: {
          select: {
            id: true,
          },
        },

        timeSlot: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Screenshot] })
  @ApiNestedQuery(ScreenshotFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Screenshot[]> {
    const args = plainToClass(ScreenshotFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        file: true,
        thumb: true,
        recordedAt: true,
        deletedAt: true,
        storageProvider: true,

        organization: {
          select: {
            id: true,
          },
        },

        tenant: {
          select: {
            id: true,
          },
        },

        timeSlot: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Screenshot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: ScreenshotWhereUniqueInput
  ): Promise<Screenshot | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        file: true,
        thumb: true,
        recordedAt: true,
        deletedAt: true,
        storageProvider: true,

        organization: {
          select: {
            id: true,
          },
        },

        tenant: {
          select: {
            id: true,
          },
        },

        timeSlot: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Screenshot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: ScreenshotWhereUniqueInput,
    @common.Body() data: ScreenshotUpdateInput
  ): Promise<Screenshot | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          organization: data.organization
            ? {
                connect: data.organization,
              }
            : undefined,

          tenant: data.tenant
            ? {
                connect: data.tenant,
              }
            : undefined,

          timeSlot: data.timeSlot
            ? {
                connect: data.timeSlot,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          file: true,
          thumb: true,
          recordedAt: true,
          deletedAt: true,
          storageProvider: true,

          organization: {
            select: {
              id: true,
            },
          },

          tenant: {
            select: {
              id: true,
            },
          },

          timeSlot: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Screenshot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: ScreenshotWhereUniqueInput
  ): Promise<Screenshot | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          file: true,
          thumb: true,
          recordedAt: true,
          deletedAt: true,
          storageProvider: true,

          organization: {
            select: {
              id: true,
            },
          },

          tenant: {
            select: {
              id: true,
            },
          },

          timeSlot: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
