import { OrganizationTeam } from "../organizationTeam/OrganizationTeam";
import { Tenant } from "../tenant/Tenant";
import { Organization } from "../organization/Organization";
import { TagCandidate } from "../tagCandidate/TagCandidate";
import { TagEmployee } from "../tagEmployee/TagEmployee";
import { TagEmployeeLevel } from "../tagEmployeeLevel/TagEmployeeLevel";
import { TagEquipment } from "../tagEquipment/TagEquipment";
import { TagEventType } from "../tagEventType/TagEventType";
import { TagExpense } from "../tagExpense/TagExpense";
import { TagIncome } from "../tagIncome/TagIncome";
import { TagIntegration } from "../tagIntegration/TagIntegration";
import { TagInvoice } from "../tagInvoice/TagInvoice";
import { TagMerchant } from "../tagMerchant/TagMerchant";
import { TagOrganization } from "../tagOrganization/TagOrganization";
import { TagOrganizationContact } from "../tagOrganizationContact/TagOrganizationContact";
import { TagOrganizationDepartment } from "../tagOrganizationDepartment/TagOrganizationDepartment";
import { TagOrganizationEmploymentType } from "../tagOrganizationEmploymentType/TagOrganizationEmploymentType";
import { TagOrganizationExpenseCategory } from "../tagOrganizationExpenseCategory/TagOrganizationExpenseCategory";
import { TagOrganizationPosition } from "../tagOrganizationPosition/TagOrganizationPosition";
import { TagOrganizationProject } from "../tagOrganizationProject/TagOrganizationProject";
import { TagOrganizationTeam } from "../tagOrganizationTeam/TagOrganizationTeam";
import { TagOrganizationVendor } from "../tagOrganizationVendor/TagOrganizationVendor";
import { TagPayment } from "../tagPayment/TagPayment";
import { TagProduct } from "../tagProduct/TagProduct";
import { TagProposal } from "../tagProposal/TagProposal";
import { TagRequestApproval } from "../tagRequestApproval/TagRequestApproval";
import { TagTask } from "../tagTask/TagTask";
import { TagUser } from "../tagUser/TagUser";
import { TagWarehouse } from "../tagWarehouse/TagWarehouse";

export type Tag = {
  updatedAt: Date;
  name: string;
  id: string;
  createdAt: Date;
  description: string | null;
  color: string;
  isSystem: boolean;
  icon: string | null;
  organizationTeam?: OrganizationTeam | null;
  tenant?: Tenant | null;
  organization?: Organization | null;
  tagCandidate?: Array<TagCandidate>;
  tagEmployee?: Array<TagEmployee>;
  tagEmployeeLevel?: Array<TagEmployeeLevel>;
  tagEquipment?: Array<TagEquipment>;
  tagEventType?: Array<TagEventType>;
  tagExpense?: Array<TagExpense>;
  tagIncome?: Array<TagIncome>;
  tagIntegration?: Array<TagIntegration>;
  tagInvoice?: Array<TagInvoice>;
  tagMerchant?: Array<TagMerchant>;
  tagOrganization?: Array<TagOrganization>;
  tagOrganizationContact?: Array<TagOrganizationContact>;
  tagOrganizationDepartment?: Array<TagOrganizationDepartment>;
  tagOrganizationEmploymentType?: Array<TagOrganizationEmploymentType>;
  tagOrganizationExpenseCategory?: Array<TagOrganizationExpenseCategory>;
  tagOrganizationPosition?: Array<TagOrganizationPosition>;
  tagOrganizationProject?: Array<TagOrganizationProject>;
  tagOrganizationTeam?: Array<TagOrganizationTeam>;
  tagOrganizationVendor?: Array<TagOrganizationVendor>;
  tagPayment?: Array<TagPayment>;
  tagProduct?: Array<TagProduct>;
  tagProposal?: Array<TagProposal>;
  tagRequestApproval?: Array<TagRequestApproval>;
  tagTask?: Array<TagTask>;
  tagUser?: Array<TagUser>;
  tagWarehouse?: Array<TagWarehouse>;
};
