import { OrganizationTeamWhereUniqueInput } from "../organizationTeam/OrganizationTeamWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { TagCandidateCreateNestedManyWithoutTagsInput } from "./TagCandidateCreateNestedManyWithoutTagsInput";
import { TagEmployeeCreateNestedManyWithoutTagsInput } from "./TagEmployeeCreateNestedManyWithoutTagsInput";
import { TagEmployeeLevelCreateNestedManyWithoutTagsInput } from "./TagEmployeeLevelCreateNestedManyWithoutTagsInput";
import { TagEquipmentCreateNestedManyWithoutTagsInput } from "./TagEquipmentCreateNestedManyWithoutTagsInput";
import { TagEventTypeCreateNestedManyWithoutTagsInput } from "./TagEventTypeCreateNestedManyWithoutTagsInput";
import { TagExpenseCreateNestedManyWithoutTagsInput } from "./TagExpenseCreateNestedManyWithoutTagsInput";
import { TagIncomeCreateNestedManyWithoutTagsInput } from "./TagIncomeCreateNestedManyWithoutTagsInput";
import { TagIntegrationCreateNestedManyWithoutTagsInput } from "./TagIntegrationCreateNestedManyWithoutTagsInput";
import { TagInvoiceCreateNestedManyWithoutTagsInput } from "./TagInvoiceCreateNestedManyWithoutTagsInput";
import { TagMerchantCreateNestedManyWithoutTagsInput } from "./TagMerchantCreateNestedManyWithoutTagsInput";
import { TagOrganizationCreateNestedManyWithoutTagsInput } from "./TagOrganizationCreateNestedManyWithoutTagsInput";
import { TagOrganizationContactCreateNestedManyWithoutTagsInput } from "./TagOrganizationContactCreateNestedManyWithoutTagsInput";
import { TagOrganizationDepartmentCreateNestedManyWithoutTagsInput } from "./TagOrganizationDepartmentCreateNestedManyWithoutTagsInput";
import { TagOrganizationEmploymentTypeCreateNestedManyWithoutTagsInput } from "./TagOrganizationEmploymentTypeCreateNestedManyWithoutTagsInput";
import { TagOrganizationExpenseCategoryCreateNestedManyWithoutTagsInput } from "./TagOrganizationExpenseCategoryCreateNestedManyWithoutTagsInput";
import { TagOrganizationPositionCreateNestedManyWithoutTagsInput } from "./TagOrganizationPositionCreateNestedManyWithoutTagsInput";
import { TagOrganizationProjectCreateNestedManyWithoutTagsInput } from "./TagOrganizationProjectCreateNestedManyWithoutTagsInput";
import { TagOrganizationTeamCreateNestedManyWithoutTagsInput } from "./TagOrganizationTeamCreateNestedManyWithoutTagsInput";
import { TagOrganizationVendorCreateNestedManyWithoutTagsInput } from "./TagOrganizationVendorCreateNestedManyWithoutTagsInput";
import { TagPaymentCreateNestedManyWithoutTagsInput } from "./TagPaymentCreateNestedManyWithoutTagsInput";
import { TagProductCreateNestedManyWithoutTagsInput } from "./TagProductCreateNestedManyWithoutTagsInput";
import { TagProposalCreateNestedManyWithoutTagsInput } from "./TagProposalCreateNestedManyWithoutTagsInput";
import { TagRequestApprovalCreateNestedManyWithoutTagsInput } from "./TagRequestApprovalCreateNestedManyWithoutTagsInput";
import { TagTaskCreateNestedManyWithoutTagsInput } from "./TagTaskCreateNestedManyWithoutTagsInput";
import { TagUserCreateNestedManyWithoutTagsInput } from "./TagUserCreateNestedManyWithoutTagsInput";
import { TagWarehouseCreateNestedManyWithoutTagsInput } from "./TagWarehouseCreateNestedManyWithoutTagsInput";

export type TagCreateInput = {
  name: string;
  description?: string | null;
  color: string;
  isSystem: boolean;
  icon?: string | null;
  organizationTeam?: OrganizationTeamWhereUniqueInput | null;
  tenant?: TenantWhereUniqueInput | null;
  organization?: OrganizationWhereUniqueInput | null;
  tagCandidate?: TagCandidateCreateNestedManyWithoutTagsInput;
  tagEmployee?: TagEmployeeCreateNestedManyWithoutTagsInput;
  tagEmployeeLevel?: TagEmployeeLevelCreateNestedManyWithoutTagsInput;
  tagEquipment?: TagEquipmentCreateNestedManyWithoutTagsInput;
  tagEventType?: TagEventTypeCreateNestedManyWithoutTagsInput;
  tagExpense?: TagExpenseCreateNestedManyWithoutTagsInput;
  tagIncome?: TagIncomeCreateNestedManyWithoutTagsInput;
  tagIntegration?: TagIntegrationCreateNestedManyWithoutTagsInput;
  tagInvoice?: TagInvoiceCreateNestedManyWithoutTagsInput;
  tagMerchant?: TagMerchantCreateNestedManyWithoutTagsInput;
  tagOrganization?: TagOrganizationCreateNestedManyWithoutTagsInput;
  tagOrganizationContact?: TagOrganizationContactCreateNestedManyWithoutTagsInput;
  tagOrganizationDepartment?: TagOrganizationDepartmentCreateNestedManyWithoutTagsInput;
  tagOrganizationEmploymentType?: TagOrganizationEmploymentTypeCreateNestedManyWithoutTagsInput;
  tagOrganizationExpenseCategory?: TagOrganizationExpenseCategoryCreateNestedManyWithoutTagsInput;
  tagOrganizationPosition?: TagOrganizationPositionCreateNestedManyWithoutTagsInput;
  tagOrganizationProject?: TagOrganizationProjectCreateNestedManyWithoutTagsInput;
  tagOrganizationTeam?: TagOrganizationTeamCreateNestedManyWithoutTagsInput;
  tagOrganizationVendor?: TagOrganizationVendorCreateNestedManyWithoutTagsInput;
  tagPayment?: TagPaymentCreateNestedManyWithoutTagsInput;
  tagProduct?: TagProductCreateNestedManyWithoutTagsInput;
  tagProposal?: TagProposalCreateNestedManyWithoutTagsInput;
  tagRequestApproval?: TagRequestApprovalCreateNestedManyWithoutTagsInput;
  tagTask?: TagTaskCreateNestedManyWithoutTagsInput;
  tagUser?: TagUserCreateNestedManyWithoutTagsInput;
  tagWarehouse?: TagWarehouseCreateNestedManyWithoutTagsInput;
};
