import { OrganizationTeamWhereUniqueInput } from "../organizationTeam/OrganizationTeamWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { TagCandidateUpdateManyWithoutTagsInput } from "./TagCandidateUpdateManyWithoutTagsInput";
import { TagEmployeeUpdateManyWithoutTagsInput } from "./TagEmployeeUpdateManyWithoutTagsInput";
import { TagEmployeeLevelUpdateManyWithoutTagsInput } from "./TagEmployeeLevelUpdateManyWithoutTagsInput";
import { TagEquipmentUpdateManyWithoutTagsInput } from "./TagEquipmentUpdateManyWithoutTagsInput";
import { TagEventTypeUpdateManyWithoutTagsInput } from "./TagEventTypeUpdateManyWithoutTagsInput";
import { TagExpenseUpdateManyWithoutTagsInput } from "./TagExpenseUpdateManyWithoutTagsInput";
import { TagIncomeUpdateManyWithoutTagsInput } from "./TagIncomeUpdateManyWithoutTagsInput";
import { TagIntegrationUpdateManyWithoutTagsInput } from "./TagIntegrationUpdateManyWithoutTagsInput";
import { TagInvoiceUpdateManyWithoutTagsInput } from "./TagInvoiceUpdateManyWithoutTagsInput";
import { TagMerchantUpdateManyWithoutTagsInput } from "./TagMerchantUpdateManyWithoutTagsInput";
import { TagOrganizationUpdateManyWithoutTagsInput } from "./TagOrganizationUpdateManyWithoutTagsInput";
import { TagOrganizationContactUpdateManyWithoutTagsInput } from "./TagOrganizationContactUpdateManyWithoutTagsInput";
import { TagOrganizationDepartmentUpdateManyWithoutTagsInput } from "./TagOrganizationDepartmentUpdateManyWithoutTagsInput";
import { TagOrganizationEmploymentTypeUpdateManyWithoutTagsInput } from "./TagOrganizationEmploymentTypeUpdateManyWithoutTagsInput";
import { TagOrganizationExpenseCategoryUpdateManyWithoutTagsInput } from "./TagOrganizationExpenseCategoryUpdateManyWithoutTagsInput";
import { TagOrganizationPositionUpdateManyWithoutTagsInput } from "./TagOrganizationPositionUpdateManyWithoutTagsInput";
import { TagOrganizationProjectUpdateManyWithoutTagsInput } from "./TagOrganizationProjectUpdateManyWithoutTagsInput";
import { TagOrganizationTeamUpdateManyWithoutTagsInput } from "./TagOrganizationTeamUpdateManyWithoutTagsInput";
import { TagOrganizationVendorUpdateManyWithoutTagsInput } from "./TagOrganizationVendorUpdateManyWithoutTagsInput";
import { TagPaymentUpdateManyWithoutTagsInput } from "./TagPaymentUpdateManyWithoutTagsInput";
import { TagProductUpdateManyWithoutTagsInput } from "./TagProductUpdateManyWithoutTagsInput";
import { TagProposalUpdateManyWithoutTagsInput } from "./TagProposalUpdateManyWithoutTagsInput";
import { TagRequestApprovalUpdateManyWithoutTagsInput } from "./TagRequestApprovalUpdateManyWithoutTagsInput";
import { TagTaskUpdateManyWithoutTagsInput } from "./TagTaskUpdateManyWithoutTagsInput";
import { TagUserUpdateManyWithoutTagsInput } from "./TagUserUpdateManyWithoutTagsInput";
import { TagWarehouseUpdateManyWithoutTagsInput } from "./TagWarehouseUpdateManyWithoutTagsInput";

export type TagUpdateInput = {
  name?: string;
  description?: string | null;
  color?: string;
  isSystem?: boolean;
  icon?: string | null;
  organizationTeam?: OrganizationTeamWhereUniqueInput | null;
  tenant?: TenantWhereUniqueInput | null;
  organization?: OrganizationWhereUniqueInput | null;
  tagCandidate?: TagCandidateUpdateManyWithoutTagsInput;
  tagEmployee?: TagEmployeeUpdateManyWithoutTagsInput;
  tagEmployeeLevel?: TagEmployeeLevelUpdateManyWithoutTagsInput;
  tagEquipment?: TagEquipmentUpdateManyWithoutTagsInput;
  tagEventType?: TagEventTypeUpdateManyWithoutTagsInput;
  tagExpense?: TagExpenseUpdateManyWithoutTagsInput;
  tagIncome?: TagIncomeUpdateManyWithoutTagsInput;
  tagIntegration?: TagIntegrationUpdateManyWithoutTagsInput;
  tagInvoice?: TagInvoiceUpdateManyWithoutTagsInput;
  tagMerchant?: TagMerchantUpdateManyWithoutTagsInput;
  tagOrganization?: TagOrganizationUpdateManyWithoutTagsInput;
  tagOrganizationContact?: TagOrganizationContactUpdateManyWithoutTagsInput;
  tagOrganizationDepartment?: TagOrganizationDepartmentUpdateManyWithoutTagsInput;
  tagOrganizationEmploymentType?: TagOrganizationEmploymentTypeUpdateManyWithoutTagsInput;
  tagOrganizationExpenseCategory?: TagOrganizationExpenseCategoryUpdateManyWithoutTagsInput;
  tagOrganizationPosition?: TagOrganizationPositionUpdateManyWithoutTagsInput;
  tagOrganizationProject?: TagOrganizationProjectUpdateManyWithoutTagsInput;
  tagOrganizationTeam?: TagOrganizationTeamUpdateManyWithoutTagsInput;
  tagOrganizationVendor?: TagOrganizationVendorUpdateManyWithoutTagsInput;
  tagPayment?: TagPaymentUpdateManyWithoutTagsInput;
  tagProduct?: TagProductUpdateManyWithoutTagsInput;
  tagProposal?: TagProposalUpdateManyWithoutTagsInput;
  tagRequestApproval?: TagRequestApprovalUpdateManyWithoutTagsInput;
  tagTask?: TagTaskUpdateManyWithoutTagsInput;
  tagUser?: TagUserUpdateManyWithoutTagsInput;
  tagWarehouse?: TagWarehouseUpdateManyWithoutTagsInput;
};
