import { DateTimeFilter } from "../../util/DateTimeFilter";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { OrganizationTeamWhereUniqueInput } from "../organizationTeam/OrganizationTeamWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { TagCandidateListRelationFilter } from "../tagCandidate/TagCandidateListRelationFilter";
import { TagEmployeeListRelationFilter } from "../tagEmployee/TagEmployeeListRelationFilter";
import { TagEmployeeLevelListRelationFilter } from "../tagEmployeeLevel/TagEmployeeLevelListRelationFilter";
import { TagEquipmentListRelationFilter } from "../tagEquipment/TagEquipmentListRelationFilter";
import { TagEventTypeListRelationFilter } from "../tagEventType/TagEventTypeListRelationFilter";
import { TagExpenseListRelationFilter } from "../tagExpense/TagExpenseListRelationFilter";
import { TagIncomeListRelationFilter } from "../tagIncome/TagIncomeListRelationFilter";
import { TagIntegrationListRelationFilter } from "../tagIntegration/TagIntegrationListRelationFilter";
import { TagInvoiceListRelationFilter } from "../tagInvoice/TagInvoiceListRelationFilter";
import { TagMerchantListRelationFilter } from "../tagMerchant/TagMerchantListRelationFilter";
import { TagOrganizationListRelationFilter } from "../tagOrganization/TagOrganizationListRelationFilter";
import { TagOrganizationContactListRelationFilter } from "../tagOrganizationContact/TagOrganizationContactListRelationFilter";
import { TagOrganizationDepartmentListRelationFilter } from "../tagOrganizationDepartment/TagOrganizationDepartmentListRelationFilter";
import { TagOrganizationEmploymentTypeListRelationFilter } from "../tagOrganizationEmploymentType/TagOrganizationEmploymentTypeListRelationFilter";
import { TagOrganizationExpenseCategoryListRelationFilter } from "../tagOrganizationExpenseCategory/TagOrganizationExpenseCategoryListRelationFilter";
import { TagOrganizationPositionListRelationFilter } from "../tagOrganizationPosition/TagOrganizationPositionListRelationFilter";
import { TagOrganizationProjectListRelationFilter } from "../tagOrganizationProject/TagOrganizationProjectListRelationFilter";
import { TagOrganizationTeamListRelationFilter } from "../tagOrganizationTeam/TagOrganizationTeamListRelationFilter";
import { TagOrganizationVendorListRelationFilter } from "../tagOrganizationVendor/TagOrganizationVendorListRelationFilter";
import { TagPaymentListRelationFilter } from "../tagPayment/TagPaymentListRelationFilter";
import { TagProductListRelationFilter } from "../tagProduct/TagProductListRelationFilter";
import { TagProposalListRelationFilter } from "../tagProposal/TagProposalListRelationFilter";
import { TagRequestApprovalListRelationFilter } from "../tagRequestApproval/TagRequestApprovalListRelationFilter";
import { TagTaskListRelationFilter } from "../tagTask/TagTaskListRelationFilter";
import { TagUserListRelationFilter } from "../tagUser/TagUserListRelationFilter";
import { TagWarehouseListRelationFilter } from "../tagWarehouse/TagWarehouseListRelationFilter";

export type TagWhereInput = {
  updatedAt?: DateTimeFilter;
  name?: StringFilter;
  id?: StringFilter;
  createdAt?: DateTimeFilter;
  description?: StringNullableFilter;
  color?: StringFilter;
  isSystem?: BooleanFilter;
  icon?: StringNullableFilter;
  organizationTeam?: OrganizationTeamWhereUniqueInput;
  tenant?: TenantWhereUniqueInput;
  organization?: OrganizationWhereUniqueInput;
  tagCandidate?: TagCandidateListRelationFilter;
  tagEmployee?: TagEmployeeListRelationFilter;
  tagEmployeeLevel?: TagEmployeeLevelListRelationFilter;
  tagEquipment?: TagEquipmentListRelationFilter;
  tagEventType?: TagEventTypeListRelationFilter;
  tagExpense?: TagExpenseListRelationFilter;
  tagIncome?: TagIncomeListRelationFilter;
  tagIntegration?: TagIntegrationListRelationFilter;
  tagInvoice?: TagInvoiceListRelationFilter;
  tagMerchant?: TagMerchantListRelationFilter;
  tagOrganization?: TagOrganizationListRelationFilter;
  tagOrganizationContact?: TagOrganizationContactListRelationFilter;
  tagOrganizationDepartment?: TagOrganizationDepartmentListRelationFilter;
  tagOrganizationEmploymentType?: TagOrganizationEmploymentTypeListRelationFilter;
  tagOrganizationExpenseCategory?: TagOrganizationExpenseCategoryListRelationFilter;
  tagOrganizationPosition?: TagOrganizationPositionListRelationFilter;
  tagOrganizationProject?: TagOrganizationProjectListRelationFilter;
  tagOrganizationTeam?: TagOrganizationTeamListRelationFilter;
  tagOrganizationVendor?: TagOrganizationVendorListRelationFilter;
  tagPayment?: TagPaymentListRelationFilter;
  tagProduct?: TagProductListRelationFilter;
  tagProposal?: TagProposalListRelationFilter;
  tagRequestApproval?: TagRequestApprovalListRelationFilter;
  tagTask?: TagTaskListRelationFilter;
  tagUser?: TagUserListRelationFilter;
  tagWarehouse?: TagWarehouseListRelationFilter;
};
