import { ImageAssetWhereUniqueInput } from "../imageAsset/ImageAssetWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { RoleWhereUniqueInput } from "../role/RoleWhereUniqueInput";
import { CandidateWhereUniqueInput } from "../candidate/CandidateWhereUniqueInput";
import { DealCreateNestedManyWithoutUsersInput } from "./DealCreateNestedManyWithoutUsersInput";
import { EmailResetCreateNestedManyWithoutUsersInput } from "./EmailResetCreateNestedManyWithoutUsersInput";
import { EmailSentCreateNestedManyWithoutUsersInput } from "./EmailSentCreateNestedManyWithoutUsersInput";
import { EmployeeWhereUniqueInput } from "../employee/EmployeeWhereUniqueInput";
import { InviteCreateNestedManyWithoutUsersInput } from "./InviteCreateNestedManyWithoutUsersInput";
import { InvoiceEstimateHistoryCreateNestedManyWithoutUsersInput } from "./InvoiceEstimateHistoryCreateNestedManyWithoutUsersInput";
import { OrganizationTeamCreateNestedManyWithoutUsersInput } from "./OrganizationTeamCreateNestedManyWithoutUsersInput";
import { OrganizationTeamJoinRequestCreateNestedManyWithoutUsersInput } from "./OrganizationTeamJoinRequestCreateNestedManyWithoutUsersInput";
import { PaymentCreateNestedManyWithoutUsersInput } from "./PaymentCreateNestedManyWithoutUsersInput";
import { TagUserCreateNestedManyWithoutUsersInput } from "./TagUserCreateNestedManyWithoutUsersInput";
import { TaskCreateNestedManyWithoutUsersInput } from "./TaskCreateNestedManyWithoutUsersInput";
import { TimesheetCreateNestedManyWithoutUsersInput } from "./TimesheetCreateNestedManyWithoutUsersInput";
import { UserOrganizationCreateNestedManyWithoutUsersInput } from "./UserOrganizationCreateNestedManyWithoutUsersInput";

export type UserCreateInput = {
  thirdPartyId?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  email?: string | null;
  hash?: string | null;
  imageUrl?: string | null;
  preferredLanguage?: string | null;
  refreshToken?: string | null;
  isActive?: boolean | null;
  preferredComponentLayout?: "CARDS_GRID" | "TABLE" | null;
  code?: number | null;
  codeExpireAt?: Date | null;
  emailVerifiedAt?: Date | null;
  emailToken?: string | null;
  phoneNumber?: string | null;
  timeZone?: string | null;
  imageAsset?: ImageAssetWhereUniqueInput | null;
  tenant?: TenantWhereUniqueInput | null;
  role?: RoleWhereUniqueInput | null;
  candidate?: CandidateWhereUniqueInput | null;
  deal?: DealCreateNestedManyWithoutUsersInput;
  emailReset?: EmailResetCreateNestedManyWithoutUsersInput;
  emailSent?: EmailSentCreateNestedManyWithoutUsersInput;
  employee?: EmployeeWhereUniqueInput | null;
  inviteInviteInvitedByIdTouser?: InviteCreateNestedManyWithoutUsersInput;
  inviteInviteUserIdTouser?: InviteCreateNestedManyWithoutUsersInput;
  invoiceEstimateHistory?: InvoiceEstimateHistoryCreateNestedManyWithoutUsersInput;
  organizationTeam?: OrganizationTeamCreateNestedManyWithoutUsersInput;
  organizationTeamJoinRequest?: OrganizationTeamJoinRequestCreateNestedManyWithoutUsersInput;
  payment?: PaymentCreateNestedManyWithoutUsersInput;
  tagUser?: TagUserCreateNestedManyWithoutUsersInput;
  task?: TaskCreateNestedManyWithoutUsersInput;
  timesheet?: TimesheetCreateNestedManyWithoutUsersInput;
  userOrganization?: UserOrganizationCreateNestedManyWithoutUsersInput;
};
