import { ImageAsset } from "../imageAsset/ImageAsset";
import { Tenant } from "../tenant/Tenant";
import { Role } from "../role/Role";
import { Candidate } from "../candidate/Candidate";
import { Deal } from "../deal/Deal";
import { EmailReset } from "../emailReset/EmailReset";
import { EmailSent } from "../emailSent/EmailSent";
import { Employee } from "../employee/Employee";
import { Invite } from "../invite/Invite";
import { InvoiceEstimateHistory } from "../invoiceEstimateHistory/InvoiceEstimateHistory";
import { OrganizationTeam } from "../organizationTeam/OrganizationTeam";
import { OrganizationTeamJoinRequest } from "../organizationTeamJoinRequest/OrganizationTeamJoinRequest";
import { Payment } from "../payment/Payment";
import { TagUser } from "../tagUser/TagUser";
import { Task } from "../task/Task";
import { Timesheet } from "../timesheet/Timesheet";
import { UserOrganization } from "../userOrganization/UserOrganization";

export type User = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  thirdPartyId: string | null;
  firstName: string | null;
  lastName: string | null;
  email: string | null;
  hash: string | null;
  imageUrl: string | null;
  preferredLanguage: string | null;
  refreshToken: string | null;
  isActive: boolean | null;
  preferredComponentLayout?: "CARDS_GRID" | "TABLE" | null;
  code: number | null;
  codeExpireAt: Date | null;
  emailVerifiedAt: Date | null;
  emailToken: string | null;
  phoneNumber: string | null;
  timeZone: string | null;
  imageAsset?: ImageAsset | null;
  tenant?: Tenant | null;
  role?: Role | null;
  candidate?: Candidate | null;
  deal?: Array<Deal>;
  emailReset?: Array<EmailReset>;
  emailSent?: Array<EmailSent>;
  employee?: Employee | null;
  inviteInviteInvitedByIdTouser?: Array<Invite>;
  inviteInviteUserIdTouser?: Array<Invite>;
  invoiceEstimateHistory?: Array<InvoiceEstimateHistory>;
  organizationTeam?: Array<OrganizationTeam>;
  organizationTeamJoinRequest?: Array<OrganizationTeamJoinRequest>;
  payment?: Array<Payment>;
  tagUser?: Array<TagUser>;
  task?: Array<Task>;
  timesheet?: Array<Timesheet>;
  userOrganization?: Array<UserOrganization>;
};
