import { ImageAssetWhereUniqueInput } from "../imageAsset/ImageAssetWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { RoleWhereUniqueInput } from "../role/RoleWhereUniqueInput";
import { CandidateWhereUniqueInput } from "../candidate/CandidateWhereUniqueInput";
import { DealUpdateManyWithoutUsersInput } from "./DealUpdateManyWithoutUsersInput";
import { EmailResetUpdateManyWithoutUsersInput } from "./EmailResetUpdateManyWithoutUsersInput";
import { EmailSentUpdateManyWithoutUsersInput } from "./EmailSentUpdateManyWithoutUsersInput";
import { EmployeeWhereUniqueInput } from "../employee/EmployeeWhereUniqueInput";
import { InviteUpdateManyWithoutUsersInput } from "./InviteUpdateManyWithoutUsersInput";
import { InvoiceEstimateHistoryUpdateManyWithoutUsersInput } from "./InvoiceEstimateHistoryUpdateManyWithoutUsersInput";
import { OrganizationTeamUpdateManyWithoutUsersInput } from "./OrganizationTeamUpdateManyWithoutUsersInput";
import { OrganizationTeamJoinRequestUpdateManyWithoutUsersInput } from "./OrganizationTeamJoinRequestUpdateManyWithoutUsersInput";
import { PaymentUpdateManyWithoutUsersInput } from "./PaymentUpdateManyWithoutUsersInput";
import { TagUserUpdateManyWithoutUsersInput } from "./TagUserUpdateManyWithoutUsersInput";
import { TaskUpdateManyWithoutUsersInput } from "./TaskUpdateManyWithoutUsersInput";
import { TimesheetUpdateManyWithoutUsersInput } from "./TimesheetUpdateManyWithoutUsersInput";
import { UserOrganizationUpdateManyWithoutUsersInput } from "./UserOrganizationUpdateManyWithoutUsersInput";

export type UserUpdateInput = {
  thirdPartyId?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  email?: string | null;
  hash?: string | null;
  imageUrl?: string | null;
  preferredLanguage?: string | null;
  refreshToken?: string | null;
  isActive?: boolean | null;
  preferredComponentLayout?: "CARDS_GRID" | "TABLE" | null;
  code?: number | null;
  codeExpireAt?: Date | null;
  emailVerifiedAt?: Date | null;
  emailToken?: string | null;
  phoneNumber?: string | null;
  timeZone?: string | null;
  imageAsset?: ImageAssetWhereUniqueInput | null;
  tenant?: TenantWhereUniqueInput | null;
  role?: RoleWhereUniqueInput | null;
  candidate?: CandidateWhereUniqueInput | null;
  deal?: DealUpdateManyWithoutUsersInput;
  emailReset?: EmailResetUpdateManyWithoutUsersInput;
  emailSent?: EmailSentUpdateManyWithoutUsersInput;
  employee?: EmployeeWhereUniqueInput | null;
  inviteInviteInvitedByIdTouser?: InviteUpdateManyWithoutUsersInput;
  inviteInviteUserIdTouser?: InviteUpdateManyWithoutUsersInput;
  invoiceEstimateHistory?: InvoiceEstimateHistoryUpdateManyWithoutUsersInput;
  organizationTeam?: OrganizationTeamUpdateManyWithoutUsersInput;
  organizationTeamJoinRequest?: OrganizationTeamJoinRequestUpdateManyWithoutUsersInput;
  payment?: PaymentUpdateManyWithoutUsersInput;
  tagUser?: TagUserUpdateManyWithoutUsersInput;
  task?: TaskUpdateManyWithoutUsersInput;
  timesheet?: TimesheetUpdateManyWithoutUsersInput;
  userOrganization?: UserOrganizationUpdateManyWithoutUsersInput;
};
