import { StringFilter } from "../../util/StringFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { ImageAssetWhereUniqueInput } from "../imageAsset/ImageAssetWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { RoleWhereUniqueInput } from "../role/RoleWhereUniqueInput";
import { CandidateWhereUniqueInput } from "../candidate/CandidateWhereUniqueInput";
import { DealListRelationFilter } from "../deal/DealListRelationFilter";
import { EmailResetListRelationFilter } from "../emailReset/EmailResetListRelationFilter";
import { EmailSentListRelationFilter } from "../emailSent/EmailSentListRelationFilter";
import { EmployeeWhereUniqueInput } from "../employee/EmployeeWhereUniqueInput";
import { InviteListRelationFilter } from "../invite/InviteListRelationFilter";
import { InvoiceEstimateHistoryListRelationFilter } from "../invoiceEstimateHistory/InvoiceEstimateHistoryListRelationFilter";
import { OrganizationTeamListRelationFilter } from "../organizationTeam/OrganizationTeamListRelationFilter";
import { OrganizationTeamJoinRequestListRelationFilter } from "../organizationTeamJoinRequest/OrganizationTeamJoinRequestListRelationFilter";
import { PaymentListRelationFilter } from "../payment/PaymentListRelationFilter";
import { TagUserListRelationFilter } from "../tagUser/TagUserListRelationFilter";
import { TaskListRelationFilter } from "../task/TaskListRelationFilter";
import { TimesheetListRelationFilter } from "../timesheet/TimesheetListRelationFilter";
import { UserOrganizationListRelationFilter } from "../userOrganization/UserOrganizationListRelationFilter";

export type UserWhereInput = {
  id?: StringFilter;
  createdAt?: DateTimeFilter;
  updatedAt?: DateTimeFilter;
  thirdPartyId?: StringNullableFilter;
  firstName?: StringNullableFilter;
  lastName?: StringNullableFilter;
  email?: StringNullableFilter;
  hash?: StringNullableFilter;
  imageUrl?: StringNullableFilter;
  preferredLanguage?: StringNullableFilter;
  refreshToken?: StringNullableFilter;
  isActive?: BooleanNullableFilter;
  preferredComponentLayout?: "CARDS_GRID" | "TABLE";
  code?: IntNullableFilter;
  codeExpireAt?: DateTimeNullableFilter;
  emailVerifiedAt?: DateTimeNullableFilter;
  emailToken?: StringNullableFilter;
  phoneNumber?: StringNullableFilter;
  timeZone?: StringNullableFilter;
  imageAsset?: ImageAssetWhereUniqueInput;
  tenant?: TenantWhereUniqueInput;
  role?: RoleWhereUniqueInput;
  candidate?: CandidateWhereUniqueInput;
  deal?: DealListRelationFilter;
  emailReset?: EmailResetListRelationFilter;
  emailSent?: EmailSentListRelationFilter;
  employee?: EmployeeWhereUniqueInput;
  inviteInviteInvitedByIdTouser?: InviteListRelationFilter;
  inviteInviteUserIdTouser?: InviteListRelationFilter;
  invoiceEstimateHistory?: InvoiceEstimateHistoryListRelationFilter;
  organizationTeam?: OrganizationTeamListRelationFilter;
  organizationTeamJoinRequest?: OrganizationTeamJoinRequestListRelationFilter;
  payment?: PaymentListRelationFilter;
  tagUser?: TagUserListRelationFilter;
  task?: TaskListRelationFilter;
  timesheet?: TimesheetListRelationFilter;
  userOrganization?: UserOrganizationListRelationFilter;
};
