/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsInt, ValidateNested, IsOptional } from "class-validator";
import { CandidateFeedbackWhereUniqueInput } from "../../candidateFeedback/base/CandidateFeedbackWhereUniqueInput";
import { Type } from "class-transformer";
import { TenantWhereUniqueInput } from "../../tenant/base/TenantWhereUniqueInput";
import { OrganizationWhereUniqueInput } from "../../organization/base/OrganizationWhereUniqueInput";
import { CandidatePersonalQualityWhereUniqueInput } from "../../candidatePersonalQuality/base/CandidatePersonalQualityWhereUniqueInput";
import { CandidateTechnologyWhereUniqueInput } from "../../candidateTechnology/base/CandidateTechnologyWhereUniqueInput";

@InputType()
class CandidateCriterionRatingCreateInput {
  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  rating!: number;

  @ApiProperty({
    required: false,
    type: () => CandidateFeedbackWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CandidateFeedbackWhereUniqueInput)
  @IsOptional()
  @Field(() => CandidateFeedbackWhereUniqueInput, {
    nullable: true,
  })
  candidateFeedback?: CandidateFeedbackWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TenantWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TenantWhereUniqueInput)
  @IsOptional()
  @Field(() => TenantWhereUniqueInput, {
    nullable: true,
  })
  tenant?: TenantWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => OrganizationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => OrganizationWhereUniqueInput)
  @IsOptional()
  @Field(() => OrganizationWhereUniqueInput, {
    nullable: true,
  })
  organization?: OrganizationWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => CandidatePersonalQualityWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CandidatePersonalQualityWhereUniqueInput)
  @IsOptional()
  @Field(() => CandidatePersonalQualityWhereUniqueInput, {
    nullable: true,
  })
  candidatePersonalQuality?: CandidatePersonalQualityWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => CandidateTechnologyWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CandidateTechnologyWhereUniqueInput)
  @IsOptional()
  @Field(() => CandidateTechnologyWhereUniqueInput, {
    nullable: true,
  })
  candidateTechnology?: CandidateTechnologyWhereUniqueInput | null;
}

export { CandidateCriterionRatingCreateInput as CandidateCriterionRatingCreateInput };
