import { StringFilter } from "../../util/StringFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntFilter } from "../../util/IntFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { OrganizationProjectWhereUniqueInput } from "../organizationProject/OrganizationProjectWhereUniqueInput";
import { GoalKpiWhereUniqueInput } from "../goalKpi/GoalKpiWhereUniqueInput";
import { EmployeeWhereUniqueInput } from "../employee/EmployeeWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { TaskWhereUniqueInput } from "../task/TaskWhereUniqueInput";
import { GoalListRelationFilter } from "../goal/GoalListRelationFilter";
import { GoalWhereUniqueInput } from "../goal/GoalWhereUniqueInput";
import { KeyResultUpdateListRelationFilter } from "../keyResultUpdate/KeyResultUpdateListRelationFilter";

export type KeyResultWhereInput = {
  id?: StringFilter;
  createdAt?: DateTimeFilter;
  updatedAt?: DateTimeFilter;
  name?: StringFilter;
  description?: StringFilter;
  typeField?: StringFilter;
  targetValue?: IntNullableFilter;
  initialValue?: IntNullableFilter;
  unit?: StringNullableFilter;
  update?: IntFilter;
  progress?: IntFilter;
  deadline?: StringFilter;
  hardDeadline?: DateTimeNullableFilter;
  softDeadline?: DateTimeNullableFilter;
  status?: StringFilter;
  weight?: StringNullableFilter;
  organizationProject?: OrganizationProjectWhereUniqueInput;
  goalKpi?: GoalKpiWhereUniqueInput;
  employeeKeyResultOwnerIdToemployee?: EmployeeWhereUniqueInput;
  tenant?: TenantWhereUniqueInput;
  employeeKeyResultLeadIdToemployee?: EmployeeWhereUniqueInput;
  organization?: OrganizationWhereUniqueInput;
  task?: TaskWhereUniqueInput;
  goalGoalAlignedKeyResultIdTokeyResult?: GoalListRelationFilter;
  goalKeyResultGoalIdTogoal?: GoalWhereUniqueInput;
  keyResultUpdate?: KeyResultUpdateListRelationFilter;
};
