import { EmployeeUpworkJobSearchCriterion } from "../employeeUpworkJobSearchCriterion/EmployeeUpworkJobSearchCriterion";
import { EquipmentSharesEmployee } from "../equipmentSharesEmployee/EquipmentSharesEmployee";
import { EventType } from "../eventType/EventType";
import { Expense } from "../expense/Expense";
import { Goal } from "../goal/Goal";
import { GoalKpi } from "../goalKpi/GoalKpi";
import { GoalKpiTemplate } from "../goalKpiTemplate/GoalKpiTemplate";
import { Income } from "../income/Income";
import { InvoiceItem } from "../invoiceItem/InvoiceItem";
import { Decimal } from "decimal.js";
import { KeyResult } from "../keyResult/KeyResult";
import { KnowledgeBaseAuthor } from "../knowledgeBaseAuthor/KnowledgeBaseAuthor";
import { Activity } from "../activity/Activity";
import { AppointmentEmployee } from "../appointmentEmployee/AppointmentEmployee";
import { AvailabilitySlot } from "../availabilitySlot/AvailabilitySlot";
import { Candidate } from "../candidate/Candidate";
import { CandidateInterviewer } from "../candidateInterviewer/CandidateInterviewer";
import { Contact } from "../contact/Contact";
import { EmployeeAppointment } from "../employeeAppointment/EmployeeAppointment";
import { EmployeeAward } from "../employeeAward/EmployeeAward";
import { EmployeeJobPreset } from "../employeeJobPreset/EmployeeJobPreset";
import { EmployeePhone } from "../employeePhone/EmployeePhone";
import { EmployeeProposalTemplate } from "../employeeProposalTemplate/EmployeeProposalTemplate";
import { EmployeeRecurringExpense } from "../employeeRecurringExpense/EmployeeRecurringExpense";
import { EmployeeSetting } from "../employeeSetting/EmployeeSetting";
import { EmployeeTasksTask } from "../employeeTasksTask/EmployeeTasksTask";
import { Organization } from "../organization/Organization";
import { OrganizationContactEmployee } from "../organizationContactEmployee/OrganizationContactEmployee";
import { OrganizationDepartmentEmployee } from "../organizationDepartmentEmployee/OrganizationDepartmentEmployee";
import { OrganizationEmploymentTypeEmployee } from "../organizationEmploymentTypeEmployee/OrganizationEmploymentTypeEmployee";
import { OrganizationPosition } from "../organizationPosition/OrganizationPosition";
import { OrganizationProjectEmployee } from "../organizationProjectEmployee/OrganizationProjectEmployee";
import { OrganizationTeamEmployee } from "../organizationTeamEmployee/OrganizationTeamEmployee";
import { Payment } from "../payment/Payment";
import { Proposal } from "../proposal/Proposal";
import { RequestApprovalEmployee } from "../requestApprovalEmployee/RequestApprovalEmployee";
import { SkillEmployee } from "../skillEmployee/SkillEmployee";
import { TagEmployee } from "../tagEmployee/TagEmployee";
import { TaskEmployee } from "../taskEmployee/TaskEmployee";
import { Tenant } from "../tenant/Tenant";
import { TimeLog } from "../timeLog/TimeLog";
import { TimeOffPolicyEmployee } from "../timeOffPolicyEmployee/TimeOffPolicyEmployee";
import { TimeOffRequestEmployee } from "../timeOffRequestEmployee/TimeOffRequestEmployee";
import { Timesheet } from "../timesheet/Timesheet";
import { TimeSlot } from "../timeSlot/TimeSlot";
import { User } from "../user/User";

export type Employee = {
  employeeUpworkJobSearchCriterion?: Array<EmployeeUpworkJobSearchCriterion>;
  endWork: Date | null;
  equipmentSharesEmployees?: Array<EquipmentSharesEmployee>;
  eventType?: Array<EventType>;
  expense?: Array<Expense>;
  facebookUrl: string | null;
  githubUrl: string | null;
  gitlabUrl: string | null;
  goalGoalLeadIdToemployee?: Array<Goal>;
  goalGoalOwnerEmployeeIdToemployee?: Array<Goal>;
  goalKpi?: Array<GoalKpi>;
  goalKpiTemplate?: Array<GoalKpiTemplate>;
  id: string;
  income?: Array<Income>;
  instagramUrl: string | null;
  invoiceItem?: Array<InvoiceItem>;
  isActive: boolean | null;
  isAway: boolean | null;
  isJobSearchActive: boolean | null;
  isOnline: boolean | null;
  isTrackingEnabled: boolean | null;
  isTrackingTime: boolean | null;
  isVerified: boolean | null;
  isVetted: boolean | null;
  jobSuccess: Decimal | null;
  keyResultKeyResultLeadIdToemployee?: Array<KeyResult>;
  keyResultKeyResultOwnerIdToemployee?: Array<KeyResult>;
  knowledgeBaseAuthor?: Array<KnowledgeBaseAuthor>;
  acceptDate: Date | null;
  activity?: Array<Activity>;
  allowScreenshotCapture: boolean;
  anonymousBonus: boolean | null;
  appointmentEmployee?: Array<AppointmentEmployee>;
  availabilitySlot?: Array<AvailabilitySlot>;
  averageBonus: Decimal | null;
  averageExpenses: Decimal | null;
  averageIncome: Decimal | null;
  billRateCurrency: string | null;
  billRateValue: number | null;
  candidate?: Candidate | null;
  candidateInterviewer?: Array<CandidateInterviewer>;
  contact?: Contact | null;
  createdAt: Date;
  deletedAt: Date | null;
  description: string | null;
  employeeAppointment?: Array<EmployeeAppointment>;
  employeeAward?: Array<EmployeeAward>;
  employeeJobPreset?: Array<EmployeeJobPreset>;
  employeeLevel: string | null;
  employeePhone?: Array<EmployeePhone>;
  employeeProposalTemplate?: Array<EmployeeProposalTemplate>;
  employeeRecurringExpense?: Array<EmployeeRecurringExpense>;
  employeeSetting?: Array<EmployeeSetting>;
  employeeTasksTask?: Array<EmployeeTasksTask>;
  linkedInId: string | null;
  linkedInUrl: string | null;
  minimumBillingRate: number | null;
  offerDate: Date | null;
  organization?: Organization | null;
  organizationContactEmployee?: Array<OrganizationContactEmployee>;
  organizationDepartmentEmployee?: Array<OrganizationDepartmentEmployee>;
  organizationEmploymentTypeEmployee?: Array<OrganizationEmploymentTypeEmployee>;
  organizationPosition?: OrganizationPosition | null;
  organizationProjectEmployee?: Array<OrganizationProjectEmployee>;
  organizationTeamEmployee?: Array<OrganizationTeamEmployee>;
  payment?: Array<Payment>;
  payPeriod: string | null;
  profileLink: string | null;
  proposal?: Array<Proposal>;
  rejectDate: Date | null;
  requestApprovalEmployee?: Array<RequestApprovalEmployee>;
  reWeeklyLimit: number | null;
  shortDescription: string | null;
  showAnonymousBonus: boolean | null;
  showAverageBonus: boolean | null;
  showAverageExpenses: boolean | null;
  showAverageIncome: boolean | null;
  showBillrate: boolean | null;
  showPayperiod: boolean | null;
  showStartWorkOn: boolean | null;
  skillEmployee?: Array<SkillEmployee>;
  stackoverflowUrl: string | null;
  startedWorkOn: Date | null;
  tagEmployee?: Array<TagEmployee>;
  taskEmployee?: Array<TaskEmployee>;
  tenant?: Tenant | null;
  timeLog?: Array<TimeLog>;
  timeOffPolicyEmployee?: Array<TimeOffPolicyEmployee>;
  timeOffRequestEmployee?: Array<TimeOffRequestEmployee>;
  timesheet?: Array<Timesheet>;
  timeSlot?: Array<TimeSlot>;
  totalJobs: Decimal | null;
  totalWorkHours: Decimal | null;
  twitterUrl: string | null;
  updatedAt: Date;
  upworkId: string | null;
  upworkUrl: string | null;
  user?: User;
  valueDate: Date | null;
};
