import { EmployeeUpworkJobSearchCriterionCreateNestedManyWithoutEmployeesInput } from "./EmployeeUpworkJobSearchCriterionCreateNestedManyWithoutEmployeesInput";
import { EquipmentSharesEmployeeCreateNestedManyWithoutEmployeesInput } from "./EquipmentSharesEmployeeCreateNestedManyWithoutEmployeesInput";
import { EventTypeCreateNestedManyWithoutEmployeesInput } from "./EventTypeCreateNestedManyWithoutEmployeesInput";
import { ExpenseCreateNestedManyWithoutEmployeesInput } from "./ExpenseCreateNestedManyWithoutEmployeesInput";
import { GoalCreateNestedManyWithoutEmployeesInput } from "./GoalCreateNestedManyWithoutEmployeesInput";
import { GoalKpiCreateNestedManyWithoutEmployeesInput } from "./GoalKpiCreateNestedManyWithoutEmployeesInput";
import { GoalKpiTemplateCreateNestedManyWithoutEmployeesInput } from "./GoalKpiTemplateCreateNestedManyWithoutEmployeesInput";
import { IncomeCreateNestedManyWithoutEmployeesInput } from "./IncomeCreateNestedManyWithoutEmployeesInput";
import { InvoiceItemCreateNestedManyWithoutEmployeesInput } from "./InvoiceItemCreateNestedManyWithoutEmployeesInput";
import { Decimal } from "decimal.js";
import { KeyResultCreateNestedManyWithoutEmployeesInput } from "./KeyResultCreateNestedManyWithoutEmployeesInput";
import { KnowledgeBaseAuthorCreateNestedManyWithoutEmployeesInput } from "./KnowledgeBaseAuthorCreateNestedManyWithoutEmployeesInput";
import { ActivityCreateNestedManyWithoutEmployeesInput } from "./ActivityCreateNestedManyWithoutEmployeesInput";
import { AppointmentEmployeeCreateNestedManyWithoutEmployeesInput } from "./AppointmentEmployeeCreateNestedManyWithoutEmployeesInput";
import { AvailabilitySlotCreateNestedManyWithoutEmployeesInput } from "./AvailabilitySlotCreateNestedManyWithoutEmployeesInput";
import { CandidateWhereUniqueInput } from "../candidate/CandidateWhereUniqueInput";
import { CandidateInterviewerCreateNestedManyWithoutEmployeesInput } from "./CandidateInterviewerCreateNestedManyWithoutEmployeesInput";
import { ContactWhereUniqueInput } from "../contact/ContactWhereUniqueInput";
import { EmployeeAppointmentCreateNestedManyWithoutEmployeesInput } from "./EmployeeAppointmentCreateNestedManyWithoutEmployeesInput";
import { EmployeeAwardCreateNestedManyWithoutEmployeesInput } from "./EmployeeAwardCreateNestedManyWithoutEmployeesInput";
import { EmployeeJobPresetCreateNestedManyWithoutEmployeesInput } from "./EmployeeJobPresetCreateNestedManyWithoutEmployeesInput";
import { EmployeePhoneCreateNestedManyWithoutEmployeesInput } from "./EmployeePhoneCreateNestedManyWithoutEmployeesInput";
import { EmployeeProposalTemplateCreateNestedManyWithoutEmployeesInput } from "./EmployeeProposalTemplateCreateNestedManyWithoutEmployeesInput";
import { EmployeeRecurringExpenseCreateNestedManyWithoutEmployeesInput } from "./EmployeeRecurringExpenseCreateNestedManyWithoutEmployeesInput";
import { EmployeeSettingCreateNestedManyWithoutEmployeesInput } from "./EmployeeSettingCreateNestedManyWithoutEmployeesInput";
import { EmployeeTasksTaskCreateNestedManyWithoutEmployeesInput } from "./EmployeeTasksTaskCreateNestedManyWithoutEmployeesInput";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { OrganizationContactEmployeeCreateNestedManyWithoutEmployeesInput } from "./OrganizationContactEmployeeCreateNestedManyWithoutEmployeesInput";
import { OrganizationDepartmentEmployeeCreateNestedManyWithoutEmployeesInput } from "./OrganizationDepartmentEmployeeCreateNestedManyWithoutEmployeesInput";
import { OrganizationEmploymentTypeEmployeeCreateNestedManyWithoutEmployeesInput } from "./OrganizationEmploymentTypeEmployeeCreateNestedManyWithoutEmployeesInput";
import { OrganizationPositionWhereUniqueInput } from "../organizationPosition/OrganizationPositionWhereUniqueInput";
import { OrganizationProjectEmployeeCreateNestedManyWithoutEmployeesInput } from "./OrganizationProjectEmployeeCreateNestedManyWithoutEmployeesInput";
import { OrganizationTeamEmployeeCreateNestedManyWithoutEmployeesInput } from "./OrganizationTeamEmployeeCreateNestedManyWithoutEmployeesInput";
import { PaymentCreateNestedManyWithoutEmployeesInput } from "./PaymentCreateNestedManyWithoutEmployeesInput";
import { ProposalCreateNestedManyWithoutEmployeesInput } from "./ProposalCreateNestedManyWithoutEmployeesInput";
import { RequestApprovalEmployeeCreateNestedManyWithoutEmployeesInput } from "./RequestApprovalEmployeeCreateNestedManyWithoutEmployeesInput";
import { SkillEmployeeCreateNestedManyWithoutEmployeesInput } from "./SkillEmployeeCreateNestedManyWithoutEmployeesInput";
import { TagEmployeeCreateNestedManyWithoutEmployeesInput } from "./TagEmployeeCreateNestedManyWithoutEmployeesInput";
import { TaskEmployeeCreateNestedManyWithoutEmployeesInput } from "./TaskEmployeeCreateNestedManyWithoutEmployeesInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { TimeLogCreateNestedManyWithoutEmployeesInput } from "./TimeLogCreateNestedManyWithoutEmployeesInput";
import { TimeOffPolicyEmployeeCreateNestedManyWithoutEmployeesInput } from "./TimeOffPolicyEmployeeCreateNestedManyWithoutEmployeesInput";
import { TimeOffRequestEmployeeCreateNestedManyWithoutEmployeesInput } from "./TimeOffRequestEmployeeCreateNestedManyWithoutEmployeesInput";
import { TimesheetCreateNestedManyWithoutEmployeesInput } from "./TimesheetCreateNestedManyWithoutEmployeesInput";
import { TimeSlotCreateNestedManyWithoutEmployeesInput } from "./TimeSlotCreateNestedManyWithoutEmployeesInput";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";

export type EmployeeCreateInput = {
  employeeUpworkJobSearchCriterion?: EmployeeUpworkJobSearchCriterionCreateNestedManyWithoutEmployeesInput;
  endWork?: Date | null;
  equipmentSharesEmployees?: EquipmentSharesEmployeeCreateNestedManyWithoutEmployeesInput;
  eventType?: EventTypeCreateNestedManyWithoutEmployeesInput;
  expense?: ExpenseCreateNestedManyWithoutEmployeesInput;
  facebookUrl?: string | null;
  githubUrl?: string | null;
  gitlabUrl?: string | null;
  goalGoalLeadIdToemployee?: GoalCreateNestedManyWithoutEmployeesInput;
  goalGoalOwnerEmployeeIdToemployee?: GoalCreateNestedManyWithoutEmployeesInput;
  goalKpi?: GoalKpiCreateNestedManyWithoutEmployeesInput;
  goalKpiTemplate?: GoalKpiTemplateCreateNestedManyWithoutEmployeesInput;
  income?: IncomeCreateNestedManyWithoutEmployeesInput;
  instagramUrl?: string | null;
  invoiceItem?: InvoiceItemCreateNestedManyWithoutEmployeesInput;
  isActive?: boolean | null;
  isAway?: boolean | null;
  isJobSearchActive?: boolean | null;
  isOnline?: boolean | null;
  isTrackingEnabled?: boolean | null;
  isTrackingTime?: boolean | null;
  isVerified?: boolean | null;
  isVetted?: boolean | null;
  jobSuccess?: Decimal | null;
  keyResultKeyResultLeadIdToemployee?: KeyResultCreateNestedManyWithoutEmployeesInput;
  keyResultKeyResultOwnerIdToemployee?: KeyResultCreateNestedManyWithoutEmployeesInput;
  knowledgeBaseAuthor?: KnowledgeBaseAuthorCreateNestedManyWithoutEmployeesInput;
  acceptDate?: Date | null;
  activity?: ActivityCreateNestedManyWithoutEmployeesInput;
  allowScreenshotCapture: boolean;
  anonymousBonus?: boolean | null;
  appointmentEmployee?: AppointmentEmployeeCreateNestedManyWithoutEmployeesInput;
  availabilitySlot?: AvailabilitySlotCreateNestedManyWithoutEmployeesInput;
  averageBonus?: Decimal | null;
  averageExpenses?: Decimal | null;
  averageIncome?: Decimal | null;
  billRateCurrency?: string | null;
  billRateValue?: number | null;
  candidate?: CandidateWhereUniqueInput | null;
  candidateInterviewer?: CandidateInterviewerCreateNestedManyWithoutEmployeesInput;
  contact?: ContactWhereUniqueInput | null;
  deletedAt?: Date | null;
  description?: string | null;
  employeeAppointment?: EmployeeAppointmentCreateNestedManyWithoutEmployeesInput;
  employeeAward?: EmployeeAwardCreateNestedManyWithoutEmployeesInput;
  employeeJobPreset?: EmployeeJobPresetCreateNestedManyWithoutEmployeesInput;
  employeeLevel?: string | null;
  employeePhone?: EmployeePhoneCreateNestedManyWithoutEmployeesInput;
  employeeProposalTemplate?: EmployeeProposalTemplateCreateNestedManyWithoutEmployeesInput;
  employeeRecurringExpense?: EmployeeRecurringExpenseCreateNestedManyWithoutEmployeesInput;
  employeeSetting?: EmployeeSettingCreateNestedManyWithoutEmployeesInput;
  employeeTasksTask?: EmployeeTasksTaskCreateNestedManyWithoutEmployeesInput;
  linkedInId?: string | null;
  linkedInUrl?: string | null;
  minimumBillingRate?: number | null;
  offerDate?: Date | null;
  organization?: OrganizationWhereUniqueInput | null;
  organizationContactEmployee?: OrganizationContactEmployeeCreateNestedManyWithoutEmployeesInput;
  organizationDepartmentEmployee?: OrganizationDepartmentEmployeeCreateNestedManyWithoutEmployeesInput;
  organizationEmploymentTypeEmployee?: OrganizationEmploymentTypeEmployeeCreateNestedManyWithoutEmployeesInput;
  organizationPosition?: OrganizationPositionWhereUniqueInput | null;
  organizationProjectEmployee?: OrganizationProjectEmployeeCreateNestedManyWithoutEmployeesInput;
  organizationTeamEmployee?: OrganizationTeamEmployeeCreateNestedManyWithoutEmployeesInput;
  payment?: PaymentCreateNestedManyWithoutEmployeesInput;
  payPeriod?: string | null;
  profileLink?: string | null;
  proposal?: ProposalCreateNestedManyWithoutEmployeesInput;
  rejectDate?: Date | null;
  requestApprovalEmployee?: RequestApprovalEmployeeCreateNestedManyWithoutEmployeesInput;
  reWeeklyLimit?: number | null;
  shortDescription?: string | null;
  showAnonymousBonus?: boolean | null;
  showAverageBonus?: boolean | null;
  showAverageExpenses?: boolean | null;
  showAverageIncome?: boolean | null;
  showBillrate?: boolean | null;
  showPayperiod?: boolean | null;
  showStartWorkOn?: boolean | null;
  skillEmployee?: SkillEmployeeCreateNestedManyWithoutEmployeesInput;
  stackoverflowUrl?: string | null;
  startedWorkOn?: Date | null;
  tagEmployee?: TagEmployeeCreateNestedManyWithoutEmployeesInput;
  taskEmployee?: TaskEmployeeCreateNestedManyWithoutEmployeesInput;
  tenant?: TenantWhereUniqueInput | null;
  timeLog?: TimeLogCreateNestedManyWithoutEmployeesInput;
  timeOffPolicyEmployee?: TimeOffPolicyEmployeeCreateNestedManyWithoutEmployeesInput;
  timeOffRequestEmployee?: TimeOffRequestEmployeeCreateNestedManyWithoutEmployeesInput;
  timesheet?: TimesheetCreateNestedManyWithoutEmployeesInput;
  timeSlot?: TimeSlotCreateNestedManyWithoutEmployeesInput;
  totalJobs?: Decimal | null;
  totalWorkHours?: Decimal | null;
  twitterUrl?: string | null;
  upworkId?: string | null;
  upworkUrl?: string | null;
  user: UserWhereUniqueInput;
  valueDate?: Date | null;
};
