import { EmployeeUpworkJobSearchCriterionListRelationFilter } from "../employeeUpworkJobSearchCriterion/EmployeeUpworkJobSearchCriterionListRelationFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { EquipmentSharesEmployeeListRelationFilter } from "../equipmentSharesEmployee/EquipmentSharesEmployeeListRelationFilter";
import { EventTypeListRelationFilter } from "../eventType/EventTypeListRelationFilter";
import { ExpenseListRelationFilter } from "../expense/ExpenseListRelationFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { GoalListRelationFilter } from "../goal/GoalListRelationFilter";
import { GoalKpiListRelationFilter } from "../goalKpi/GoalKpiListRelationFilter";
import { GoalKpiTemplateListRelationFilter } from "../goalKpiTemplate/GoalKpiTemplateListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { IncomeListRelationFilter } from "../income/IncomeListRelationFilter";
import { InvoiceItemListRelationFilter } from "../invoiceItem/InvoiceItemListRelationFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { DecimalNullableFilter } from "../../util/DecimalNullableFilter";
import { KeyResultListRelationFilter } from "../keyResult/KeyResultListRelationFilter";
import { KnowledgeBaseAuthorListRelationFilter } from "../knowledgeBaseAuthor/KnowledgeBaseAuthorListRelationFilter";
import { ActivityListRelationFilter } from "../activity/ActivityListRelationFilter";
import { BooleanFilter } from "../../util/BooleanFilter";
import { AppointmentEmployeeListRelationFilter } from "../appointmentEmployee/AppointmentEmployeeListRelationFilter";
import { AvailabilitySlotListRelationFilter } from "../availabilitySlot/AvailabilitySlotListRelationFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { CandidateWhereUniqueInput } from "../candidate/CandidateWhereUniqueInput";
import { CandidateInterviewerListRelationFilter } from "../candidateInterviewer/CandidateInterviewerListRelationFilter";
import { ContactWhereUniqueInput } from "../contact/ContactWhereUniqueInput";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { EmployeeAppointmentListRelationFilter } from "../employeeAppointment/EmployeeAppointmentListRelationFilter";
import { EmployeeAwardListRelationFilter } from "../employeeAward/EmployeeAwardListRelationFilter";
import { EmployeeJobPresetListRelationFilter } from "../employeeJobPreset/EmployeeJobPresetListRelationFilter";
import { EmployeePhoneListRelationFilter } from "../employeePhone/EmployeePhoneListRelationFilter";
import { EmployeeProposalTemplateListRelationFilter } from "../employeeProposalTemplate/EmployeeProposalTemplateListRelationFilter";
import { EmployeeRecurringExpenseListRelationFilter } from "../employeeRecurringExpense/EmployeeRecurringExpenseListRelationFilter";
import { EmployeeSettingListRelationFilter } from "../employeeSetting/EmployeeSettingListRelationFilter";
import { EmployeeTasksTaskListRelationFilter } from "../employeeTasksTask/EmployeeTasksTaskListRelationFilter";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { OrganizationContactEmployeeListRelationFilter } from "../organizationContactEmployee/OrganizationContactEmployeeListRelationFilter";
import { OrganizationDepartmentEmployeeListRelationFilter } from "../organizationDepartmentEmployee/OrganizationDepartmentEmployeeListRelationFilter";
import { OrganizationEmploymentTypeEmployeeListRelationFilter } from "../organizationEmploymentTypeEmployee/OrganizationEmploymentTypeEmployeeListRelationFilter";
import { OrganizationPositionWhereUniqueInput } from "../organizationPosition/OrganizationPositionWhereUniqueInput";
import { OrganizationProjectEmployeeListRelationFilter } from "../organizationProjectEmployee/OrganizationProjectEmployeeListRelationFilter";
import { OrganizationTeamEmployeeListRelationFilter } from "../organizationTeamEmployee/OrganizationTeamEmployeeListRelationFilter";
import { PaymentListRelationFilter } from "../payment/PaymentListRelationFilter";
import { ProposalListRelationFilter } from "../proposal/ProposalListRelationFilter";
import { RequestApprovalEmployeeListRelationFilter } from "../requestApprovalEmployee/RequestApprovalEmployeeListRelationFilter";
import { SkillEmployeeListRelationFilter } from "../skillEmployee/SkillEmployeeListRelationFilter";
import { TagEmployeeListRelationFilter } from "../tagEmployee/TagEmployeeListRelationFilter";
import { TaskEmployeeListRelationFilter } from "../taskEmployee/TaskEmployeeListRelationFilter";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { TimeLogListRelationFilter } from "../timeLog/TimeLogListRelationFilter";
import { TimeOffPolicyEmployeeListRelationFilter } from "../timeOffPolicyEmployee/TimeOffPolicyEmployeeListRelationFilter";
import { TimeOffRequestEmployeeListRelationFilter } from "../timeOffRequestEmployee/TimeOffRequestEmployeeListRelationFilter";
import { TimesheetListRelationFilter } from "../timesheet/TimesheetListRelationFilter";
import { TimeSlotListRelationFilter } from "../timeSlot/TimeSlotListRelationFilter";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";

export type EmployeeWhereInput = {
  employeeUpworkJobSearchCriterion?: EmployeeUpworkJobSearchCriterionListRelationFilter;
  endWork?: DateTimeNullableFilter;
  equipmentSharesEmployees?: EquipmentSharesEmployeeListRelationFilter;
  eventType?: EventTypeListRelationFilter;
  expense?: ExpenseListRelationFilter;
  facebookUrl?: StringNullableFilter;
  githubUrl?: StringNullableFilter;
  gitlabUrl?: StringNullableFilter;
  goalGoalLeadIdToemployee?: GoalListRelationFilter;
  goalGoalOwnerEmployeeIdToemployee?: GoalListRelationFilter;
  goalKpi?: GoalKpiListRelationFilter;
  goalKpiTemplate?: GoalKpiTemplateListRelationFilter;
  id?: StringFilter;
  income?: IncomeListRelationFilter;
  instagramUrl?: StringNullableFilter;
  invoiceItem?: InvoiceItemListRelationFilter;
  isActive?: BooleanNullableFilter;
  isAway?: BooleanNullableFilter;
  isJobSearchActive?: BooleanNullableFilter;
  isOnline?: BooleanNullableFilter;
  isTrackingEnabled?: BooleanNullableFilter;
  isTrackingTime?: BooleanNullableFilter;
  isVerified?: BooleanNullableFilter;
  isVetted?: BooleanNullableFilter;
  jobSuccess?: DecimalNullableFilter;
  keyResultKeyResultLeadIdToemployee?: KeyResultListRelationFilter;
  keyResultKeyResultOwnerIdToemployee?: KeyResultListRelationFilter;
  knowledgeBaseAuthor?: KnowledgeBaseAuthorListRelationFilter;
  acceptDate?: DateTimeNullableFilter;
  activity?: ActivityListRelationFilter;
  allowScreenshotCapture?: BooleanFilter;
  anonymousBonus?: BooleanNullableFilter;
  appointmentEmployee?: AppointmentEmployeeListRelationFilter;
  availabilitySlot?: AvailabilitySlotListRelationFilter;
  averageBonus?: DecimalNullableFilter;
  averageExpenses?: DecimalNullableFilter;
  averageIncome?: DecimalNullableFilter;
  billRateCurrency?: StringNullableFilter;
  billRateValue?: IntNullableFilter;
  candidate?: CandidateWhereUniqueInput;
  candidateInterviewer?: CandidateInterviewerListRelationFilter;
  contact?: ContactWhereUniqueInput;
  createdAt?: DateTimeFilter;
  deletedAt?: DateTimeNullableFilter;
  description?: StringNullableFilter;
  employeeAppointment?: EmployeeAppointmentListRelationFilter;
  employeeAward?: EmployeeAwardListRelationFilter;
  employeeJobPreset?: EmployeeJobPresetListRelationFilter;
  employeeLevel?: StringNullableFilter;
  employeePhone?: EmployeePhoneListRelationFilter;
  employeeProposalTemplate?: EmployeeProposalTemplateListRelationFilter;
  employeeRecurringExpense?: EmployeeRecurringExpenseListRelationFilter;
  employeeSetting?: EmployeeSettingListRelationFilter;
  employeeTasksTask?: EmployeeTasksTaskListRelationFilter;
  linkedInId?: StringNullableFilter;
  linkedInUrl?: StringNullableFilter;
  minimumBillingRate?: IntNullableFilter;
  offerDate?: DateTimeNullableFilter;
  organization?: OrganizationWhereUniqueInput;
  organizationContactEmployee?: OrganizationContactEmployeeListRelationFilter;
  organizationDepartmentEmployee?: OrganizationDepartmentEmployeeListRelationFilter;
  organizationEmploymentTypeEmployee?: OrganizationEmploymentTypeEmployeeListRelationFilter;
  organizationPosition?: OrganizationPositionWhereUniqueInput;
  organizationProjectEmployee?: OrganizationProjectEmployeeListRelationFilter;
  organizationTeamEmployee?: OrganizationTeamEmployeeListRelationFilter;
  payment?: PaymentListRelationFilter;
  payPeriod?: StringNullableFilter;
  profileLink?: StringNullableFilter;
  proposal?: ProposalListRelationFilter;
  rejectDate?: DateTimeNullableFilter;
  requestApprovalEmployee?: RequestApprovalEmployeeListRelationFilter;
  reWeeklyLimit?: IntNullableFilter;
  shortDescription?: StringNullableFilter;
  showAnonymousBonus?: BooleanNullableFilter;
  showAverageBonus?: BooleanNullableFilter;
  showAverageExpenses?: BooleanNullableFilter;
  showAverageIncome?: BooleanNullableFilter;
  showBillrate?: BooleanNullableFilter;
  showPayperiod?: BooleanNullableFilter;
  showStartWorkOn?: BooleanNullableFilter;
  skillEmployee?: SkillEmployeeListRelationFilter;
  stackoverflowUrl?: StringNullableFilter;
  startedWorkOn?: DateTimeNullableFilter;
  tagEmployee?: TagEmployeeListRelationFilter;
  taskEmployee?: TaskEmployeeListRelationFilter;
  tenant?: TenantWhereUniqueInput;
  timeLog?: TimeLogListRelationFilter;
  timeOffPolicyEmployee?: TimeOffPolicyEmployeeListRelationFilter;
  timeOffRequestEmployee?: TimeOffRequestEmployeeListRelationFilter;
  timesheet?: TimesheetListRelationFilter;
  timeSlot?: TimeSlotListRelationFilter;
  totalJobs?: DecimalNullableFilter;
  totalWorkHours?: DecimalNullableFilter;
  twitterUrl?: StringNullableFilter;
  updatedAt?: DateTimeFilter;
  upworkId?: StringNullableFilter;
  upworkUrl?: StringNullableFilter;
  user?: UserWhereUniqueInput;
  valueDate?: DateTimeNullableFilter;
};
