/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateWarehouseArgs } from "./CreateWarehouseArgs";
import { UpdateWarehouseArgs } from "./UpdateWarehouseArgs";
import { DeleteWarehouseArgs } from "./DeleteWarehouseArgs";
import { WarehouseCountArgs } from "./WarehouseCountArgs";
import { WarehouseFindManyArgs } from "./WarehouseFindManyArgs";
import { WarehouseFindUniqueArgs } from "./WarehouseFindUniqueArgs";
import { Warehouse } from "./Warehouse";
import { TagWarehouseFindManyArgs } from "../../tagWarehouse/base/TagWarehouseFindManyArgs";
import { TagWarehouse } from "../../tagWarehouse/base/TagWarehouse";
import { WarehouseMerchantFindManyArgs } from "../../warehouseMerchant/base/WarehouseMerchantFindManyArgs";
import { WarehouseMerchant } from "../../warehouseMerchant/base/WarehouseMerchant";
import { WarehouseProductFindManyArgs } from "../../warehouseProduct/base/WarehouseProductFindManyArgs";
import { WarehouseProduct } from "../../warehouseProduct/base/WarehouseProduct";
import { Contact } from "../../contact/base/Contact";
import { Tenant } from "../../tenant/base/Tenant";
import { ImageAsset } from "../../imageAsset/base/ImageAsset";
import { Organization } from "../../organization/base/Organization";
import { WarehouseService } from "../warehouse.service";
@graphql.Resolver(() => Warehouse)
export class WarehouseResolverBase {
  constructor(protected readonly service: WarehouseService) {}

  async _warehousesMeta(
    @graphql.Args() args: WarehouseCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Warehouse])
  async warehouses(
    @graphql.Args() args: WarehouseFindManyArgs
  ): Promise<Warehouse[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => Warehouse, { nullable: true })
  async warehouse(
    @graphql.Args() args: WarehouseFindUniqueArgs
  ): Promise<Warehouse | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Warehouse)
  async createWarehouse(
    @graphql.Args() args: CreateWarehouseArgs
  ): Promise<Warehouse> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        contact: args.data.contact
          ? {
              connect: args.data.contact,
            }
          : undefined,

        tenant: args.data.tenant
          ? {
              connect: args.data.tenant,
            }
          : undefined,

        imageAsset: args.data.imageAsset
          ? {
              connect: args.data.imageAsset,
            }
          : undefined,

        organization: args.data.organization
          ? {
              connect: args.data.organization,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Warehouse)
  async updateWarehouse(
    @graphql.Args() args: UpdateWarehouseArgs
  ): Promise<Warehouse | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          contact: args.data.contact
            ? {
                connect: args.data.contact,
              }
            : undefined,

          tenant: args.data.tenant
            ? {
                connect: args.data.tenant,
              }
            : undefined,

          imageAsset: args.data.imageAsset
            ? {
                connect: args.data.imageAsset,
              }
            : undefined,

          organization: args.data.organization
            ? {
                connect: args.data.organization,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Warehouse)
  async deleteWarehouse(
    @graphql.Args() args: DeleteWarehouseArgs
  ): Promise<Warehouse | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [TagWarehouse], { name: "tagWarehouse" })
  async resolveFieldTagWarehouse(
    @graphql.Parent() parent: Warehouse,
    @graphql.Args() args: TagWarehouseFindManyArgs
  ): Promise<TagWarehouse[]> {
    const results = await this.service.findTagWarehouse(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [WarehouseMerchant], {
    name: "warehouseMerchant",
  })
  async resolveFieldWarehouseMerchant(
    @graphql.Parent() parent: Warehouse,
    @graphql.Args() args: WarehouseMerchantFindManyArgs
  ): Promise<WarehouseMerchant[]> {
    const results = await this.service.findWarehouseMerchant(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [WarehouseProduct], { name: "warehouseProduct" })
  async resolveFieldWarehouseProduct(
    @graphql.Parent() parent: Warehouse,
    @graphql.Args() args: WarehouseProductFindManyArgs
  ): Promise<WarehouseProduct[]> {
    const results = await this.service.findWarehouseProduct(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Contact, {
    nullable: true,
    name: "contact",
  })
  async resolveFieldContact(
    @graphql.Parent() parent: Warehouse
  ): Promise<Contact | null> {
    const result = await this.service.getContact(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Tenant, {
    nullable: true,
    name: "tenant",
  })
  async resolveFieldTenant(
    @graphql.Parent() parent: Warehouse
  ): Promise<Tenant | null> {
    const result = await this.service.getTenant(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => ImageAsset, {
    nullable: true,
    name: "imageAsset",
  })
  async resolveFieldImageAsset(
    @graphql.Parent() parent: Warehouse
  ): Promise<ImageAsset | null> {
    const result = await this.service.getImageAsset(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Organization, {
    nullable: true,
    name: "organization",
  })
  async resolveFieldOrganization(
    @graphql.Parent() parent: Warehouse
  ): Promise<Organization | null> {
    const result = await this.service.getOrganization(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
