import { OrganizationSprintWhereUniqueInput } from "../organizationSprint/OrganizationSprintWhereUniqueInput";
import { OrganizationProjectWhereUniqueInput } from "../organizationProject/OrganizationProjectWhereUniqueInput";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { TaskWhereUniqueInput } from "./TaskWhereUniqueInput";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { ActivityCreateNestedManyWithoutTasksInput } from "./ActivityCreateNestedManyWithoutTasksInput";
import { EmployeeTasksTaskCreateNestedManyWithoutTasksInput } from "./EmployeeTasksTaskCreateNestedManyWithoutTasksInput";
import { InvoiceItemCreateNestedManyWithoutTasksInput } from "./InvoiceItemCreateNestedManyWithoutTasksInput";
import { KeyResultCreateNestedManyWithoutTasksInput } from "./KeyResultCreateNestedManyWithoutTasksInput";
import { OrganizationTeamTasksTaskCreateNestedManyWithoutTasksInput } from "./OrganizationTeamTasksTaskCreateNestedManyWithoutTasksInput";
import { TagTaskCreateNestedManyWithoutTasksInput } from "./TagTaskCreateNestedManyWithoutTasksInput";
import { TaskCreateNestedManyWithoutTasksInput } from "./TaskCreateNestedManyWithoutTasksInput";
import { TaskEmployeeCreateNestedManyWithoutTasksInput } from "./TaskEmployeeCreateNestedManyWithoutTasksInput";
import { TaskLinkedIssueCreateNestedManyWithoutTasksInput } from "./TaskLinkedIssueCreateNestedManyWithoutTasksInput";
import { TaskTeamCreateNestedManyWithoutTasksInput } from "./TaskTeamCreateNestedManyWithoutTasksInput";
import { TimeLogCreateNestedManyWithoutTasksInput } from "./TimeLogCreateNestedManyWithoutTasksInput";

export type TaskCreateInput = {
  title: string;
  description?: string | null;
  status?: string | null;
  estimate?: number | null;
  dueDate?: Date | null;
  numberField?: number | null;
  prefix?: string | null;
  priority?: string | null;
  size?: string | null;
  publicField?: boolean | null;
  startDate?: Date | null;
  resolvedAt?: Date | null;
  version?: string | null;
  issueType?: string | null;
  organizationSprint?: OrganizationSprintWhereUniqueInput | null;
  organizationProject?: OrganizationProjectWhereUniqueInput | null;
  organization?: OrganizationWhereUniqueInput | null;
  task?: TaskWhereUniqueInput | null;
  user?: UserWhereUniqueInput | null;
  tenant?: TenantWhereUniqueInput | null;
  activity?: ActivityCreateNestedManyWithoutTasksInput;
  employeeTasksTask?: EmployeeTasksTaskCreateNestedManyWithoutTasksInput;
  invoiceItem?: InvoiceItemCreateNestedManyWithoutTasksInput;
  keyResult?: KeyResultCreateNestedManyWithoutTasksInput;
  organizationTeamTasksTask?: OrganizationTeamTasksTaskCreateNestedManyWithoutTasksInput;
  tagTask?: TagTaskCreateNestedManyWithoutTasksInput;
  otherTask?: TaskCreateNestedManyWithoutTasksInput;
  taskEmployee?: TaskEmployeeCreateNestedManyWithoutTasksInput;
  taskLinkedIssuesTaskLinkedIssuesTaskToIdTotask?: TaskLinkedIssueCreateNestedManyWithoutTasksInput;
  taskLinkedIssuesTaskLinkedIssuesTaskFromIdTotask?: TaskLinkedIssueCreateNestedManyWithoutTasksInput;
  taskTeam?: TaskTeamCreateNestedManyWithoutTasksInput;
  timeLog?: TimeLogCreateNestedManyWithoutTasksInput;
};
