import { StringFilter } from "../../util/StringFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { OrganizationSprintWhereUniqueInput } from "../organizationSprint/OrganizationSprintWhereUniqueInput";
import { OrganizationProjectWhereUniqueInput } from "../organizationProject/OrganizationProjectWhereUniqueInput";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { TaskWhereUniqueInput } from "./TaskWhereUniqueInput";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { ActivityListRelationFilter } from "../activity/ActivityListRelationFilter";
import { EmployeeTasksTaskListRelationFilter } from "../employeeTasksTask/EmployeeTasksTaskListRelationFilter";
import { InvoiceItemListRelationFilter } from "../invoiceItem/InvoiceItemListRelationFilter";
import { KeyResultListRelationFilter } from "../keyResult/KeyResultListRelationFilter";
import { OrganizationTeamTasksTaskListRelationFilter } from "../organizationTeamTasksTask/OrganizationTeamTasksTaskListRelationFilter";
import { TagTaskListRelationFilter } from "../tagTask/TagTaskListRelationFilter";
import { TaskListRelationFilter } from "./TaskListRelationFilter";
import { TaskEmployeeListRelationFilter } from "../taskEmployee/TaskEmployeeListRelationFilter";
import { TaskLinkedIssueListRelationFilter } from "../taskLinkedIssue/TaskLinkedIssueListRelationFilter";
import { TaskTeamListRelationFilter } from "../taskTeam/TaskTeamListRelationFilter";
import { TimeLogListRelationFilter } from "../timeLog/TimeLogListRelationFilter";

export type TaskWhereInput = {
  id?: StringFilter;
  createdAt?: DateTimeFilter;
  updatedAt?: DateTimeFilter;
  title?: StringFilter;
  description?: StringNullableFilter;
  status?: StringNullableFilter;
  estimate?: IntNullableFilter;
  dueDate?: DateTimeNullableFilter;
  numberField?: IntNullableFilter;
  prefix?: StringNullableFilter;
  priority?: StringNullableFilter;
  size?: StringNullableFilter;
  publicField?: BooleanNullableFilter;
  startDate?: DateTimeNullableFilter;
  resolvedAt?: DateTimeNullableFilter;
  version?: StringNullableFilter;
  issueType?: StringNullableFilter;
  organizationSprint?: OrganizationSprintWhereUniqueInput;
  organizationProject?: OrganizationProjectWhereUniqueInput;
  organization?: OrganizationWhereUniqueInput;
  task?: TaskWhereUniqueInput;
  user?: UserWhereUniqueInput;
  tenant?: TenantWhereUniqueInput;
  activity?: ActivityListRelationFilter;
  employeeTasksTask?: EmployeeTasksTaskListRelationFilter;
  invoiceItem?: InvoiceItemListRelationFilter;
  keyResult?: KeyResultListRelationFilter;
  organizationTeamTasksTask?: OrganizationTeamTasksTaskListRelationFilter;
  tagTask?: TagTaskListRelationFilter;
  otherTask?: TaskListRelationFilter;
  taskEmployee?: TaskEmployeeListRelationFilter;
  taskLinkedIssuesTaskLinkedIssuesTaskToIdTotask?: TaskLinkedIssueListRelationFilter;
  taskLinkedIssuesTaskLinkedIssuesTaskFromIdTotask?: TaskLinkedIssueListRelationFilter;
  taskTeam?: TaskTeamListRelationFilter;
  timeLog?: TimeLogListRelationFilter;
};
