import { OrganizationSprintWhereUniqueInput } from "../organizationSprint/OrganizationSprintWhereUniqueInput";
import { OrganizationProjectWhereUniqueInput } from "../organizationProject/OrganizationProjectWhereUniqueInput";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { TaskWhereUniqueInput } from "./TaskWhereUniqueInput";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { ActivityUpdateManyWithoutTasksInput } from "./ActivityUpdateManyWithoutTasksInput";
import { EmployeeTasksTaskUpdateManyWithoutTasksInput } from "./EmployeeTasksTaskUpdateManyWithoutTasksInput";
import { InvoiceItemUpdateManyWithoutTasksInput } from "./InvoiceItemUpdateManyWithoutTasksInput";
import { KeyResultUpdateManyWithoutTasksInput } from "./KeyResultUpdateManyWithoutTasksInput";
import { OrganizationTeamTasksTaskUpdateManyWithoutTasksInput } from "./OrganizationTeamTasksTaskUpdateManyWithoutTasksInput";
import { TagTaskUpdateManyWithoutTasksInput } from "./TagTaskUpdateManyWithoutTasksInput";
import { TaskUpdateManyWithoutTasksInput } from "./TaskUpdateManyWithoutTasksInput";
import { TaskEmployeeUpdateManyWithoutTasksInput } from "./TaskEmployeeUpdateManyWithoutTasksInput";
import { TaskLinkedIssueUpdateManyWithoutTasksInput } from "./TaskLinkedIssueUpdateManyWithoutTasksInput";
import { TaskTeamUpdateManyWithoutTasksInput } from "./TaskTeamUpdateManyWithoutTasksInput";
import { TimeLogUpdateManyWithoutTasksInput } from "./TimeLogUpdateManyWithoutTasksInput";

export type TaskUpdateInput = {
  title?: string;
  description?: string | null;
  status?: string | null;
  estimate?: number | null;
  dueDate?: Date | null;
  numberField?: number | null;
  prefix?: string | null;
  priority?: string | null;
  size?: string | null;
  publicField?: boolean | null;
  startDate?: Date | null;
  resolvedAt?: Date | null;
  version?: string | null;
  issueType?: string | null;
  organizationSprint?: OrganizationSprintWhereUniqueInput | null;
  organizationProject?: OrganizationProjectWhereUniqueInput | null;
  organization?: OrganizationWhereUniqueInput | null;
  task?: TaskWhereUniqueInput | null;
  user?: UserWhereUniqueInput | null;
  tenant?: TenantWhereUniqueInput | null;
  activity?: ActivityUpdateManyWithoutTasksInput;
  employeeTasksTask?: EmployeeTasksTaskUpdateManyWithoutTasksInput;
  invoiceItem?: InvoiceItemUpdateManyWithoutTasksInput;
  keyResult?: KeyResultUpdateManyWithoutTasksInput;
  organizationTeamTasksTask?: OrganizationTeamTasksTaskUpdateManyWithoutTasksInput;
  tagTask?: TagTaskUpdateManyWithoutTasksInput;
  otherTask?: TaskUpdateManyWithoutTasksInput;
  taskEmployee?: TaskEmployeeUpdateManyWithoutTasksInput;
  taskLinkedIssuesTaskLinkedIssuesTaskToIdTotask?: TaskLinkedIssueUpdateManyWithoutTasksInput;
  taskLinkedIssuesTaskLinkedIssuesTaskFromIdTotask?: TaskLinkedIssueUpdateManyWithoutTasksInput;
  taskTeam?: TaskTeamUpdateManyWithoutTasksInput;
  timeLog?: TimeLogUpdateManyWithoutTasksInput;
};
