import { AccountingTemplateCreateNestedManyWithoutTenantsInput } from "./AccountingTemplateCreateNestedManyWithoutTenantsInput";
import { ActivityCreateNestedManyWithoutTenantsInput } from "./ActivityCreateNestedManyWithoutTenantsInput";
import { AppointmentEmployeeCreateNestedManyWithoutTenantsInput } from "./AppointmentEmployeeCreateNestedManyWithoutTenantsInput";
import { ApprovalPolicyCreateNestedManyWithoutTenantsInput } from "./ApprovalPolicyCreateNestedManyWithoutTenantsInput";
import { AvailabilitySlotCreateNestedManyWithoutTenantsInput } from "./AvailabilitySlotCreateNestedManyWithoutTenantsInput";
import { CandidateCreateNestedManyWithoutTenantsInput } from "./CandidateCreateNestedManyWithoutTenantsInput";
import { CandidateCriterionRatingCreateNestedManyWithoutTenantsInput } from "./CandidateCriterionRatingCreateNestedManyWithoutTenantsInput";
import { CandidateDocumentCreateNestedManyWithoutTenantsInput } from "./CandidateDocumentCreateNestedManyWithoutTenantsInput";
import { CandidateEducationCreateNestedManyWithoutTenantsInput } from "./CandidateEducationCreateNestedManyWithoutTenantsInput";
import { CandidateExperienceCreateNestedManyWithoutTenantsInput } from "./CandidateExperienceCreateNestedManyWithoutTenantsInput";
import { CandidateFeedbackCreateNestedManyWithoutTenantsInput } from "./CandidateFeedbackCreateNestedManyWithoutTenantsInput";
import { CandidateInterviewCreateNestedManyWithoutTenantsInput } from "./CandidateInterviewCreateNestedManyWithoutTenantsInput";
import { CandidateInterviewerCreateNestedManyWithoutTenantsInput } from "./CandidateInterviewerCreateNestedManyWithoutTenantsInput";
import { CandidatePersonalQualityCreateNestedManyWithoutTenantsInput } from "./CandidatePersonalQualityCreateNestedManyWithoutTenantsInput";
import { CandidateSkillCreateNestedManyWithoutTenantsInput } from "./CandidateSkillCreateNestedManyWithoutTenantsInput";
import { CandidateSourceCreateNestedManyWithoutTenantsInput } from "./CandidateSourceCreateNestedManyWithoutTenantsInput";
import { CandidateTechnologyCreateNestedManyWithoutTenantsInput } from "./CandidateTechnologyCreateNestedManyWithoutTenantsInput";
import { ChangelogCreateNestedManyWithoutTenantsInput } from "./ChangelogCreateNestedManyWithoutTenantsInput";
import { ContactCreateNestedManyWithoutTenantsInput } from "./ContactCreateNestedManyWithoutTenantsInput";
import { CustomSmtpCreateNestedManyWithoutTenantsInput } from "./CustomSmtpCreateNestedManyWithoutTenantsInput";
import { DealCreateNestedManyWithoutTenantsInput } from "./DealCreateNestedManyWithoutTenantsInput";
import { EmailResetCreateNestedManyWithoutTenantsInput } from "./EmailResetCreateNestedManyWithoutTenantsInput";
import { EmailSentCreateNestedManyWithoutTenantsInput } from "./EmailSentCreateNestedManyWithoutTenantsInput";
import { EmailTemplateCreateNestedManyWithoutTenantsInput } from "./EmailTemplateCreateNestedManyWithoutTenantsInput";
import { EmployeeCreateNestedManyWithoutTenantsInput } from "./EmployeeCreateNestedManyWithoutTenantsInput";
import { EmployeeAppointmentCreateNestedManyWithoutTenantsInput } from "./EmployeeAppointmentCreateNestedManyWithoutTenantsInput";
import { EmployeeAwardCreateNestedManyWithoutTenantsInput } from "./EmployeeAwardCreateNestedManyWithoutTenantsInput";
import { EmployeeLevelCreateNestedManyWithoutTenantsInput } from "./EmployeeLevelCreateNestedManyWithoutTenantsInput";
import { EmployeePhoneCreateNestedManyWithoutTenantsInput } from "./EmployeePhoneCreateNestedManyWithoutTenantsInput";
import { EmployeeProposalTemplateCreateNestedManyWithoutTenantsInput } from "./EmployeeProposalTemplateCreateNestedManyWithoutTenantsInput";
import { EmployeeRecurringExpenseCreateNestedManyWithoutTenantsInput } from "./EmployeeRecurringExpenseCreateNestedManyWithoutTenantsInput";
import { EmployeeSettingCreateNestedManyWithoutTenantsInput } from "./EmployeeSettingCreateNestedManyWithoutTenantsInput";
import { EmployeeUpworkJobSearchCriterionCreateNestedManyWithoutTenantsInput } from "./EmployeeUpworkJobSearchCriterionCreateNestedManyWithoutTenantsInput";
import { EquipmentCreateNestedManyWithoutTenantsInput } from "./EquipmentCreateNestedManyWithoutTenantsInput";
import { EquipmentSharingCreateNestedManyWithoutTenantsInput } from "./EquipmentSharingCreateNestedManyWithoutTenantsInput";
import { EquipmentSharingPolicyCreateNestedManyWithoutTenantsInput } from "./EquipmentSharingPolicyCreateNestedManyWithoutTenantsInput";
import { EstimateEmailCreateNestedManyWithoutTenantsInput } from "./EstimateEmailCreateNestedManyWithoutTenantsInput";
import { EventTypeCreateNestedManyWithoutTenantsInput } from "./EventTypeCreateNestedManyWithoutTenantsInput";
import { ExpenseCreateNestedManyWithoutTenantsInput } from "./ExpenseCreateNestedManyWithoutTenantsInput";
import { ExpenseCategoryCreateNestedManyWithoutTenantsInput } from "./ExpenseCategoryCreateNestedManyWithoutTenantsInput";
import { FeatureOrganizationCreateNestedManyWithoutTenantsInput } from "./FeatureOrganizationCreateNestedManyWithoutTenantsInput";
import { GoalCreateNestedManyWithoutTenantsInput } from "./GoalCreateNestedManyWithoutTenantsInput";
import { GoalGeneralSettingCreateNestedManyWithoutTenantsInput } from "./GoalGeneralSettingCreateNestedManyWithoutTenantsInput";
import { GoalKpiCreateNestedManyWithoutTenantsInput } from "./GoalKpiCreateNestedManyWithoutTenantsInput";
import { GoalKpiTemplateCreateNestedManyWithoutTenantsInput } from "./GoalKpiTemplateCreateNestedManyWithoutTenantsInput";
import { GoalTemplateCreateNestedManyWithoutTenantsInput } from "./GoalTemplateCreateNestedManyWithoutTenantsInput";
import { GoalTimeFrameCreateNestedManyWithoutTenantsInput } from "./GoalTimeFrameCreateNestedManyWithoutTenantsInput";
import { ImageAssetCreateNestedManyWithoutTenantsInput } from "./ImageAssetCreateNestedManyWithoutTenantsInput";
import { ImageAssetWhereUniqueInput } from "../imageAsset/ImageAssetWhereUniqueInput";
import { ImportHistoryCreateNestedManyWithoutTenantsInput } from "./ImportHistoryCreateNestedManyWithoutTenantsInput";
import { ImportRecordCreateNestedManyWithoutTenantsInput } from "./ImportRecordCreateNestedManyWithoutTenantsInput";
import { IncomeCreateNestedManyWithoutTenantsInput } from "./IncomeCreateNestedManyWithoutTenantsInput";
import { IntegrationEntitySettingCreateNestedManyWithoutTenantsInput } from "./IntegrationEntitySettingCreateNestedManyWithoutTenantsInput";
import { IntegrationEntitySettingTiedCreateNestedManyWithoutTenantsInput } from "./IntegrationEntitySettingTiedCreateNestedManyWithoutTenantsInput";
import { IntegrationMapCreateNestedManyWithoutTenantsInput } from "./IntegrationMapCreateNestedManyWithoutTenantsInput";
import { IntegrationSettingCreateNestedManyWithoutTenantsInput } from "./IntegrationSettingCreateNestedManyWithoutTenantsInput";
import { IntegrationTenantCreateNestedManyWithoutTenantsInput } from "./IntegrationTenantCreateNestedManyWithoutTenantsInput";
import { InviteCreateNestedManyWithoutTenantsInput } from "./InviteCreateNestedManyWithoutTenantsInput";
import { InvoiceCreateNestedManyWithoutTenantsInput } from "./InvoiceCreateNestedManyWithoutTenantsInput";
import { InvoiceEstimateHistoryCreateNestedManyWithoutTenantsInput } from "./InvoiceEstimateHistoryCreateNestedManyWithoutTenantsInput";
import { InvoiceItemCreateNestedManyWithoutTenantsInput } from "./InvoiceItemCreateNestedManyWithoutTenantsInput";
import { IssueTypeCreateNestedManyWithoutTenantsInput } from "./IssueTypeCreateNestedManyWithoutTenantsInput";
import { JobPresetCreateNestedManyWithoutTenantsInput } from "./JobPresetCreateNestedManyWithoutTenantsInput";
import { JobPresetUpworkJobSearchCriterionCreateNestedManyWithoutTenantsInput } from "./JobPresetUpworkJobSearchCriterionCreateNestedManyWithoutTenantsInput";
import { JobSearchCategoryCreateNestedManyWithoutTenantsInput } from "./JobSearchCategoryCreateNestedManyWithoutTenantsInput";
import { JobSearchOccupationCreateNestedManyWithoutTenantsInput } from "./JobSearchOccupationCreateNestedManyWithoutTenantsInput";
import { KeyResultCreateNestedManyWithoutTenantsInput } from "./KeyResultCreateNestedManyWithoutTenantsInput";
import { KeyResultTemplateCreateNestedManyWithoutTenantsInput } from "./KeyResultTemplateCreateNestedManyWithoutTenantsInput";
import { KeyResultUpdateCreateNestedManyWithoutTenantsInput } from "./KeyResultUpdateCreateNestedManyWithoutTenantsInput";
import { KnowledgeBaseCreateNestedManyWithoutTenantsInput } from "./KnowledgeBaseCreateNestedManyWithoutTenantsInput";
import { KnowledgeBaseArticleCreateNestedManyWithoutTenantsInput } from "./KnowledgeBaseArticleCreateNestedManyWithoutTenantsInput";
import { KnowledgeBaseAuthorCreateNestedManyWithoutTenantsInput } from "./KnowledgeBaseAuthorCreateNestedManyWithoutTenantsInput";
import { MerchantCreateNestedManyWithoutTenantsInput } from "./MerchantCreateNestedManyWithoutTenantsInput";
import { OrganizationCreateNestedManyWithoutTenantsInput } from "./OrganizationCreateNestedManyWithoutTenantsInput";
import { OrganizationAwardCreateNestedManyWithoutTenantsInput } from "./OrganizationAwardCreateNestedManyWithoutTenantsInput";
import { OrganizationContactCreateNestedManyWithoutTenantsInput } from "./OrganizationContactCreateNestedManyWithoutTenantsInput";
import { OrganizationDepartmentCreateNestedManyWithoutTenantsInput } from "./OrganizationDepartmentCreateNestedManyWithoutTenantsInput";
import { OrganizationDocumentCreateNestedManyWithoutTenantsInput } from "./OrganizationDocumentCreateNestedManyWithoutTenantsInput";
import { OrganizationEmploymentTypeCreateNestedManyWithoutTenantsInput } from "./OrganizationEmploymentTypeCreateNestedManyWithoutTenantsInput";
import { OrganizationLanguageCreateNestedManyWithoutTenantsInput } from "./OrganizationLanguageCreateNestedManyWithoutTenantsInput";
import { OrganizationPositionCreateNestedManyWithoutTenantsInput } from "./OrganizationPositionCreateNestedManyWithoutTenantsInput";
import { OrganizationProjectCreateNestedManyWithoutTenantsInput } from "./OrganizationProjectCreateNestedManyWithoutTenantsInput";
import { OrganizationRecurringExpenseCreateNestedManyWithoutTenantsInput } from "./OrganizationRecurringExpenseCreateNestedManyWithoutTenantsInput";
import { OrganizationSprintCreateNestedManyWithoutTenantsInput } from "./OrganizationSprintCreateNestedManyWithoutTenantsInput";
import { OrganizationTaskSettingCreateNestedManyWithoutTenantsInput } from "./OrganizationTaskSettingCreateNestedManyWithoutTenantsInput";
import { OrganizationTeamCreateNestedManyWithoutTenantsInput } from "./OrganizationTeamCreateNestedManyWithoutTenantsInput";
import { OrganizationTeamEmployeeCreateNestedManyWithoutTenantsInput } from "./OrganizationTeamEmployeeCreateNestedManyWithoutTenantsInput";
import { OrganizationTeamJoinRequestCreateNestedManyWithoutTenantsInput } from "./OrganizationTeamJoinRequestCreateNestedManyWithoutTenantsInput";
import { OrganizationVendorCreateNestedManyWithoutTenantsInput } from "./OrganizationVendorCreateNestedManyWithoutTenantsInput";
import { PaymentCreateNestedManyWithoutTenantsInput } from "./PaymentCreateNestedManyWithoutTenantsInput";
import { PipelineCreateNestedManyWithoutTenantsInput } from "./PipelineCreateNestedManyWithoutTenantsInput";
import { PipelineStageCreateNestedManyWithoutTenantsInput } from "./PipelineStageCreateNestedManyWithoutTenantsInput";
import { ProductCreateNestedManyWithoutTenantsInput } from "./ProductCreateNestedManyWithoutTenantsInput";
import { ProductCategoryCreateNestedManyWithoutTenantsInput } from "./ProductCategoryCreateNestedManyWithoutTenantsInput";
import { ProductCategoryTranslationCreateNestedManyWithoutTenantsInput } from "./ProductCategoryTranslationCreateNestedManyWithoutTenantsInput";
import { ProductOptionCreateNestedManyWithoutTenantsInput } from "./ProductOptionCreateNestedManyWithoutTenantsInput";
import { ProductOptionGroupCreateNestedManyWithoutTenantsInput } from "./ProductOptionGroupCreateNestedManyWithoutTenantsInput";
import { ProductOptionGroupTranslationCreateNestedManyWithoutTenantsInput } from "./ProductOptionGroupTranslationCreateNestedManyWithoutTenantsInput";
import { ProductOptionTranslationCreateNestedManyWithoutTenantsInput } from "./ProductOptionTranslationCreateNestedManyWithoutTenantsInput";
import { ProductTranslationCreateNestedManyWithoutTenantsInput } from "./ProductTranslationCreateNestedManyWithoutTenantsInput";
import { ProductTypeCreateNestedManyWithoutTenantsInput } from "./ProductTypeCreateNestedManyWithoutTenantsInput";
import { ProductTypeTranslationCreateNestedManyWithoutTenantsInput } from "./ProductTypeTranslationCreateNestedManyWithoutTenantsInput";
import { ProductVariantCreateNestedManyWithoutTenantsInput } from "./ProductVariantCreateNestedManyWithoutTenantsInput";
import { ProductVariantPriceCreateNestedManyWithoutTenantsInput } from "./ProductVariantPriceCreateNestedManyWithoutTenantsInput";
import { ProductVariantSettingCreateNestedManyWithoutTenantsInput } from "./ProductVariantSettingCreateNestedManyWithoutTenantsInput";
import { ProposalCreateNestedManyWithoutTenantsInput } from "./ProposalCreateNestedManyWithoutTenantsInput";
import { ReportOrganizationCreateNestedManyWithoutTenantsInput } from "./ReportOrganizationCreateNestedManyWithoutTenantsInput";
import { RequestApprovalCreateNestedManyWithoutTenantsInput } from "./RequestApprovalCreateNestedManyWithoutTenantsInput";
import { RequestApprovalEmployeeCreateNestedManyWithoutTenantsInput } from "./RequestApprovalEmployeeCreateNestedManyWithoutTenantsInput";
import { RequestApprovalTeamCreateNestedManyWithoutTenantsInput } from "./RequestApprovalTeamCreateNestedManyWithoutTenantsInput";
import { RoleCreateNestedManyWithoutTenantsInput } from "./RoleCreateNestedManyWithoutTenantsInput";
import { RolePermissionCreateNestedManyWithoutTenantsInput } from "./RolePermissionCreateNestedManyWithoutTenantsInput";
import { ScreenshotCreateNestedManyWithoutTenantsInput } from "./ScreenshotCreateNestedManyWithoutTenantsInput";
import { SkillCreateNestedManyWithoutTenantsInput } from "./SkillCreateNestedManyWithoutTenantsInput";
import { TagCreateNestedManyWithoutTenantsInput } from "./TagCreateNestedManyWithoutTenantsInput";
import { TaskCreateNestedManyWithoutTenantsInput } from "./TaskCreateNestedManyWithoutTenantsInput";
import { TaskLinkedIssueCreateNestedManyWithoutTenantsInput } from "./TaskLinkedIssueCreateNestedManyWithoutTenantsInput";
import { TaskPriorityCreateNestedManyWithoutTenantsInput } from "./TaskPriorityCreateNestedManyWithoutTenantsInput";
import { TaskRelatedIssueTypeCreateNestedManyWithoutTenantsInput } from "./TaskRelatedIssueTypeCreateNestedManyWithoutTenantsInput";
import { TaskSizeCreateNestedManyWithoutTenantsInput } from "./TaskSizeCreateNestedManyWithoutTenantsInput";
import { TaskStatusCreateNestedManyWithoutTenantsInput } from "./TaskStatusCreateNestedManyWithoutTenantsInput";
import { TaskVersionCreateNestedManyWithoutTenantsInput } from "./TaskVersionCreateNestedManyWithoutTenantsInput";
import { TenantSettingCreateNestedManyWithoutTenantsInput } from "./TenantSettingCreateNestedManyWithoutTenantsInput";
import { TimeLogCreateNestedManyWithoutTenantsInput } from "./TimeLogCreateNestedManyWithoutTenantsInput";
import { TimeOffPolicyCreateNestedManyWithoutTenantsInput } from "./TimeOffPolicyCreateNestedManyWithoutTenantsInput";
import { TimeOffRequestCreateNestedManyWithoutTenantsInput } from "./TimeOffRequestCreateNestedManyWithoutTenantsInput";
import { TimeSlotCreateNestedManyWithoutTenantsInput } from "./TimeSlotCreateNestedManyWithoutTenantsInput";
import { TimeSlotMinuteCreateNestedManyWithoutTenantsInput } from "./TimeSlotMinuteCreateNestedManyWithoutTenantsInput";
import { TimesheetCreateNestedManyWithoutTenantsInput } from "./TimesheetCreateNestedManyWithoutTenantsInput";
import { UserCreateNestedManyWithoutTenantsInput } from "./UserCreateNestedManyWithoutTenantsInput";
import { UserOrganizationCreateNestedManyWithoutTenantsInput } from "./UserOrganizationCreateNestedManyWithoutTenantsInput";
import { WarehouseCreateNestedManyWithoutTenantsInput } from "./WarehouseCreateNestedManyWithoutTenantsInput";
import { WarehouseProductCreateNestedManyWithoutTenantsInput } from "./WarehouseProductCreateNestedManyWithoutTenantsInput";
import { WarehouseProductVariantCreateNestedManyWithoutTenantsInput } from "./WarehouseProductVariantCreateNestedManyWithoutTenantsInput";

export type TenantCreateInput = {
  name: string;
  logo?: string | null;
  accountingTemplate?: AccountingTemplateCreateNestedManyWithoutTenantsInput;
  activity?: ActivityCreateNestedManyWithoutTenantsInput;
  appointmentEmployee?: AppointmentEmployeeCreateNestedManyWithoutTenantsInput;
  approvalPolicy?: ApprovalPolicyCreateNestedManyWithoutTenantsInput;
  availabilitySlot?: AvailabilitySlotCreateNestedManyWithoutTenantsInput;
  candidate?: CandidateCreateNestedManyWithoutTenantsInput;
  candidateCriterionRating?: CandidateCriterionRatingCreateNestedManyWithoutTenantsInput;
  candidateDocument?: CandidateDocumentCreateNestedManyWithoutTenantsInput;
  candidateEducation?: CandidateEducationCreateNestedManyWithoutTenantsInput;
  candidateExperience?: CandidateExperienceCreateNestedManyWithoutTenantsInput;
  candidateFeedback?: CandidateFeedbackCreateNestedManyWithoutTenantsInput;
  candidateInterview?: CandidateInterviewCreateNestedManyWithoutTenantsInput;
  candidateInterviewer?: CandidateInterviewerCreateNestedManyWithoutTenantsInput;
  candidatePersonalQuality?: CandidatePersonalQualityCreateNestedManyWithoutTenantsInput;
  candidateSkill?: CandidateSkillCreateNestedManyWithoutTenantsInput;
  candidateSource?: CandidateSourceCreateNestedManyWithoutTenantsInput;
  candidateTechnology?: CandidateTechnologyCreateNestedManyWithoutTenantsInput;
  changelog?: ChangelogCreateNestedManyWithoutTenantsInput;
  contact?: ContactCreateNestedManyWithoutTenantsInput;
  customSmtp?: CustomSmtpCreateNestedManyWithoutTenantsInput;
  deal?: DealCreateNestedManyWithoutTenantsInput;
  emailReset?: EmailResetCreateNestedManyWithoutTenantsInput;
  emailSent?: EmailSentCreateNestedManyWithoutTenantsInput;
  emailTemplate?: EmailTemplateCreateNestedManyWithoutTenantsInput;
  employee?: EmployeeCreateNestedManyWithoutTenantsInput;
  employeeAppointment?: EmployeeAppointmentCreateNestedManyWithoutTenantsInput;
  employeeAward?: EmployeeAwardCreateNestedManyWithoutTenantsInput;
  employeeLevel?: EmployeeLevelCreateNestedManyWithoutTenantsInput;
  employeePhone?: EmployeePhoneCreateNestedManyWithoutTenantsInput;
  employeeProposalTemplate?: EmployeeProposalTemplateCreateNestedManyWithoutTenantsInput;
  employeeRecurringExpense?: EmployeeRecurringExpenseCreateNestedManyWithoutTenantsInput;
  employeeSetting?: EmployeeSettingCreateNestedManyWithoutTenantsInput;
  employeeUpworkJobSearchCriterion?: EmployeeUpworkJobSearchCriterionCreateNestedManyWithoutTenantsInput;
  equipment?: EquipmentCreateNestedManyWithoutTenantsInput;
  equipmentSharing?: EquipmentSharingCreateNestedManyWithoutTenantsInput;
  equipmentSharingPolicy?: EquipmentSharingPolicyCreateNestedManyWithoutTenantsInput;
  estimateEmail?: EstimateEmailCreateNestedManyWithoutTenantsInput;
  eventType?: EventTypeCreateNestedManyWithoutTenantsInput;
  expense?: ExpenseCreateNestedManyWithoutTenantsInput;
  expenseCategory?: ExpenseCategoryCreateNestedManyWithoutTenantsInput;
  featureOrganization?: FeatureOrganizationCreateNestedManyWithoutTenantsInput;
  goal?: GoalCreateNestedManyWithoutTenantsInput;
  goalGeneralSetting?: GoalGeneralSettingCreateNestedManyWithoutTenantsInput;
  goalKpi?: GoalKpiCreateNestedManyWithoutTenantsInput;
  goalKpiTemplate?: GoalKpiTemplateCreateNestedManyWithoutTenantsInput;
  goalTemplate?: GoalTemplateCreateNestedManyWithoutTenantsInput;
  goalTimeFrame?: GoalTimeFrameCreateNestedManyWithoutTenantsInput;
  imageAssetImageAssetTenantIdTotenant?: ImageAssetCreateNestedManyWithoutTenantsInput;
  imageAssetTenantImageIdToimageAsset?: ImageAssetWhereUniqueInput | null;
  importHistory?: ImportHistoryCreateNestedManyWithoutTenantsInput;
  importRecord?: ImportRecordCreateNestedManyWithoutTenantsInput;
  income?: IncomeCreateNestedManyWithoutTenantsInput;
  integrationEntitySetting?: IntegrationEntitySettingCreateNestedManyWithoutTenantsInput;
  integrationEntitySettingTied?: IntegrationEntitySettingTiedCreateNestedManyWithoutTenantsInput;
  integrationMap?: IntegrationMapCreateNestedManyWithoutTenantsInput;
  integrationSetting?: IntegrationSettingCreateNestedManyWithoutTenantsInput;
  integrationTenant?: IntegrationTenantCreateNestedManyWithoutTenantsInput;
  invite?: InviteCreateNestedManyWithoutTenantsInput;
  invoice?: InvoiceCreateNestedManyWithoutTenantsInput;
  invoiceEstimateHistory?: InvoiceEstimateHistoryCreateNestedManyWithoutTenantsInput;
  invoiceItem?: InvoiceItemCreateNestedManyWithoutTenantsInput;
  issueType?: IssueTypeCreateNestedManyWithoutTenantsInput;
  jobPreset?: JobPresetCreateNestedManyWithoutTenantsInput;
  jobPresetUpworkJobSearchCriterion?: JobPresetUpworkJobSearchCriterionCreateNestedManyWithoutTenantsInput;
  jobSearchCategory?: JobSearchCategoryCreateNestedManyWithoutTenantsInput;
  jobSearchOccupation?: JobSearchOccupationCreateNestedManyWithoutTenantsInput;
  keyResult?: KeyResultCreateNestedManyWithoutTenantsInput;
  keyResultTemplate?: KeyResultTemplateCreateNestedManyWithoutTenantsInput;
  keyResultUpdate?: KeyResultUpdateCreateNestedManyWithoutTenantsInput;
  knowledgeBase?: KnowledgeBaseCreateNestedManyWithoutTenantsInput;
  knowledgeBaseArticle?: KnowledgeBaseArticleCreateNestedManyWithoutTenantsInput;
  knowledgeBaseAuthor?: KnowledgeBaseAuthorCreateNestedManyWithoutTenantsInput;
  merchant?: MerchantCreateNestedManyWithoutTenantsInput;
  organization?: OrganizationCreateNestedManyWithoutTenantsInput;
  organizationAward?: OrganizationAwardCreateNestedManyWithoutTenantsInput;
  organizationContact?: OrganizationContactCreateNestedManyWithoutTenantsInput;
  organizationDepartment?: OrganizationDepartmentCreateNestedManyWithoutTenantsInput;
  organizationDocument?: OrganizationDocumentCreateNestedManyWithoutTenantsInput;
  organizationEmploymentType?: OrganizationEmploymentTypeCreateNestedManyWithoutTenantsInput;
  organizationLanguage?: OrganizationLanguageCreateNestedManyWithoutTenantsInput;
  organizationPosition?: OrganizationPositionCreateNestedManyWithoutTenantsInput;
  organizationProject?: OrganizationProjectCreateNestedManyWithoutTenantsInput;
  organizationRecurringExpense?: OrganizationRecurringExpenseCreateNestedManyWithoutTenantsInput;
  organizationSprint?: OrganizationSprintCreateNestedManyWithoutTenantsInput;
  organizationTaskSetting?: OrganizationTaskSettingCreateNestedManyWithoutTenantsInput;
  organizationTeam?: OrganizationTeamCreateNestedManyWithoutTenantsInput;
  organizationTeamEmployee?: OrganizationTeamEmployeeCreateNestedManyWithoutTenantsInput;
  organizationTeamJoinRequest?: OrganizationTeamJoinRequestCreateNestedManyWithoutTenantsInput;
  organizationVendor?: OrganizationVendorCreateNestedManyWithoutTenantsInput;
  payment?: PaymentCreateNestedManyWithoutTenantsInput;
  pipeline?: PipelineCreateNestedManyWithoutTenantsInput;
  pipelineStage?: PipelineStageCreateNestedManyWithoutTenantsInput;
  product?: ProductCreateNestedManyWithoutTenantsInput;
  productCategory?: ProductCategoryCreateNestedManyWithoutTenantsInput;
  productCategoryTranslation?: ProductCategoryTranslationCreateNestedManyWithoutTenantsInput;
  productOption?: ProductOptionCreateNestedManyWithoutTenantsInput;
  productOptionGroup?: ProductOptionGroupCreateNestedManyWithoutTenantsInput;
  productOptionGroupTranslation?: ProductOptionGroupTranslationCreateNestedManyWithoutTenantsInput;
  productOptionTranslation?: ProductOptionTranslationCreateNestedManyWithoutTenantsInput;
  productTranslation?: ProductTranslationCreateNestedManyWithoutTenantsInput;
  productType?: ProductTypeCreateNestedManyWithoutTenantsInput;
  productTypeTranslation?: ProductTypeTranslationCreateNestedManyWithoutTenantsInput;
  productVariant?: ProductVariantCreateNestedManyWithoutTenantsInput;
  productVariantPrice?: ProductVariantPriceCreateNestedManyWithoutTenantsInput;
  productVariantSetting?: ProductVariantSettingCreateNestedManyWithoutTenantsInput;
  proposal?: ProposalCreateNestedManyWithoutTenantsInput;
  reportOrganization?: ReportOrganizationCreateNestedManyWithoutTenantsInput;
  requestApproval?: RequestApprovalCreateNestedManyWithoutTenantsInput;
  requestApprovalEmployee?: RequestApprovalEmployeeCreateNestedManyWithoutTenantsInput;
  requestApprovalTeam?: RequestApprovalTeamCreateNestedManyWithoutTenantsInput;
  role?: RoleCreateNestedManyWithoutTenantsInput;
  rolePermission?: RolePermissionCreateNestedManyWithoutTenantsInput;
  screenshot?: ScreenshotCreateNestedManyWithoutTenantsInput;
  skill?: SkillCreateNestedManyWithoutTenantsInput;
  tag?: TagCreateNestedManyWithoutTenantsInput;
  task?: TaskCreateNestedManyWithoutTenantsInput;
  taskLinkedIssues?: TaskLinkedIssueCreateNestedManyWithoutTenantsInput;
  taskPriority?: TaskPriorityCreateNestedManyWithoutTenantsInput;
  taskRelatedIssueType?: TaskRelatedIssueTypeCreateNestedManyWithoutTenantsInput;
  taskSize?: TaskSizeCreateNestedManyWithoutTenantsInput;
  taskStatus?: TaskStatusCreateNestedManyWithoutTenantsInput;
  taskVersion?: TaskVersionCreateNestedManyWithoutTenantsInput;
  tenantSetting?: TenantSettingCreateNestedManyWithoutTenantsInput;
  timeLog?: TimeLogCreateNestedManyWithoutTenantsInput;
  timeOffPolicy?: TimeOffPolicyCreateNestedManyWithoutTenantsInput;
  timeOffRequest?: TimeOffRequestCreateNestedManyWithoutTenantsInput;
  timeSlot?: TimeSlotCreateNestedManyWithoutTenantsInput;
  timeSlotMinute?: TimeSlotMinuteCreateNestedManyWithoutTenantsInput;
  timesheet?: TimesheetCreateNestedManyWithoutTenantsInput;
  user?: UserCreateNestedManyWithoutTenantsInput;
  userOrganization?: UserOrganizationCreateNestedManyWithoutTenantsInput;
  warehouse?: WarehouseCreateNestedManyWithoutTenantsInput;
  warehouseProduct?: WarehouseProductCreateNestedManyWithoutTenantsInput;
  warehouseProductVariant?: WarehouseProductVariantCreateNestedManyWithoutTenantsInput;
};
