import { AccountingTemplateUpdateManyWithoutTenantsInput } from "./AccountingTemplateUpdateManyWithoutTenantsInput";
import { ActivityUpdateManyWithoutTenantsInput } from "./ActivityUpdateManyWithoutTenantsInput";
import { AppointmentEmployeeUpdateManyWithoutTenantsInput } from "./AppointmentEmployeeUpdateManyWithoutTenantsInput";
import { ApprovalPolicyUpdateManyWithoutTenantsInput } from "./ApprovalPolicyUpdateManyWithoutTenantsInput";
import { AvailabilitySlotUpdateManyWithoutTenantsInput } from "./AvailabilitySlotUpdateManyWithoutTenantsInput";
import { CandidateUpdateManyWithoutTenantsInput } from "./CandidateUpdateManyWithoutTenantsInput";
import { CandidateCriterionRatingUpdateManyWithoutTenantsInput } from "./CandidateCriterionRatingUpdateManyWithoutTenantsInput";
import { CandidateDocumentUpdateManyWithoutTenantsInput } from "./CandidateDocumentUpdateManyWithoutTenantsInput";
import { CandidateEducationUpdateManyWithoutTenantsInput } from "./CandidateEducationUpdateManyWithoutTenantsInput";
import { CandidateExperienceUpdateManyWithoutTenantsInput } from "./CandidateExperienceUpdateManyWithoutTenantsInput";
import { CandidateFeedbackUpdateManyWithoutTenantsInput } from "./CandidateFeedbackUpdateManyWithoutTenantsInput";
import { CandidateInterviewUpdateManyWithoutTenantsInput } from "./CandidateInterviewUpdateManyWithoutTenantsInput";
import { CandidateInterviewerUpdateManyWithoutTenantsInput } from "./CandidateInterviewerUpdateManyWithoutTenantsInput";
import { CandidatePersonalQualityUpdateManyWithoutTenantsInput } from "./CandidatePersonalQualityUpdateManyWithoutTenantsInput";
import { CandidateSkillUpdateManyWithoutTenantsInput } from "./CandidateSkillUpdateManyWithoutTenantsInput";
import { CandidateSourceUpdateManyWithoutTenantsInput } from "./CandidateSourceUpdateManyWithoutTenantsInput";
import { CandidateTechnologyUpdateManyWithoutTenantsInput } from "./CandidateTechnologyUpdateManyWithoutTenantsInput";
import { ChangelogUpdateManyWithoutTenantsInput } from "./ChangelogUpdateManyWithoutTenantsInput";
import { ContactUpdateManyWithoutTenantsInput } from "./ContactUpdateManyWithoutTenantsInput";
import { CustomSmtpUpdateManyWithoutTenantsInput } from "./CustomSmtpUpdateManyWithoutTenantsInput";
import { DealUpdateManyWithoutTenantsInput } from "./DealUpdateManyWithoutTenantsInput";
import { EmailResetUpdateManyWithoutTenantsInput } from "./EmailResetUpdateManyWithoutTenantsInput";
import { EmailSentUpdateManyWithoutTenantsInput } from "./EmailSentUpdateManyWithoutTenantsInput";
import { EmailTemplateUpdateManyWithoutTenantsInput } from "./EmailTemplateUpdateManyWithoutTenantsInput";
import { EmployeeUpdateManyWithoutTenantsInput } from "./EmployeeUpdateManyWithoutTenantsInput";
import { EmployeeAppointmentUpdateManyWithoutTenantsInput } from "./EmployeeAppointmentUpdateManyWithoutTenantsInput";
import { EmployeeAwardUpdateManyWithoutTenantsInput } from "./EmployeeAwardUpdateManyWithoutTenantsInput";
import { EmployeeLevelUpdateManyWithoutTenantsInput } from "./EmployeeLevelUpdateManyWithoutTenantsInput";
import { EmployeePhoneUpdateManyWithoutTenantsInput } from "./EmployeePhoneUpdateManyWithoutTenantsInput";
import { EmployeeProposalTemplateUpdateManyWithoutTenantsInput } from "./EmployeeProposalTemplateUpdateManyWithoutTenantsInput";
import { EmployeeRecurringExpenseUpdateManyWithoutTenantsInput } from "./EmployeeRecurringExpenseUpdateManyWithoutTenantsInput";
import { EmployeeSettingUpdateManyWithoutTenantsInput } from "./EmployeeSettingUpdateManyWithoutTenantsInput";
import { EmployeeUpworkJobSearchCriterionUpdateManyWithoutTenantsInput } from "./EmployeeUpworkJobSearchCriterionUpdateManyWithoutTenantsInput";
import { EquipmentUpdateManyWithoutTenantsInput } from "./EquipmentUpdateManyWithoutTenantsInput";
import { EquipmentSharingUpdateManyWithoutTenantsInput } from "./EquipmentSharingUpdateManyWithoutTenantsInput";
import { EquipmentSharingPolicyUpdateManyWithoutTenantsInput } from "./EquipmentSharingPolicyUpdateManyWithoutTenantsInput";
import { EstimateEmailUpdateManyWithoutTenantsInput } from "./EstimateEmailUpdateManyWithoutTenantsInput";
import { EventTypeUpdateManyWithoutTenantsInput } from "./EventTypeUpdateManyWithoutTenantsInput";
import { ExpenseUpdateManyWithoutTenantsInput } from "./ExpenseUpdateManyWithoutTenantsInput";
import { ExpenseCategoryUpdateManyWithoutTenantsInput } from "./ExpenseCategoryUpdateManyWithoutTenantsInput";
import { FeatureOrganizationUpdateManyWithoutTenantsInput } from "./FeatureOrganizationUpdateManyWithoutTenantsInput";
import { GoalUpdateManyWithoutTenantsInput } from "./GoalUpdateManyWithoutTenantsInput";
import { GoalGeneralSettingUpdateManyWithoutTenantsInput } from "./GoalGeneralSettingUpdateManyWithoutTenantsInput";
import { GoalKpiUpdateManyWithoutTenantsInput } from "./GoalKpiUpdateManyWithoutTenantsInput";
import { GoalKpiTemplateUpdateManyWithoutTenantsInput } from "./GoalKpiTemplateUpdateManyWithoutTenantsInput";
import { GoalTemplateUpdateManyWithoutTenantsInput } from "./GoalTemplateUpdateManyWithoutTenantsInput";
import { GoalTimeFrameUpdateManyWithoutTenantsInput } from "./GoalTimeFrameUpdateManyWithoutTenantsInput";
import { ImageAssetUpdateManyWithoutTenantsInput } from "./ImageAssetUpdateManyWithoutTenantsInput";
import { ImageAssetWhereUniqueInput } from "../imageAsset/ImageAssetWhereUniqueInput";
import { ImportHistoryUpdateManyWithoutTenantsInput } from "./ImportHistoryUpdateManyWithoutTenantsInput";
import { ImportRecordUpdateManyWithoutTenantsInput } from "./ImportRecordUpdateManyWithoutTenantsInput";
import { IncomeUpdateManyWithoutTenantsInput } from "./IncomeUpdateManyWithoutTenantsInput";
import { IntegrationEntitySettingUpdateManyWithoutTenantsInput } from "./IntegrationEntitySettingUpdateManyWithoutTenantsInput";
import { IntegrationEntitySettingTiedUpdateManyWithoutTenantsInput } from "./IntegrationEntitySettingTiedUpdateManyWithoutTenantsInput";
import { IntegrationMapUpdateManyWithoutTenantsInput } from "./IntegrationMapUpdateManyWithoutTenantsInput";
import { IntegrationSettingUpdateManyWithoutTenantsInput } from "./IntegrationSettingUpdateManyWithoutTenantsInput";
import { IntegrationTenantUpdateManyWithoutTenantsInput } from "./IntegrationTenantUpdateManyWithoutTenantsInput";
import { InviteUpdateManyWithoutTenantsInput } from "./InviteUpdateManyWithoutTenantsInput";
import { InvoiceUpdateManyWithoutTenantsInput } from "./InvoiceUpdateManyWithoutTenantsInput";
import { InvoiceEstimateHistoryUpdateManyWithoutTenantsInput } from "./InvoiceEstimateHistoryUpdateManyWithoutTenantsInput";
import { InvoiceItemUpdateManyWithoutTenantsInput } from "./InvoiceItemUpdateManyWithoutTenantsInput";
import { IssueTypeUpdateManyWithoutTenantsInput } from "./IssueTypeUpdateManyWithoutTenantsInput";
import { JobPresetUpdateManyWithoutTenantsInput } from "./JobPresetUpdateManyWithoutTenantsInput";
import { JobPresetUpworkJobSearchCriterionUpdateManyWithoutTenantsInput } from "./JobPresetUpworkJobSearchCriterionUpdateManyWithoutTenantsInput";
import { JobSearchCategoryUpdateManyWithoutTenantsInput } from "./JobSearchCategoryUpdateManyWithoutTenantsInput";
import { JobSearchOccupationUpdateManyWithoutTenantsInput } from "./JobSearchOccupationUpdateManyWithoutTenantsInput";
import { KeyResultUpdateManyWithoutTenantsInput } from "./KeyResultUpdateManyWithoutTenantsInput";
import { KeyResultTemplateUpdateManyWithoutTenantsInput } from "./KeyResultTemplateUpdateManyWithoutTenantsInput";
import { KeyResultUpdateUpdateManyWithoutTenantsInput } from "./KeyResultUpdateUpdateManyWithoutTenantsInput";
import { KnowledgeBaseUpdateManyWithoutTenantsInput } from "./KnowledgeBaseUpdateManyWithoutTenantsInput";
import { KnowledgeBaseArticleUpdateManyWithoutTenantsInput } from "./KnowledgeBaseArticleUpdateManyWithoutTenantsInput";
import { KnowledgeBaseAuthorUpdateManyWithoutTenantsInput } from "./KnowledgeBaseAuthorUpdateManyWithoutTenantsInput";
import { MerchantUpdateManyWithoutTenantsInput } from "./MerchantUpdateManyWithoutTenantsInput";
import { OrganizationUpdateManyWithoutTenantsInput } from "./OrganizationUpdateManyWithoutTenantsInput";
import { OrganizationAwardUpdateManyWithoutTenantsInput } from "./OrganizationAwardUpdateManyWithoutTenantsInput";
import { OrganizationContactUpdateManyWithoutTenantsInput } from "./OrganizationContactUpdateManyWithoutTenantsInput";
import { OrganizationDepartmentUpdateManyWithoutTenantsInput } from "./OrganizationDepartmentUpdateManyWithoutTenantsInput";
import { OrganizationDocumentUpdateManyWithoutTenantsInput } from "./OrganizationDocumentUpdateManyWithoutTenantsInput";
import { OrganizationEmploymentTypeUpdateManyWithoutTenantsInput } from "./OrganizationEmploymentTypeUpdateManyWithoutTenantsInput";
import { OrganizationLanguageUpdateManyWithoutTenantsInput } from "./OrganizationLanguageUpdateManyWithoutTenantsInput";
import { OrganizationPositionUpdateManyWithoutTenantsInput } from "./OrganizationPositionUpdateManyWithoutTenantsInput";
import { OrganizationProjectUpdateManyWithoutTenantsInput } from "./OrganizationProjectUpdateManyWithoutTenantsInput";
import { OrganizationRecurringExpenseUpdateManyWithoutTenantsInput } from "./OrganizationRecurringExpenseUpdateManyWithoutTenantsInput";
import { OrganizationSprintUpdateManyWithoutTenantsInput } from "./OrganizationSprintUpdateManyWithoutTenantsInput";
import { OrganizationTaskSettingUpdateManyWithoutTenantsInput } from "./OrganizationTaskSettingUpdateManyWithoutTenantsInput";
import { OrganizationTeamUpdateManyWithoutTenantsInput } from "./OrganizationTeamUpdateManyWithoutTenantsInput";
import { OrganizationTeamEmployeeUpdateManyWithoutTenantsInput } from "./OrganizationTeamEmployeeUpdateManyWithoutTenantsInput";
import { OrganizationTeamJoinRequestUpdateManyWithoutTenantsInput } from "./OrganizationTeamJoinRequestUpdateManyWithoutTenantsInput";
import { OrganizationVendorUpdateManyWithoutTenantsInput } from "./OrganizationVendorUpdateManyWithoutTenantsInput";
import { PaymentUpdateManyWithoutTenantsInput } from "./PaymentUpdateManyWithoutTenantsInput";
import { PipelineUpdateManyWithoutTenantsInput } from "./PipelineUpdateManyWithoutTenantsInput";
import { PipelineStageUpdateManyWithoutTenantsInput } from "./PipelineStageUpdateManyWithoutTenantsInput";
import { ProductUpdateManyWithoutTenantsInput } from "./ProductUpdateManyWithoutTenantsInput";
import { ProductCategoryUpdateManyWithoutTenantsInput } from "./ProductCategoryUpdateManyWithoutTenantsInput";
import { ProductCategoryTranslationUpdateManyWithoutTenantsInput } from "./ProductCategoryTranslationUpdateManyWithoutTenantsInput";
import { ProductOptionUpdateManyWithoutTenantsInput } from "./ProductOptionUpdateManyWithoutTenantsInput";
import { ProductOptionGroupUpdateManyWithoutTenantsInput } from "./ProductOptionGroupUpdateManyWithoutTenantsInput";
import { ProductOptionGroupTranslationUpdateManyWithoutTenantsInput } from "./ProductOptionGroupTranslationUpdateManyWithoutTenantsInput";
import { ProductOptionTranslationUpdateManyWithoutTenantsInput } from "./ProductOptionTranslationUpdateManyWithoutTenantsInput";
import { ProductTranslationUpdateManyWithoutTenantsInput } from "./ProductTranslationUpdateManyWithoutTenantsInput";
import { ProductTypeUpdateManyWithoutTenantsInput } from "./ProductTypeUpdateManyWithoutTenantsInput";
import { ProductTypeTranslationUpdateManyWithoutTenantsInput } from "./ProductTypeTranslationUpdateManyWithoutTenantsInput";
import { ProductVariantUpdateManyWithoutTenantsInput } from "./ProductVariantUpdateManyWithoutTenantsInput";
import { ProductVariantPriceUpdateManyWithoutTenantsInput } from "./ProductVariantPriceUpdateManyWithoutTenantsInput";
import { ProductVariantSettingUpdateManyWithoutTenantsInput } from "./ProductVariantSettingUpdateManyWithoutTenantsInput";
import { ProposalUpdateManyWithoutTenantsInput } from "./ProposalUpdateManyWithoutTenantsInput";
import { ReportOrganizationUpdateManyWithoutTenantsInput } from "./ReportOrganizationUpdateManyWithoutTenantsInput";
import { RequestApprovalUpdateManyWithoutTenantsInput } from "./RequestApprovalUpdateManyWithoutTenantsInput";
import { RequestApprovalEmployeeUpdateManyWithoutTenantsInput } from "./RequestApprovalEmployeeUpdateManyWithoutTenantsInput";
import { RequestApprovalTeamUpdateManyWithoutTenantsInput } from "./RequestApprovalTeamUpdateManyWithoutTenantsInput";
import { RoleUpdateManyWithoutTenantsInput } from "./RoleUpdateManyWithoutTenantsInput";
import { RolePermissionUpdateManyWithoutTenantsInput } from "./RolePermissionUpdateManyWithoutTenantsInput";
import { ScreenshotUpdateManyWithoutTenantsInput } from "./ScreenshotUpdateManyWithoutTenantsInput";
import { SkillUpdateManyWithoutTenantsInput } from "./SkillUpdateManyWithoutTenantsInput";
import { TagUpdateManyWithoutTenantsInput } from "./TagUpdateManyWithoutTenantsInput";
import { TaskUpdateManyWithoutTenantsInput } from "./TaskUpdateManyWithoutTenantsInput";
import { TaskLinkedIssueUpdateManyWithoutTenantsInput } from "./TaskLinkedIssueUpdateManyWithoutTenantsInput";
import { TaskPriorityUpdateManyWithoutTenantsInput } from "./TaskPriorityUpdateManyWithoutTenantsInput";
import { TaskRelatedIssueTypeUpdateManyWithoutTenantsInput } from "./TaskRelatedIssueTypeUpdateManyWithoutTenantsInput";
import { TaskSizeUpdateManyWithoutTenantsInput } from "./TaskSizeUpdateManyWithoutTenantsInput";
import { TaskStatusUpdateManyWithoutTenantsInput } from "./TaskStatusUpdateManyWithoutTenantsInput";
import { TaskVersionUpdateManyWithoutTenantsInput } from "./TaskVersionUpdateManyWithoutTenantsInput";
import { TenantSettingUpdateManyWithoutTenantsInput } from "./TenantSettingUpdateManyWithoutTenantsInput";
import { TimeLogUpdateManyWithoutTenantsInput } from "./TimeLogUpdateManyWithoutTenantsInput";
import { TimeOffPolicyUpdateManyWithoutTenantsInput } from "./TimeOffPolicyUpdateManyWithoutTenantsInput";
import { TimeOffRequestUpdateManyWithoutTenantsInput } from "./TimeOffRequestUpdateManyWithoutTenantsInput";
import { TimeSlotUpdateManyWithoutTenantsInput } from "./TimeSlotUpdateManyWithoutTenantsInput";
import { TimeSlotMinuteUpdateManyWithoutTenantsInput } from "./TimeSlotMinuteUpdateManyWithoutTenantsInput";
import { TimesheetUpdateManyWithoutTenantsInput } from "./TimesheetUpdateManyWithoutTenantsInput";
import { UserUpdateManyWithoutTenantsInput } from "./UserUpdateManyWithoutTenantsInput";
import { UserOrganizationUpdateManyWithoutTenantsInput } from "./UserOrganizationUpdateManyWithoutTenantsInput";
import { WarehouseUpdateManyWithoutTenantsInput } from "./WarehouseUpdateManyWithoutTenantsInput";
import { WarehouseProductUpdateManyWithoutTenantsInput } from "./WarehouseProductUpdateManyWithoutTenantsInput";
import { WarehouseProductVariantUpdateManyWithoutTenantsInput } from "./WarehouseProductVariantUpdateManyWithoutTenantsInput";

export type TenantUpdateInput = {
  name?: string;
  logo?: string | null;
  accountingTemplate?: AccountingTemplateUpdateManyWithoutTenantsInput;
  activity?: ActivityUpdateManyWithoutTenantsInput;
  appointmentEmployee?: AppointmentEmployeeUpdateManyWithoutTenantsInput;
  approvalPolicy?: ApprovalPolicyUpdateManyWithoutTenantsInput;
  availabilitySlot?: AvailabilitySlotUpdateManyWithoutTenantsInput;
  candidate?: CandidateUpdateManyWithoutTenantsInput;
  candidateCriterionRating?: CandidateCriterionRatingUpdateManyWithoutTenantsInput;
  candidateDocument?: CandidateDocumentUpdateManyWithoutTenantsInput;
  candidateEducation?: CandidateEducationUpdateManyWithoutTenantsInput;
  candidateExperience?: CandidateExperienceUpdateManyWithoutTenantsInput;
  candidateFeedback?: CandidateFeedbackUpdateManyWithoutTenantsInput;
  candidateInterview?: CandidateInterviewUpdateManyWithoutTenantsInput;
  candidateInterviewer?: CandidateInterviewerUpdateManyWithoutTenantsInput;
  candidatePersonalQuality?: CandidatePersonalQualityUpdateManyWithoutTenantsInput;
  candidateSkill?: CandidateSkillUpdateManyWithoutTenantsInput;
  candidateSource?: CandidateSourceUpdateManyWithoutTenantsInput;
  candidateTechnology?: CandidateTechnologyUpdateManyWithoutTenantsInput;
  changelog?: ChangelogUpdateManyWithoutTenantsInput;
  contact?: ContactUpdateManyWithoutTenantsInput;
  customSmtp?: CustomSmtpUpdateManyWithoutTenantsInput;
  deal?: DealUpdateManyWithoutTenantsInput;
  emailReset?: EmailResetUpdateManyWithoutTenantsInput;
  emailSent?: EmailSentUpdateManyWithoutTenantsInput;
  emailTemplate?: EmailTemplateUpdateManyWithoutTenantsInput;
  employee?: EmployeeUpdateManyWithoutTenantsInput;
  employeeAppointment?: EmployeeAppointmentUpdateManyWithoutTenantsInput;
  employeeAward?: EmployeeAwardUpdateManyWithoutTenantsInput;
  employeeLevel?: EmployeeLevelUpdateManyWithoutTenantsInput;
  employeePhone?: EmployeePhoneUpdateManyWithoutTenantsInput;
  employeeProposalTemplate?: EmployeeProposalTemplateUpdateManyWithoutTenantsInput;
  employeeRecurringExpense?: EmployeeRecurringExpenseUpdateManyWithoutTenantsInput;
  employeeSetting?: EmployeeSettingUpdateManyWithoutTenantsInput;
  employeeUpworkJobSearchCriterion?: EmployeeUpworkJobSearchCriterionUpdateManyWithoutTenantsInput;
  equipment?: EquipmentUpdateManyWithoutTenantsInput;
  equipmentSharing?: EquipmentSharingUpdateManyWithoutTenantsInput;
  equipmentSharingPolicy?: EquipmentSharingPolicyUpdateManyWithoutTenantsInput;
  estimateEmail?: EstimateEmailUpdateManyWithoutTenantsInput;
  eventType?: EventTypeUpdateManyWithoutTenantsInput;
  expense?: ExpenseUpdateManyWithoutTenantsInput;
  expenseCategory?: ExpenseCategoryUpdateManyWithoutTenantsInput;
  featureOrganization?: FeatureOrganizationUpdateManyWithoutTenantsInput;
  goal?: GoalUpdateManyWithoutTenantsInput;
  goalGeneralSetting?: GoalGeneralSettingUpdateManyWithoutTenantsInput;
  goalKpi?: GoalKpiUpdateManyWithoutTenantsInput;
  goalKpiTemplate?: GoalKpiTemplateUpdateManyWithoutTenantsInput;
  goalTemplate?: GoalTemplateUpdateManyWithoutTenantsInput;
  goalTimeFrame?: GoalTimeFrameUpdateManyWithoutTenantsInput;
  imageAssetImageAssetTenantIdTotenant?: ImageAssetUpdateManyWithoutTenantsInput;
  imageAssetTenantImageIdToimageAsset?: ImageAssetWhereUniqueInput | null;
  importHistory?: ImportHistoryUpdateManyWithoutTenantsInput;
  importRecord?: ImportRecordUpdateManyWithoutTenantsInput;
  income?: IncomeUpdateManyWithoutTenantsInput;
  integrationEntitySetting?: IntegrationEntitySettingUpdateManyWithoutTenantsInput;
  integrationEntitySettingTied?: IntegrationEntitySettingTiedUpdateManyWithoutTenantsInput;
  integrationMap?: IntegrationMapUpdateManyWithoutTenantsInput;
  integrationSetting?: IntegrationSettingUpdateManyWithoutTenantsInput;
  integrationTenant?: IntegrationTenantUpdateManyWithoutTenantsInput;
  invite?: InviteUpdateManyWithoutTenantsInput;
  invoice?: InvoiceUpdateManyWithoutTenantsInput;
  invoiceEstimateHistory?: InvoiceEstimateHistoryUpdateManyWithoutTenantsInput;
  invoiceItem?: InvoiceItemUpdateManyWithoutTenantsInput;
  issueType?: IssueTypeUpdateManyWithoutTenantsInput;
  jobPreset?: JobPresetUpdateManyWithoutTenantsInput;
  jobPresetUpworkJobSearchCriterion?: JobPresetUpworkJobSearchCriterionUpdateManyWithoutTenantsInput;
  jobSearchCategory?: JobSearchCategoryUpdateManyWithoutTenantsInput;
  jobSearchOccupation?: JobSearchOccupationUpdateManyWithoutTenantsInput;
  keyResult?: KeyResultUpdateManyWithoutTenantsInput;
  keyResultTemplate?: KeyResultTemplateUpdateManyWithoutTenantsInput;
  keyResultUpdate?: KeyResultUpdateUpdateManyWithoutTenantsInput;
  knowledgeBase?: KnowledgeBaseUpdateManyWithoutTenantsInput;
  knowledgeBaseArticle?: KnowledgeBaseArticleUpdateManyWithoutTenantsInput;
  knowledgeBaseAuthor?: KnowledgeBaseAuthorUpdateManyWithoutTenantsInput;
  merchant?: MerchantUpdateManyWithoutTenantsInput;
  organization?: OrganizationUpdateManyWithoutTenantsInput;
  organizationAward?: OrganizationAwardUpdateManyWithoutTenantsInput;
  organizationContact?: OrganizationContactUpdateManyWithoutTenantsInput;
  organizationDepartment?: OrganizationDepartmentUpdateManyWithoutTenantsInput;
  organizationDocument?: OrganizationDocumentUpdateManyWithoutTenantsInput;
  organizationEmploymentType?: OrganizationEmploymentTypeUpdateManyWithoutTenantsInput;
  organizationLanguage?: OrganizationLanguageUpdateManyWithoutTenantsInput;
  organizationPosition?: OrganizationPositionUpdateManyWithoutTenantsInput;
  organizationProject?: OrganizationProjectUpdateManyWithoutTenantsInput;
  organizationRecurringExpense?: OrganizationRecurringExpenseUpdateManyWithoutTenantsInput;
  organizationSprint?: OrganizationSprintUpdateManyWithoutTenantsInput;
  organizationTaskSetting?: OrganizationTaskSettingUpdateManyWithoutTenantsInput;
  organizationTeam?: OrganizationTeamUpdateManyWithoutTenantsInput;
  organizationTeamEmployee?: OrganizationTeamEmployeeUpdateManyWithoutTenantsInput;
  organizationTeamJoinRequest?: OrganizationTeamJoinRequestUpdateManyWithoutTenantsInput;
  organizationVendor?: OrganizationVendorUpdateManyWithoutTenantsInput;
  payment?: PaymentUpdateManyWithoutTenantsInput;
  pipeline?: PipelineUpdateManyWithoutTenantsInput;
  pipelineStage?: PipelineStageUpdateManyWithoutTenantsInput;
  product?: ProductUpdateManyWithoutTenantsInput;
  productCategory?: ProductCategoryUpdateManyWithoutTenantsInput;
  productCategoryTranslation?: ProductCategoryTranslationUpdateManyWithoutTenantsInput;
  productOption?: ProductOptionUpdateManyWithoutTenantsInput;
  productOptionGroup?: ProductOptionGroupUpdateManyWithoutTenantsInput;
  productOptionGroupTranslation?: ProductOptionGroupTranslationUpdateManyWithoutTenantsInput;
  productOptionTranslation?: ProductOptionTranslationUpdateManyWithoutTenantsInput;
  productTranslation?: ProductTranslationUpdateManyWithoutTenantsInput;
  productType?: ProductTypeUpdateManyWithoutTenantsInput;
  productTypeTranslation?: ProductTypeTranslationUpdateManyWithoutTenantsInput;
  productVariant?: ProductVariantUpdateManyWithoutTenantsInput;
  productVariantPrice?: ProductVariantPriceUpdateManyWithoutTenantsInput;
  productVariantSetting?: ProductVariantSettingUpdateManyWithoutTenantsInput;
  proposal?: ProposalUpdateManyWithoutTenantsInput;
  reportOrganization?: ReportOrganizationUpdateManyWithoutTenantsInput;
  requestApproval?: RequestApprovalUpdateManyWithoutTenantsInput;
  requestApprovalEmployee?: RequestApprovalEmployeeUpdateManyWithoutTenantsInput;
  requestApprovalTeam?: RequestApprovalTeamUpdateManyWithoutTenantsInput;
  role?: RoleUpdateManyWithoutTenantsInput;
  rolePermission?: RolePermissionUpdateManyWithoutTenantsInput;
  screenshot?: ScreenshotUpdateManyWithoutTenantsInput;
  skill?: SkillUpdateManyWithoutTenantsInput;
  tag?: TagUpdateManyWithoutTenantsInput;
  task?: TaskUpdateManyWithoutTenantsInput;
  taskLinkedIssues?: TaskLinkedIssueUpdateManyWithoutTenantsInput;
  taskPriority?: TaskPriorityUpdateManyWithoutTenantsInput;
  taskRelatedIssueType?: TaskRelatedIssueTypeUpdateManyWithoutTenantsInput;
  taskSize?: TaskSizeUpdateManyWithoutTenantsInput;
  taskStatus?: TaskStatusUpdateManyWithoutTenantsInput;
  taskVersion?: TaskVersionUpdateManyWithoutTenantsInput;
  tenantSetting?: TenantSettingUpdateManyWithoutTenantsInput;
  timeLog?: TimeLogUpdateManyWithoutTenantsInput;
  timeOffPolicy?: TimeOffPolicyUpdateManyWithoutTenantsInput;
  timeOffRequest?: TimeOffRequestUpdateManyWithoutTenantsInput;
  timeSlot?: TimeSlotUpdateManyWithoutTenantsInput;
  timeSlotMinute?: TimeSlotMinuteUpdateManyWithoutTenantsInput;
  timesheet?: TimesheetUpdateManyWithoutTenantsInput;
  user?: UserUpdateManyWithoutTenantsInput;
  userOrganization?: UserOrganizationUpdateManyWithoutTenantsInput;
  warehouse?: WarehouseUpdateManyWithoutTenantsInput;
  warehouseProduct?: WarehouseProductUpdateManyWithoutTenantsInput;
  warehouseProductVariant?: WarehouseProductVariantUpdateManyWithoutTenantsInput;
};
