import { AccountingTemplate } from "../accountingTemplate/AccountingTemplate";
import { Activity } from "../activity/Activity";
import { AppointmentEmployee } from "../appointmentEmployee/AppointmentEmployee";
import { ApprovalPolicy } from "../approvalPolicy/ApprovalPolicy";
import { AvailabilitySlot } from "../availabilitySlot/AvailabilitySlot";
import { Candidate } from "../candidate/Candidate";
import { CandidateCriterionRating } from "../candidateCriterionRating/CandidateCriterionRating";
import { CandidateDocument } from "../candidateDocument/CandidateDocument";
import { CandidateEducation } from "../candidateEducation/CandidateEducation";
import { CandidateExperience } from "../candidateExperience/CandidateExperience";
import { CandidateFeedback } from "../candidateFeedback/CandidateFeedback";
import { CandidateInterview } from "../candidateInterview/CandidateInterview";
import { CandidateInterviewer } from "../candidateInterviewer/CandidateInterviewer";
import { CandidatePersonalQuality } from "../candidatePersonalQuality/CandidatePersonalQuality";
import { CandidateSkill } from "../candidateSkill/CandidateSkill";
import { CandidateSource } from "../candidateSource/CandidateSource";
import { CandidateTechnology } from "../candidateTechnology/CandidateTechnology";
import { Changelog } from "../changelog/Changelog";
import { Contact } from "../contact/Contact";
import { CustomSmtp } from "../customSmtp/CustomSmtp";
import { Deal } from "../deal/Deal";
import { EmailReset } from "../emailReset/EmailReset";
import { EmailSent } from "../emailSent/EmailSent";
import { EmailTemplate } from "../emailTemplate/EmailTemplate";
import { Employee } from "../employee/Employee";
import { EmployeeAppointment } from "../employeeAppointment/EmployeeAppointment";
import { EmployeeAward } from "../employeeAward/EmployeeAward";
import { EmployeeLevel } from "../employeeLevel/EmployeeLevel";
import { EmployeePhone } from "../employeePhone/EmployeePhone";
import { EmployeeProposalTemplate } from "../employeeProposalTemplate/EmployeeProposalTemplate";
import { EmployeeRecurringExpense } from "../employeeRecurringExpense/EmployeeRecurringExpense";
import { EmployeeSetting } from "../employeeSetting/EmployeeSetting";
import { EmployeeUpworkJobSearchCriterion } from "../employeeUpworkJobSearchCriterion/EmployeeUpworkJobSearchCriterion";
import { Equipment } from "../equipment/Equipment";
import { EquipmentSharing } from "../equipmentSharing/EquipmentSharing";
import { EquipmentSharingPolicy } from "../equipmentSharingPolicy/EquipmentSharingPolicy";
import { EstimateEmail } from "../estimateEmail/EstimateEmail";
import { EventType } from "../eventType/EventType";
import { Expense } from "../expense/Expense";
import { ExpenseCategory } from "../expenseCategory/ExpenseCategory";
import { FeatureOrganization } from "../featureOrganization/FeatureOrganization";
import { Goal } from "../goal/Goal";
import { GoalGeneralSetting } from "../goalGeneralSetting/GoalGeneralSetting";
import { GoalKpi } from "../goalKpi/GoalKpi";
import { GoalKpiTemplate } from "../goalKpiTemplate/GoalKpiTemplate";
import { GoalTemplate } from "../goalTemplate/GoalTemplate";
import { GoalTimeFrame } from "../goalTimeFrame/GoalTimeFrame";
import { ImageAsset } from "../imageAsset/ImageAsset";
import { ImportHistory } from "../importHistory/ImportHistory";
import { ImportRecord } from "../importRecord/ImportRecord";
import { Income } from "../income/Income";
import { IntegrationEntitySetting } from "../integrationEntitySetting/IntegrationEntitySetting";
import { IntegrationEntitySettingTied } from "../integrationEntitySettingTied/IntegrationEntitySettingTied";
import { IntegrationMap } from "../integrationMap/IntegrationMap";
import { IntegrationSetting } from "../integrationSetting/IntegrationSetting";
import { IntegrationTenant } from "../integrationTenant/IntegrationTenant";
import { Invite } from "../invite/Invite";
import { Invoice } from "../invoice/Invoice";
import { InvoiceEstimateHistory } from "../invoiceEstimateHistory/InvoiceEstimateHistory";
import { InvoiceItem } from "../invoiceItem/InvoiceItem";
import { IssueType } from "../issueType/IssueType";
import { JobPreset } from "../jobPreset/JobPreset";
import { JobPresetUpworkJobSearchCriterion } from "../jobPresetUpworkJobSearchCriterion/JobPresetUpworkJobSearchCriterion";
import { JobSearchCategory } from "../jobSearchCategory/JobSearchCategory";
import { JobSearchOccupation } from "../jobSearchOccupation/JobSearchOccupation";
import { KeyResult } from "../keyResult/KeyResult";
import { KeyResultTemplate } from "../keyResultTemplate/KeyResultTemplate";
import { KeyResultUpdate } from "../keyResultUpdate/KeyResultUpdate";
import { KnowledgeBase } from "../knowledgeBase/KnowledgeBase";
import { KnowledgeBaseArticle } from "../knowledgeBaseArticle/KnowledgeBaseArticle";
import { KnowledgeBaseAuthor } from "../knowledgeBaseAuthor/KnowledgeBaseAuthor";
import { Merchant } from "../merchant/Merchant";
import { Organization } from "../organization/Organization";
import { OrganizationAward } from "../organizationAward/OrganizationAward";
import { OrganizationContact } from "../organizationContact/OrganizationContact";
import { OrganizationDepartment } from "../organizationDepartment/OrganizationDepartment";
import { OrganizationDocument } from "../organizationDocument/OrganizationDocument";
import { OrganizationEmploymentType } from "../organizationEmploymentType/OrganizationEmploymentType";
import { OrganizationLanguage } from "../organizationLanguage/OrganizationLanguage";
import { OrganizationPosition } from "../organizationPosition/OrganizationPosition";
import { OrganizationProject } from "../organizationProject/OrganizationProject";
import { OrganizationRecurringExpense } from "../organizationRecurringExpense/OrganizationRecurringExpense";
import { OrganizationSprint } from "../organizationSprint/OrganizationSprint";
import { OrganizationTaskSetting } from "../organizationTaskSetting/OrganizationTaskSetting";
import { OrganizationTeam } from "../organizationTeam/OrganizationTeam";
import { OrganizationTeamEmployee } from "../organizationTeamEmployee/OrganizationTeamEmployee";
import { OrganizationTeamJoinRequest } from "../organizationTeamJoinRequest/OrganizationTeamJoinRequest";
import { OrganizationVendor } from "../organizationVendor/OrganizationVendor";
import { Payment } from "../payment/Payment";
import { Pipeline } from "../pipeline/Pipeline";
import { PipelineStage } from "../pipelineStage/PipelineStage";
import { Product } from "../product/Product";
import { ProductCategory } from "../productCategory/ProductCategory";
import { ProductCategoryTranslation } from "../productCategoryTranslation/ProductCategoryTranslation";
import { ProductOption } from "../productOption/ProductOption";
import { ProductOptionGroup } from "../productOptionGroup/ProductOptionGroup";
import { ProductOptionGroupTranslation } from "../productOptionGroupTranslation/ProductOptionGroupTranslation";
import { ProductOptionTranslation } from "../productOptionTranslation/ProductOptionTranslation";
import { ProductTranslation } from "../productTranslation/ProductTranslation";
import { ProductType } from "../productType/ProductType";
import { ProductTypeTranslation } from "../productTypeTranslation/ProductTypeTranslation";
import { ProductVariant } from "../productVariant/ProductVariant";
import { ProductVariantPrice } from "../productVariantPrice/ProductVariantPrice";
import { ProductVariantSetting } from "../productVariantSetting/ProductVariantSetting";
import { Proposal } from "../proposal/Proposal";
import { ReportOrganization } from "../reportOrganization/ReportOrganization";
import { RequestApproval } from "../requestApproval/RequestApproval";
import { RequestApprovalEmployee } from "../requestApprovalEmployee/RequestApprovalEmployee";
import { RequestApprovalTeam } from "../requestApprovalTeam/RequestApprovalTeam";
import { Role } from "../role/Role";
import { RolePermission } from "../rolePermission/RolePermission";
import { Screenshot } from "../screenshot/Screenshot";
import { Skill } from "../skill/Skill";
import { Tag } from "../tag/Tag";
import { Task } from "../task/Task";
import { TaskLinkedIssue } from "../taskLinkedIssue/TaskLinkedIssue";
import { TaskPriority } from "../taskPriority/TaskPriority";
import { TaskRelatedIssueType } from "../taskRelatedIssueType/TaskRelatedIssueType";
import { TaskSize } from "../taskSize/TaskSize";
import { TaskStatus } from "../taskStatus/TaskStatus";
import { TaskVersion } from "../taskVersion/TaskVersion";
import { TenantSetting } from "../tenantSetting/TenantSetting";
import { TimeLog } from "../timeLog/TimeLog";
import { TimeOffPolicy } from "../timeOffPolicy/TimeOffPolicy";
import { TimeOffRequest } from "../timeOffRequest/TimeOffRequest";
import { TimeSlot } from "../timeSlot/TimeSlot";
import { TimeSlotMinute } from "../timeSlotMinute/TimeSlotMinute";
import { Timesheet } from "../timesheet/Timesheet";
import { User } from "../user/User";
import { UserOrganization } from "../userOrganization/UserOrganization";
import { Warehouse } from "../warehouse/Warehouse";
import { WarehouseProduct } from "../warehouseProduct/WarehouseProduct";
import { WarehouseProductVariant } from "../warehouseProductVariant/WarehouseProductVariant";

export type Tenant = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  name: string;
  logo: string | null;
  accountingTemplate?: Array<AccountingTemplate>;
  activity?: Array<Activity>;
  appointmentEmployee?: Array<AppointmentEmployee>;
  approvalPolicy?: Array<ApprovalPolicy>;
  availabilitySlot?: Array<AvailabilitySlot>;
  candidate?: Array<Candidate>;
  candidateCriterionRating?: Array<CandidateCriterionRating>;
  candidateDocument?: Array<CandidateDocument>;
  candidateEducation?: Array<CandidateEducation>;
  candidateExperience?: Array<CandidateExperience>;
  candidateFeedback?: Array<CandidateFeedback>;
  candidateInterview?: Array<CandidateInterview>;
  candidateInterviewer?: Array<CandidateInterviewer>;
  candidatePersonalQuality?: Array<CandidatePersonalQuality>;
  candidateSkill?: Array<CandidateSkill>;
  candidateSource?: Array<CandidateSource>;
  candidateTechnology?: Array<CandidateTechnology>;
  changelog?: Array<Changelog>;
  contact?: Array<Contact>;
  customSmtp?: Array<CustomSmtp>;
  deal?: Array<Deal>;
  emailReset?: Array<EmailReset>;
  emailSent?: Array<EmailSent>;
  emailTemplate?: Array<EmailTemplate>;
  employee?: Array<Employee>;
  employeeAppointment?: Array<EmployeeAppointment>;
  employeeAward?: Array<EmployeeAward>;
  employeeLevel?: Array<EmployeeLevel>;
  employeePhone?: Array<EmployeePhone>;
  employeeProposalTemplate?: Array<EmployeeProposalTemplate>;
  employeeRecurringExpense?: Array<EmployeeRecurringExpense>;
  employeeSetting?: Array<EmployeeSetting>;
  employeeUpworkJobSearchCriterion?: Array<EmployeeUpworkJobSearchCriterion>;
  equipment?: Array<Equipment>;
  equipmentSharing?: Array<EquipmentSharing>;
  equipmentSharingPolicy?: Array<EquipmentSharingPolicy>;
  estimateEmail?: Array<EstimateEmail>;
  eventType?: Array<EventType>;
  expense?: Array<Expense>;
  expenseCategory?: Array<ExpenseCategory>;
  featureOrganization?: Array<FeatureOrganization>;
  goal?: Array<Goal>;
  goalGeneralSetting?: Array<GoalGeneralSetting>;
  goalKpi?: Array<GoalKpi>;
  goalKpiTemplate?: Array<GoalKpiTemplate>;
  goalTemplate?: Array<GoalTemplate>;
  goalTimeFrame?: Array<GoalTimeFrame>;
  imageAssetImageAssetTenantIdTotenant?: Array<ImageAsset>;
  imageAssetTenantImageIdToimageAsset?: ImageAsset | null;
  importHistory?: Array<ImportHistory>;
  importRecord?: Array<ImportRecord>;
  income?: Array<Income>;
  integrationEntitySetting?: Array<IntegrationEntitySetting>;
  integrationEntitySettingTied?: Array<IntegrationEntitySettingTied>;
  integrationMap?: Array<IntegrationMap>;
  integrationSetting?: Array<IntegrationSetting>;
  integrationTenant?: Array<IntegrationTenant>;
  invite?: Array<Invite>;
  invoice?: Array<Invoice>;
  invoiceEstimateHistory?: Array<InvoiceEstimateHistory>;
  invoiceItem?: Array<InvoiceItem>;
  issueType?: Array<IssueType>;
  jobPreset?: Array<JobPreset>;
  jobPresetUpworkJobSearchCriterion?: Array<JobPresetUpworkJobSearchCriterion>;
  jobSearchCategory?: Array<JobSearchCategory>;
  jobSearchOccupation?: Array<JobSearchOccupation>;
  keyResult?: Array<KeyResult>;
  keyResultTemplate?: Array<KeyResultTemplate>;
  keyResultUpdate?: Array<KeyResultUpdate>;
  knowledgeBase?: Array<KnowledgeBase>;
  knowledgeBaseArticle?: Array<KnowledgeBaseArticle>;
  knowledgeBaseAuthor?: Array<KnowledgeBaseAuthor>;
  merchant?: Array<Merchant>;
  organization?: Array<Organization>;
  organizationAward?: Array<OrganizationAward>;
  organizationContact?: Array<OrganizationContact>;
  organizationDepartment?: Array<OrganizationDepartment>;
  organizationDocument?: Array<OrganizationDocument>;
  organizationEmploymentType?: Array<OrganizationEmploymentType>;
  organizationLanguage?: Array<OrganizationLanguage>;
  organizationPosition?: Array<OrganizationPosition>;
  organizationProject?: Array<OrganizationProject>;
  organizationRecurringExpense?: Array<OrganizationRecurringExpense>;
  organizationSprint?: Array<OrganizationSprint>;
  organizationTaskSetting?: Array<OrganizationTaskSetting>;
  organizationTeam?: Array<OrganizationTeam>;
  organizationTeamEmployee?: Array<OrganizationTeamEmployee>;
  organizationTeamJoinRequest?: Array<OrganizationTeamJoinRequest>;
  organizationVendor?: Array<OrganizationVendor>;
  payment?: Array<Payment>;
  pipeline?: Array<Pipeline>;
  pipelineStage?: Array<PipelineStage>;
  product?: Array<Product>;
  productCategory?: Array<ProductCategory>;
  productCategoryTranslation?: Array<ProductCategoryTranslation>;
  productOption?: Array<ProductOption>;
  productOptionGroup?: Array<ProductOptionGroup>;
  productOptionGroupTranslation?: Array<ProductOptionGroupTranslation>;
  productOptionTranslation?: Array<ProductOptionTranslation>;
  productTranslation?: Array<ProductTranslation>;
  productType?: Array<ProductType>;
  productTypeTranslation?: Array<ProductTypeTranslation>;
  productVariant?: Array<ProductVariant>;
  productVariantPrice?: Array<ProductVariantPrice>;
  productVariantSetting?: Array<ProductVariantSetting>;
  proposal?: Array<Proposal>;
  reportOrganization?: Array<ReportOrganization>;
  requestApproval?: Array<RequestApproval>;
  requestApprovalEmployee?: Array<RequestApprovalEmployee>;
  requestApprovalTeam?: Array<RequestApprovalTeam>;
  role?: Array<Role>;
  rolePermission?: Array<RolePermission>;
  screenshot?: Array<Screenshot>;
  skill?: Array<Skill>;
  tag?: Array<Tag>;
  task?: Array<Task>;
  taskLinkedIssues?: Array<TaskLinkedIssue>;
  taskPriority?: Array<TaskPriority>;
  taskRelatedIssueType?: Array<TaskRelatedIssueType>;
  taskSize?: Array<TaskSize>;
  taskStatus?: Array<TaskStatus>;
  taskVersion?: Array<TaskVersion>;
  tenantSetting?: Array<TenantSetting>;
  timeLog?: Array<TimeLog>;
  timeOffPolicy?: Array<TimeOffPolicy>;
  timeOffRequest?: Array<TimeOffRequest>;
  timeSlot?: Array<TimeSlot>;
  timeSlotMinute?: Array<TimeSlotMinute>;
  timesheet?: Array<Timesheet>;
  user?: Array<User>;
  userOrganization?: Array<UserOrganization>;
  warehouse?: Array<Warehouse>;
  warehouseProduct?: Array<WarehouseProduct>;
  warehouseProductVariant?: Array<WarehouseProductVariant>;
};
