/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field, Float } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsDate,
  IsOptional,
  IsNumber,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { Decimal } from "decimal.js";
import { EnumCandidateFeedbackStatus } from "./EnumCandidateFeedbackStatus";
import { CandidateInterview } from "../../candidateInterview/base/CandidateInterview";
import { Organization } from "../../organization/base/Organization";
import { CandidateInterviewer } from "../../candidateInterviewer/base/CandidateInterviewer";
import { Tenant } from "../../tenant/base/Tenant";
import { Candidate } from "../../candidate/base/Candidate";
import { CandidateCriterionRating } from "../../candidateCriterionRating/base/CandidateCriterionRating";

@ObjectType()
class CandidateFeedback {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description!: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @IsOptional()
  @Field(() => Float, {
    nullable: true,
  })
  rating!: Decimal | null;

  @ApiProperty({
    required: false,
    enum: EnumCandidateFeedbackStatus,
  })
  @IsEnum(EnumCandidateFeedbackStatus)
  @IsOptional()
  @Field(() => EnumCandidateFeedbackStatus, {
    nullable: true,
  })
  status?: "APPLIED" | "REJECTED" | "HIRED" | null;

  @ApiProperty({
    required: false,
    type: () => CandidateInterview,
  })
  @ValidateNested()
  @Type(() => CandidateInterview)
  @IsOptional()
  candidateInterview?: CandidateInterview | null;

  @ApiProperty({
    required: false,
    type: () => Organization,
  })
  @ValidateNested()
  @Type(() => Organization)
  @IsOptional()
  organization?: Organization | null;

  @ApiProperty({
    required: false,
    type: () => CandidateInterviewer,
  })
  @ValidateNested()
  @Type(() => CandidateInterviewer)
  @IsOptional()
  candidateInterviewer?: CandidateInterviewer | null;

  @ApiProperty({
    required: false,
    type: () => Tenant,
  })
  @ValidateNested()
  @Type(() => Tenant)
  @IsOptional()
  tenant?: Tenant | null;

  @ApiProperty({
    required: false,
    type: () => Candidate,
  })
  @ValidateNested()
  @Type(() => Candidate)
  @IsOptional()
  candidate?: Candidate | null;

  @ApiProperty({
    required: false,
    type: () => [CandidateCriterionRating],
  })
  @ValidateNested()
  @Type(() => CandidateCriterionRating)
  @IsOptional()
  candidateCriterionRating?: Array<CandidateCriterionRating>;
}

export { CandidateFeedback as CandidateFeedback };
