/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { OrganizationTeamEmployeeService } from "../organizationTeamEmployee.service";
import { OrganizationTeamEmployeeCreateInput } from "./OrganizationTeamEmployeeCreateInput";
import { OrganizationTeamEmployeeWhereInput } from "./OrganizationTeamEmployeeWhereInput";
import { OrganizationTeamEmployeeWhereUniqueInput } from "./OrganizationTeamEmployeeWhereUniqueInput";
import { OrganizationTeamEmployeeFindManyArgs } from "./OrganizationTeamEmployeeFindManyArgs";
import { OrganizationTeamEmployeeUpdateInput } from "./OrganizationTeamEmployeeUpdateInput";
import { OrganizationTeamEmployee } from "./OrganizationTeamEmployee";

export class OrganizationTeamEmployeeControllerBase {
  constructor(protected readonly service: OrganizationTeamEmployeeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: OrganizationTeamEmployee })
  async create(
    @common.Body() data: OrganizationTeamEmployeeCreateInput
  ): Promise<OrganizationTeamEmployee> {
    return await this.service.create({
      data: {
        ...data,

        organizationTeam: {
          connect: data.organizationTeam,
        },

        employee: {
          connect: data.employee,
        },

        role: data.role
          ? {
              connect: data.role,
            }
          : undefined,

        organization: data.organization
          ? {
              connect: data.organization,
            }
          : undefined,

        tenant: data.tenant
          ? {
              connect: data.tenant,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isTrackingEnabled: true,

        organizationTeam: {
          select: {
            id: true,
          },
        },

        employee: {
          select: {
            id: true,
          },
        },

        role: {
          select: {
            id: true,
          },
        },

        organization: {
          select: {
            id: true,
          },
        },

        tenant: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [OrganizationTeamEmployee] })
  @ApiNestedQuery(OrganizationTeamEmployeeFindManyArgs)
  async findMany(
    @common.Req() request: Request
  ): Promise<OrganizationTeamEmployee[]> {
    const args = plainToClass(
      OrganizationTeamEmployeeFindManyArgs,
      request.query
    );
    return this.service.findMany({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isTrackingEnabled: true,

        organizationTeam: {
          select: {
            id: true,
          },
        },

        employee: {
          select: {
            id: true,
          },
        },

        role: {
          select: {
            id: true,
          },
        },

        organization: {
          select: {
            id: true,
          },
        },

        tenant: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: OrganizationTeamEmployee })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: OrganizationTeamEmployeeWhereUniqueInput
  ): Promise<OrganizationTeamEmployee | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isTrackingEnabled: true,

        organizationTeam: {
          select: {
            id: true,
          },
        },

        employee: {
          select: {
            id: true,
          },
        },

        role: {
          select: {
            id: true,
          },
        },

        organization: {
          select: {
            id: true,
          },
        },

        tenant: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: OrganizationTeamEmployee })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: OrganizationTeamEmployeeWhereUniqueInput,
    @common.Body() data: OrganizationTeamEmployeeUpdateInput
  ): Promise<OrganizationTeamEmployee | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          organizationTeam: {
            connect: data.organizationTeam,
          },

          employee: {
            connect: data.employee,
          },

          role: data.role
            ? {
                connect: data.role,
              }
            : undefined,

          organization: data.organization
            ? {
                connect: data.organization,
              }
            : undefined,

          tenant: data.tenant
            ? {
                connect: data.tenant,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          isTrackingEnabled: true,

          organizationTeam: {
            select: {
              id: true,
            },
          },

          employee: {
            select: {
              id: true,
            },
          },

          role: {
            select: {
              id: true,
            },
          },

          organization: {
            select: {
              id: true,
            },
          },

          tenant: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: OrganizationTeamEmployee })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: OrganizationTeamEmployeeWhereUniqueInput
  ): Promise<OrganizationTeamEmployee | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          isTrackingEnabled: true,

          organizationTeam: {
            select: {
              id: true,
            },
          },

          employee: {
            select: {
              id: true,
            },
          },

          role: {
            select: {
              id: true,
            },
          },

          organization: {
            select: {
              id: true,
            },
          },

          tenant: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
