import { Decimal } from "decimal.js";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { OrganizationCreateNestedManyWithoutImageAssetsInput } from "./OrganizationCreateNestedManyWithoutImageAssetsInput";
import { TenantCreateNestedManyWithoutImageAssetsInput } from "./TenantCreateNestedManyWithoutImageAssetsInput";
import { EquipmentCreateNestedManyWithoutImageAssetsInput } from "./EquipmentCreateNestedManyWithoutImageAssetsInput";
import { IssueTypeCreateNestedManyWithoutImageAssetsInput } from "./IssueTypeCreateNestedManyWithoutImageAssetsInput";
import { MerchantCreateNestedManyWithoutImageAssetsInput } from "./MerchantCreateNestedManyWithoutImageAssetsInput";
import { OrganizationContactCreateNestedManyWithoutImageAssetsInput } from "./OrganizationContactCreateNestedManyWithoutImageAssetsInput";
import { OrganizationDocumentCreateNestedManyWithoutImageAssetsInput } from "./OrganizationDocumentCreateNestedManyWithoutImageAssetsInput";
import { OrganizationProjectCreateNestedManyWithoutImageAssetsInput } from "./OrganizationProjectCreateNestedManyWithoutImageAssetsInput";
import { OrganizationTeamCreateNestedManyWithoutImageAssetsInput } from "./OrganizationTeamCreateNestedManyWithoutImageAssetsInput";
import { ProductCreateNestedManyWithoutImageAssetsInput } from "./ProductCreateNestedManyWithoutImageAssetsInput";
import { ProductCategoryCreateNestedManyWithoutImageAssetsInput } from "./ProductCategoryCreateNestedManyWithoutImageAssetsInput";
import { ProductGalleryItemCreateNestedManyWithoutImageAssetsInput } from "./ProductGalleryItemCreateNestedManyWithoutImageAssetsInput";
import { ProductVariantCreateNestedManyWithoutImageAssetsInput } from "./ProductVariantCreateNestedManyWithoutImageAssetsInput";
import { TimeOffRequestCreateNestedManyWithoutImageAssetsInput } from "./TimeOffRequestCreateNestedManyWithoutImageAssetsInput";
import { UserCreateNestedManyWithoutImageAssetsInput } from "./UserCreateNestedManyWithoutImageAssetsInput";
import { WarehouseCreateNestedManyWithoutImageAssetsInput } from "./WarehouseCreateNestedManyWithoutImageAssetsInput";

export type ImageAssetCreateInput = {
  name?: string | null;
  url: string;
  width: number;
  height: number;
  isFeatured: boolean;
  thumb?: string | null;
  size?: Decimal | null;
  externalProviderId?: string | null;
  storageProvider?: "LOCAL" | "S3" | "WASABI" | "CLOUDINARY" | null;
  deletedAt?: Date | null;
  tenantImageAssetTenantIdTotenant?: TenantWhereUniqueInput | null;
  organizationImageAssetOrganizationIdToorganization?: OrganizationWhereUniqueInput | null;
  organizationOrganizationImageIdToimageAsset?: OrganizationCreateNestedManyWithoutImageAssetsInput;
  tenantTenantImageIdToimageAsset?: TenantCreateNestedManyWithoutImageAssetsInput;
  equipment?: EquipmentCreateNestedManyWithoutImageAssetsInput;
  issueType?: IssueTypeCreateNestedManyWithoutImageAssetsInput;
  merchant?: MerchantCreateNestedManyWithoutImageAssetsInput;
  organizationContact?: OrganizationContactCreateNestedManyWithoutImageAssetsInput;
  organizationDocument?: OrganizationDocumentCreateNestedManyWithoutImageAssetsInput;
  organizationProject?: OrganizationProjectCreateNestedManyWithoutImageAssetsInput;
  organizationTeam?: OrganizationTeamCreateNestedManyWithoutImageAssetsInput;
  product?: ProductCreateNestedManyWithoutImageAssetsInput;
  productCategory?: ProductCategoryCreateNestedManyWithoutImageAssetsInput;
  productGalleryItem?: ProductGalleryItemCreateNestedManyWithoutImageAssetsInput;
  productVariant?: ProductVariantCreateNestedManyWithoutImageAssetsInput;
  timeOffRequest?: TimeOffRequestCreateNestedManyWithoutImageAssetsInput;
  user?: UserCreateNestedManyWithoutImageAssetsInput;
  warehouse?: WarehouseCreateNestedManyWithoutImageAssetsInput;
};
