import { Decimal } from "decimal.js";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { OrganizationUpdateManyWithoutImageAssetsInput } from "./OrganizationUpdateManyWithoutImageAssetsInput";
import { TenantUpdateManyWithoutImageAssetsInput } from "./TenantUpdateManyWithoutImageAssetsInput";
import { EquipmentUpdateManyWithoutImageAssetsInput } from "./EquipmentUpdateManyWithoutImageAssetsInput";
import { IssueTypeUpdateManyWithoutImageAssetsInput } from "./IssueTypeUpdateManyWithoutImageAssetsInput";
import { MerchantUpdateManyWithoutImageAssetsInput } from "./MerchantUpdateManyWithoutImageAssetsInput";
import { OrganizationContactUpdateManyWithoutImageAssetsInput } from "./OrganizationContactUpdateManyWithoutImageAssetsInput";
import { OrganizationDocumentUpdateManyWithoutImageAssetsInput } from "./OrganizationDocumentUpdateManyWithoutImageAssetsInput";
import { OrganizationProjectUpdateManyWithoutImageAssetsInput } from "./OrganizationProjectUpdateManyWithoutImageAssetsInput";
import { OrganizationTeamUpdateManyWithoutImageAssetsInput } from "./OrganizationTeamUpdateManyWithoutImageAssetsInput";
import { ProductUpdateManyWithoutImageAssetsInput } from "./ProductUpdateManyWithoutImageAssetsInput";
import { ProductCategoryUpdateManyWithoutImageAssetsInput } from "./ProductCategoryUpdateManyWithoutImageAssetsInput";
import { ProductGalleryItemUpdateManyWithoutImageAssetsInput } from "./ProductGalleryItemUpdateManyWithoutImageAssetsInput";
import { ProductVariantUpdateManyWithoutImageAssetsInput } from "./ProductVariantUpdateManyWithoutImageAssetsInput";
import { TimeOffRequestUpdateManyWithoutImageAssetsInput } from "./TimeOffRequestUpdateManyWithoutImageAssetsInput";
import { UserUpdateManyWithoutImageAssetsInput } from "./UserUpdateManyWithoutImageAssetsInput";
import { WarehouseUpdateManyWithoutImageAssetsInput } from "./WarehouseUpdateManyWithoutImageAssetsInput";

export type ImageAssetUpdateInput = {
  name?: string | null;
  url?: string;
  width?: number;
  height?: number;
  isFeatured?: boolean;
  thumb?: string | null;
  size?: Decimal | null;
  externalProviderId?: string | null;
  storageProvider?: "LOCAL" | "S3" | "WASABI" | "CLOUDINARY" | null;
  deletedAt?: Date | null;
  tenantImageAssetTenantIdTotenant?: TenantWhereUniqueInput | null;
  organizationImageAssetOrganizationIdToorganization?: OrganizationWhereUniqueInput | null;
  organizationOrganizationImageIdToimageAsset?: OrganizationUpdateManyWithoutImageAssetsInput;
  tenantTenantImageIdToimageAsset?: TenantUpdateManyWithoutImageAssetsInput;
  equipment?: EquipmentUpdateManyWithoutImageAssetsInput;
  issueType?: IssueTypeUpdateManyWithoutImageAssetsInput;
  merchant?: MerchantUpdateManyWithoutImageAssetsInput;
  organizationContact?: OrganizationContactUpdateManyWithoutImageAssetsInput;
  organizationDocument?: OrganizationDocumentUpdateManyWithoutImageAssetsInput;
  organizationProject?: OrganizationProjectUpdateManyWithoutImageAssetsInput;
  organizationTeam?: OrganizationTeamUpdateManyWithoutImageAssetsInput;
  product?: ProductUpdateManyWithoutImageAssetsInput;
  productCategory?: ProductCategoryUpdateManyWithoutImageAssetsInput;
  productGalleryItem?: ProductGalleryItemUpdateManyWithoutImageAssetsInput;
  productVariant?: ProductVariantUpdateManyWithoutImageAssetsInput;
  timeOffRequest?: TimeOffRequestUpdateManyWithoutImageAssetsInput;
  user?: UserUpdateManyWithoutImageAssetsInput;
  warehouse?: WarehouseUpdateManyWithoutImageAssetsInput;
};
