import { Decimal } from "decimal.js";
import { Tenant } from "../tenant/Tenant";
import { Organization } from "../organization/Organization";
import { Equipment } from "../equipment/Equipment";
import { IssueType } from "../issueType/IssueType";
import { Merchant } from "../merchant/Merchant";
import { OrganizationContact } from "../organizationContact/OrganizationContact";
import { OrganizationDocument } from "../organizationDocument/OrganizationDocument";
import { OrganizationProject } from "../organizationProject/OrganizationProject";
import { OrganizationTeam } from "../organizationTeam/OrganizationTeam";
import { Product } from "../product/Product";
import { ProductCategory } from "../productCategory/ProductCategory";
import { ProductGalleryItem } from "../productGalleryItem/ProductGalleryItem";
import { ProductVariant } from "../productVariant/ProductVariant";
import { TimeOffRequest } from "../timeOffRequest/TimeOffRequest";
import { User } from "../user/User";
import { Warehouse } from "../warehouse/Warehouse";

export type ImageAsset = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  name: string | null;
  url: string;
  width: number;
  height: number;
  isFeatured: boolean;
  thumb: string | null;
  size: Decimal | null;
  externalProviderId: string | null;
  storageProvider?: "LOCAL" | "S3" | "WASABI" | "CLOUDINARY" | null;
  deletedAt: Date | null;
  tenantImageAssetTenantIdTotenant?: Tenant | null;
  organizationImageAssetOrganizationIdToorganization?: Organization | null;
  organizationOrganizationImageIdToimageAsset?: Array<Organization>;
  tenantTenantImageIdToimageAsset?: Array<Tenant>;
  equipment?: Array<Equipment>;
  issueType?: Array<IssueType>;
  merchant?: Array<Merchant>;
  organizationContact?: Array<OrganizationContact>;
  organizationDocument?: Array<OrganizationDocument>;
  organizationProject?: Array<OrganizationProject>;
  organizationTeam?: Array<OrganizationTeam>;
  product?: Array<Product>;
  productCategory?: Array<ProductCategory>;
  productGalleryItem?: Array<ProductGalleryItem>;
  productVariant?: Array<ProductVariant>;
  timeOffRequest?: Array<TimeOffRequest>;
  user?: Array<User>;
  warehouse?: Array<Warehouse>;
};
