import { ImageAsset } from "../imageAsset/ImageAsset";
import { Tenant } from "../tenant/Tenant";
import { Organization } from "../organization/Organization";
import { OrganizationContact } from "../organizationContact/OrganizationContact";
import { Activity } from "../activity/Activity";
import { Expense } from "../expense/Expense";
import { InviteOrganizationProject } from "../inviteOrganizationProject/InviteOrganizationProject";
import { InvoiceItem } from "../invoiceItem/InvoiceItem";
import { IssueType } from "../issueType/IssueType";
import { KeyResult } from "../keyResult/KeyResult";
import { OrganizationProjectEmployee } from "../organizationProjectEmployee/OrganizationProjectEmployee";
import { OrganizationSprint } from "../organizationSprint/OrganizationSprint";
import { OrganizationTaskSetting } from "../organizationTaskSetting/OrganizationTaskSetting";
import { Payment } from "../payment/Payment";
import { TagOrganizationProject } from "../tagOrganizationProject/TagOrganizationProject";
import { Task } from "../task/Task";
import { TaskPriority } from "../taskPriority/TaskPriority";
import { TaskRelatedIssueType } from "../taskRelatedIssueType/TaskRelatedIssueType";
import { TaskSize } from "../taskSize/TaskSize";
import { TaskStatus } from "../taskStatus/TaskStatus";
import { TaskVersion } from "../taskVersion/TaskVersion";
import { TimeLog } from "../timeLog/TimeLog";

export type OrganizationProject = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  name: string;
  startDate: Date | null;
  endDate: Date | null;
  billing: string | null;
  currency: string | null;
  publicField: boolean | null;
  owner: string | null;
  taskListType: string;
  code: string | null;
  description: string | null;
  color: string | null;
  billable: boolean | null;
  billingFlat: boolean | null;
  openSource: boolean | null;
  projectUrl: string | null;
  openSourceProjectUrl: string | null;
  budget: number | null;
  budgetType: string | null;
  membersCount: number | null;
  imageUrl: string | null;
  imageAsset?: ImageAsset | null;
  tenant?: Tenant | null;
  organization?: Organization | null;
  organizationContact?: OrganizationContact | null;
  activity?: Array<Activity>;
  expense?: Array<Expense>;
  inviteOrganizationProject?: Array<InviteOrganizationProject>;
  invoiceItem?: Array<InvoiceItem>;
  issueType?: Array<IssueType>;
  keyResult?: Array<KeyResult>;
  organizationProjectEmployee?: Array<OrganizationProjectEmployee>;
  organizationSprint?: Array<OrganizationSprint>;
  organizationTaskSetting?: Array<OrganizationTaskSetting>;
  payment?: Array<Payment>;
  tagOrganizationProject?: Array<TagOrganizationProject>;
  task?: Array<Task>;
  taskPriority?: Array<TaskPriority>;
  taskRelatedIssueType?: Array<TaskRelatedIssueType>;
  taskSize?: Array<TaskSize>;
  taskStatus?: Array<TaskStatus>;
  taskVersion?: Array<TaskVersion>;
  timeLog?: Array<TimeLog>;
};
