import { StringFilter } from "../../util/StringFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { ImageAssetWhereUniqueInput } from "../imageAsset/ImageAssetWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { OrganizationContactWhereUniqueInput } from "../organizationContact/OrganizationContactWhereUniqueInput";
import { ActivityListRelationFilter } from "../activity/ActivityListRelationFilter";
import { ExpenseListRelationFilter } from "../expense/ExpenseListRelationFilter";
import { InviteOrganizationProjectListRelationFilter } from "../inviteOrganizationProject/InviteOrganizationProjectListRelationFilter";
import { InvoiceItemListRelationFilter } from "../invoiceItem/InvoiceItemListRelationFilter";
import { IssueTypeListRelationFilter } from "../issueType/IssueTypeListRelationFilter";
import { KeyResultListRelationFilter } from "../keyResult/KeyResultListRelationFilter";
import { OrganizationProjectEmployeeListRelationFilter } from "../organizationProjectEmployee/OrganizationProjectEmployeeListRelationFilter";
import { OrganizationSprintListRelationFilter } from "../organizationSprint/OrganizationSprintListRelationFilter";
import { OrganizationTaskSettingListRelationFilter } from "../organizationTaskSetting/OrganizationTaskSettingListRelationFilter";
import { PaymentListRelationFilter } from "../payment/PaymentListRelationFilter";
import { TagOrganizationProjectListRelationFilter } from "../tagOrganizationProject/TagOrganizationProjectListRelationFilter";
import { TaskListRelationFilter } from "../task/TaskListRelationFilter";
import { TaskPriorityListRelationFilter } from "../taskPriority/TaskPriorityListRelationFilter";
import { TaskRelatedIssueTypeListRelationFilter } from "../taskRelatedIssueType/TaskRelatedIssueTypeListRelationFilter";
import { TaskSizeListRelationFilter } from "../taskSize/TaskSizeListRelationFilter";
import { TaskStatusListRelationFilter } from "../taskStatus/TaskStatusListRelationFilter";
import { TaskVersionListRelationFilter } from "../taskVersion/TaskVersionListRelationFilter";
import { TimeLogListRelationFilter } from "../timeLog/TimeLogListRelationFilter";

export type OrganizationProjectWhereInput = {
  id?: StringFilter;
  createdAt?: DateTimeFilter;
  updatedAt?: DateTimeFilter;
  name?: StringFilter;
  startDate?: DateTimeNullableFilter;
  endDate?: DateTimeNullableFilter;
  billing?: StringNullableFilter;
  currency?: StringNullableFilter;
  publicField?: BooleanNullableFilter;
  owner?: StringNullableFilter;
  taskListType?: StringFilter;
  code?: StringNullableFilter;
  description?: StringNullableFilter;
  color?: StringNullableFilter;
  billable?: BooleanNullableFilter;
  billingFlat?: BooleanNullableFilter;
  openSource?: BooleanNullableFilter;
  projectUrl?: StringNullableFilter;
  openSourceProjectUrl?: StringNullableFilter;
  budget?: IntNullableFilter;
  budgetType?: StringNullableFilter;
  membersCount?: IntNullableFilter;
  imageUrl?: StringNullableFilter;
  imageAsset?: ImageAssetWhereUniqueInput;
  tenant?: TenantWhereUniqueInput;
  organization?: OrganizationWhereUniqueInput;
  organizationContact?: OrganizationContactWhereUniqueInput;
  activity?: ActivityListRelationFilter;
  expense?: ExpenseListRelationFilter;
  inviteOrganizationProject?: InviteOrganizationProjectListRelationFilter;
  invoiceItem?: InvoiceItemListRelationFilter;
  issueType?: IssueTypeListRelationFilter;
  keyResult?: KeyResultListRelationFilter;
  organizationProjectEmployee?: OrganizationProjectEmployeeListRelationFilter;
  organizationSprint?: OrganizationSprintListRelationFilter;
  organizationTaskSetting?: OrganizationTaskSettingListRelationFilter;
  payment?: PaymentListRelationFilter;
  tagOrganizationProject?: TagOrganizationProjectListRelationFilter;
  task?: TaskListRelationFilter;
  taskPriority?: TaskPriorityListRelationFilter;
  taskRelatedIssueType?: TaskRelatedIssueTypeListRelationFilter;
  taskSize?: TaskSizeListRelationFilter;
  taskStatus?: TaskStatusListRelationFilter;
  taskVersion?: TaskVersionListRelationFilter;
  timeLog?: TimeLogListRelationFilter;
};
