import { ImageAssetWhereUniqueInput } from "../imageAsset/ImageAssetWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { OrganizationContactWhereUniqueInput } from "../organizationContact/OrganizationContactWhereUniqueInput";
import { ActivityUpdateManyWithoutOrganizationProjectsInput } from "./ActivityUpdateManyWithoutOrganizationProjectsInput";
import { ExpenseUpdateManyWithoutOrganizationProjectsInput } from "./ExpenseUpdateManyWithoutOrganizationProjectsInput";
import { InviteOrganizationProjectUpdateManyWithoutOrganizationProjectsInput } from "./InviteOrganizationProjectUpdateManyWithoutOrganizationProjectsInput";
import { InvoiceItemUpdateManyWithoutOrganizationProjectsInput } from "./InvoiceItemUpdateManyWithoutOrganizationProjectsInput";
import { IssueTypeUpdateManyWithoutOrganizationProjectsInput } from "./IssueTypeUpdateManyWithoutOrganizationProjectsInput";
import { KeyResultUpdateManyWithoutOrganizationProjectsInput } from "./KeyResultUpdateManyWithoutOrganizationProjectsInput";
import { OrganizationProjectEmployeeUpdateManyWithoutOrganizationProjectsInput } from "./OrganizationProjectEmployeeUpdateManyWithoutOrganizationProjectsInput";
import { OrganizationSprintUpdateManyWithoutOrganizationProjectsInput } from "./OrganizationSprintUpdateManyWithoutOrganizationProjectsInput";
import { OrganizationTaskSettingUpdateManyWithoutOrganizationProjectsInput } from "./OrganizationTaskSettingUpdateManyWithoutOrganizationProjectsInput";
import { PaymentUpdateManyWithoutOrganizationProjectsInput } from "./PaymentUpdateManyWithoutOrganizationProjectsInput";
import { TagOrganizationProjectUpdateManyWithoutOrganizationProjectsInput } from "./TagOrganizationProjectUpdateManyWithoutOrganizationProjectsInput";
import { TaskUpdateManyWithoutOrganizationProjectsInput } from "./TaskUpdateManyWithoutOrganizationProjectsInput";
import { TaskPriorityUpdateManyWithoutOrganizationProjectsInput } from "./TaskPriorityUpdateManyWithoutOrganizationProjectsInput";
import { TaskRelatedIssueTypeUpdateManyWithoutOrganizationProjectsInput } from "./TaskRelatedIssueTypeUpdateManyWithoutOrganizationProjectsInput";
import { TaskSizeUpdateManyWithoutOrganizationProjectsInput } from "./TaskSizeUpdateManyWithoutOrganizationProjectsInput";
import { TaskStatusUpdateManyWithoutOrganizationProjectsInput } from "./TaskStatusUpdateManyWithoutOrganizationProjectsInput";
import { TaskVersionUpdateManyWithoutOrganizationProjectsInput } from "./TaskVersionUpdateManyWithoutOrganizationProjectsInput";
import { TimeLogUpdateManyWithoutOrganizationProjectsInput } from "./TimeLogUpdateManyWithoutOrganizationProjectsInput";

export type OrganizationProjectUpdateInput = {
  name?: string;
  startDate?: Date | null;
  endDate?: Date | null;
  billing?: string | null;
  currency?: string | null;
  publicField?: boolean | null;
  owner?: string | null;
  taskListType?: string;
  code?: string | null;
  description?: string | null;
  color?: string | null;
  billable?: boolean | null;
  billingFlat?: boolean | null;
  openSource?: boolean | null;
  projectUrl?: string | null;
  openSourceProjectUrl?: string | null;
  budget?: number | null;
  budgetType?: string | null;
  membersCount?: number | null;
  imageUrl?: string | null;
  imageAsset?: ImageAssetWhereUniqueInput | null;
  tenant?: TenantWhereUniqueInput | null;
  organization?: OrganizationWhereUniqueInput | null;
  organizationContact?: OrganizationContactWhereUniqueInput | null;
  activity?: ActivityUpdateManyWithoutOrganizationProjectsInput;
  expense?: ExpenseUpdateManyWithoutOrganizationProjectsInput;
  inviteOrganizationProject?: InviteOrganizationProjectUpdateManyWithoutOrganizationProjectsInput;
  invoiceItem?: InvoiceItemUpdateManyWithoutOrganizationProjectsInput;
  issueType?: IssueTypeUpdateManyWithoutOrganizationProjectsInput;
  keyResult?: KeyResultUpdateManyWithoutOrganizationProjectsInput;
  organizationProjectEmployee?: OrganizationProjectEmployeeUpdateManyWithoutOrganizationProjectsInput;
  organizationSprint?: OrganizationSprintUpdateManyWithoutOrganizationProjectsInput;
  organizationTaskSetting?: OrganizationTaskSettingUpdateManyWithoutOrganizationProjectsInput;
  payment?: PaymentUpdateManyWithoutOrganizationProjectsInput;
  tagOrganizationProject?: TagOrganizationProjectUpdateManyWithoutOrganizationProjectsInput;
  task?: TaskUpdateManyWithoutOrganizationProjectsInput;
  taskPriority?: TaskPriorityUpdateManyWithoutOrganizationProjectsInput;
  taskRelatedIssueType?: TaskRelatedIssueTypeUpdateManyWithoutOrganizationProjectsInput;
  taskSize?: TaskSizeUpdateManyWithoutOrganizationProjectsInput;
  taskStatus?: TaskStatusUpdateManyWithoutOrganizationProjectsInput;
  taskVersion?: TaskVersionUpdateManyWithoutOrganizationProjectsInput;
  timeLog?: TimeLogUpdateManyWithoutOrganizationProjectsInput;
};
