/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  RequestApproval,
  RequestApprovalEmployee,
  RequestApprovalTeam,
  TagRequestApproval,
  ApprovalPolicy,
  Organization,
  Tenant,
} from "@prisma/client";

export class RequestApprovalServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.RequestApprovalCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.RequestApprovalCountArgs>
  ): Promise<number> {
    return this.prisma.requestApproval.count(args);
  }

  async findMany<T extends Prisma.RequestApprovalFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.RequestApprovalFindManyArgs>
  ): Promise<RequestApproval[]> {
    return this.prisma.requestApproval.findMany(args);
  }
  async findOne<T extends Prisma.RequestApprovalFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.RequestApprovalFindUniqueArgs>
  ): Promise<RequestApproval | null> {
    return this.prisma.requestApproval.findUnique(args);
  }
  async create<T extends Prisma.RequestApprovalCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.RequestApprovalCreateArgs>
  ): Promise<RequestApproval> {
    return this.prisma.requestApproval.create<T>(args);
  }
  async update<T extends Prisma.RequestApprovalUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.RequestApprovalUpdateArgs>
  ): Promise<RequestApproval> {
    return this.prisma.requestApproval.update<T>(args);
  }
  async delete<T extends Prisma.RequestApprovalDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.RequestApprovalDeleteArgs>
  ): Promise<RequestApproval> {
    return this.prisma.requestApproval.delete(args);
  }

  async findRequestApprovalEmployee(
    parentId: string,
    args: Prisma.RequestApprovalEmployeeFindManyArgs
  ): Promise<RequestApprovalEmployee[]> {
    return this.prisma.requestApproval
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .requestApprovalEmployee(args);
  }

  async findRequestApprovalTeam(
    parentId: string,
    args: Prisma.RequestApprovalTeamFindManyArgs
  ): Promise<RequestApprovalTeam[]> {
    return this.prisma.requestApproval
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .requestApprovalTeam(args);
  }

  async findTagRequestApproval(
    parentId: string,
    args: Prisma.TagRequestApprovalFindManyArgs
  ): Promise<TagRequestApproval[]> {
    return this.prisma.requestApproval
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .tagRequestApproval(args);
  }

  async getApprovalPolicy(parentId: string): Promise<ApprovalPolicy | null> {
    return this.prisma.requestApproval
      .findUnique({
        where: { id: parentId },
      })
      .approvalPolicy();
  }

  async getOrganization(parentId: string): Promise<Organization | null> {
    return this.prisma.requestApproval
      .findUnique({
        where: { id: parentId },
      })
      .organization();
  }

  async getTenant(parentId: string): Promise<Tenant | null> {
    return this.prisma.requestApproval
      .findUnique({
        where: { id: parentId },
      })
      .tenant();
  }
}
