import { EquipmentSharesTeamUpdateManyWithoutOrganizationTeamsInput } from "./EquipmentSharesTeamUpdateManyWithoutOrganizationTeamsInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { ImageAssetWhereUniqueInput } from "../imageAsset/ImageAssetWhereUniqueInput";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { GoalUpdateManyWithoutOrganizationTeamsInput } from "./GoalUpdateManyWithoutOrganizationTeamsInput";
import { InviteOrganizationTeamUpdateManyWithoutOrganizationTeamsInput } from "./InviteOrganizationTeamUpdateManyWithoutOrganizationTeamsInput";
import { IssueTypeUpdateManyWithoutOrganizationTeamsInput } from "./IssueTypeUpdateManyWithoutOrganizationTeamsInput";
import { OrganizationTaskSettingUpdateManyWithoutOrganizationTeamsInput } from "./OrganizationTaskSettingUpdateManyWithoutOrganizationTeamsInput";
import { OrganizationTeamEmployeeUpdateManyWithoutOrganizationTeamsInput } from "./OrganizationTeamEmployeeUpdateManyWithoutOrganizationTeamsInput";
import { OrganizationTeamJoinRequestUpdateManyWithoutOrganizationTeamsInput } from "./OrganizationTeamJoinRequestUpdateManyWithoutOrganizationTeamsInput";
import { OrganizationTeamTasksTaskUpdateManyWithoutOrganizationTeamsInput } from "./OrganizationTeamTasksTaskUpdateManyWithoutOrganizationTeamsInput";
import { RequestApprovalTeamUpdateManyWithoutOrganizationTeamsInput } from "./RequestApprovalTeamUpdateManyWithoutOrganizationTeamsInput";
import { TagUpdateManyWithoutOrganizationTeamsInput } from "./TagUpdateManyWithoutOrganizationTeamsInput";
import { TagOrganizationTeamUpdateManyWithoutOrganizationTeamsInput } from "./TagOrganizationTeamUpdateManyWithoutOrganizationTeamsInput";
import { TaskPriorityUpdateManyWithoutOrganizationTeamsInput } from "./TaskPriorityUpdateManyWithoutOrganizationTeamsInput";
import { TaskRelatedIssueTypeUpdateManyWithoutOrganizationTeamsInput } from "./TaskRelatedIssueTypeUpdateManyWithoutOrganizationTeamsInput";
import { TaskSizeUpdateManyWithoutOrganizationTeamsInput } from "./TaskSizeUpdateManyWithoutOrganizationTeamsInput";
import { TaskStatusUpdateManyWithoutOrganizationTeamsInput } from "./TaskStatusUpdateManyWithoutOrganizationTeamsInput";
import { TaskTeamUpdateManyWithoutOrganizationTeamsInput } from "./TaskTeamUpdateManyWithoutOrganizationTeamsInput";
import { TaskVersionUpdateManyWithoutOrganizationTeamsInput } from "./TaskVersionUpdateManyWithoutOrganizationTeamsInput";
import { TimeLogUpdateManyWithoutOrganizationTeamsInput } from "./TimeLogUpdateManyWithoutOrganizationTeamsInput";

export type OrganizationTeamUpdateInput = {
  name?: string;
  prefix?: string | null;
  publicField?: boolean | null;
  profileLink?: string | null;
  equipmentSharesTeams?: EquipmentSharesTeamUpdateManyWithoutOrganizationTeamsInput;
  logo?: string | null;
  color?: string | null;
  emoji?: string | null;
  teamSize?: string | null;
  tenant?: TenantWhereUniqueInput | null;
  imageAsset?: ImageAssetWhereUniqueInput | null;
  user?: UserWhereUniqueInput | null;
  organization?: OrganizationWhereUniqueInput | null;
  goal?: GoalUpdateManyWithoutOrganizationTeamsInput;
  inviteOrganizationTeam?: InviteOrganizationTeamUpdateManyWithoutOrganizationTeamsInput;
  issueType?: IssueTypeUpdateManyWithoutOrganizationTeamsInput;
  organizationTaskSetting?: OrganizationTaskSettingUpdateManyWithoutOrganizationTeamsInput;
  organizationTeamEmployee?: OrganizationTeamEmployeeUpdateManyWithoutOrganizationTeamsInput;
  organizationTeamJoinRequest?: OrganizationTeamJoinRequestUpdateManyWithoutOrganizationTeamsInput;
  organizationTeamTasksTask?: OrganizationTeamTasksTaskUpdateManyWithoutOrganizationTeamsInput;
  requestApprovalTeam?: RequestApprovalTeamUpdateManyWithoutOrganizationTeamsInput;
  tag?: TagUpdateManyWithoutOrganizationTeamsInput;
  tagOrganizationTeam?: TagOrganizationTeamUpdateManyWithoutOrganizationTeamsInput;
  taskPriority?: TaskPriorityUpdateManyWithoutOrganizationTeamsInput;
  taskRelatedIssueType?: TaskRelatedIssueTypeUpdateManyWithoutOrganizationTeamsInput;
  taskSize?: TaskSizeUpdateManyWithoutOrganizationTeamsInput;
  taskStatus?: TaskStatusUpdateManyWithoutOrganizationTeamsInput;
  taskTeam?: TaskTeamUpdateManyWithoutOrganizationTeamsInput;
  taskVersion?: TaskVersionUpdateManyWithoutOrganizationTeamsInput;
  timeLog?: TimeLogUpdateManyWithoutOrganizationTeamsInput;
};
