import { EquipmentSharesTeamCreateNestedManyWithoutOrganizationTeamsInput } from "./EquipmentSharesTeamCreateNestedManyWithoutOrganizationTeamsInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { ImageAssetWhereUniqueInput } from "../imageAsset/ImageAssetWhereUniqueInput";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { GoalCreateNestedManyWithoutOrganizationTeamsInput } from "./GoalCreateNestedManyWithoutOrganizationTeamsInput";
import { InviteOrganizationTeamCreateNestedManyWithoutOrganizationTeamsInput } from "./InviteOrganizationTeamCreateNestedManyWithoutOrganizationTeamsInput";
import { IssueTypeCreateNestedManyWithoutOrganizationTeamsInput } from "./IssueTypeCreateNestedManyWithoutOrganizationTeamsInput";
import { OrganizationTaskSettingCreateNestedManyWithoutOrganizationTeamsInput } from "./OrganizationTaskSettingCreateNestedManyWithoutOrganizationTeamsInput";
import { OrganizationTeamEmployeeCreateNestedManyWithoutOrganizationTeamsInput } from "./OrganizationTeamEmployeeCreateNestedManyWithoutOrganizationTeamsInput";
import { OrganizationTeamJoinRequestCreateNestedManyWithoutOrganizationTeamsInput } from "./OrganizationTeamJoinRequestCreateNestedManyWithoutOrganizationTeamsInput";
import { OrganizationTeamTasksTaskCreateNestedManyWithoutOrganizationTeamsInput } from "./OrganizationTeamTasksTaskCreateNestedManyWithoutOrganizationTeamsInput";
import { RequestApprovalTeamCreateNestedManyWithoutOrganizationTeamsInput } from "./RequestApprovalTeamCreateNestedManyWithoutOrganizationTeamsInput";
import { TagCreateNestedManyWithoutOrganizationTeamsInput } from "./TagCreateNestedManyWithoutOrganizationTeamsInput";
import { TagOrganizationTeamCreateNestedManyWithoutOrganizationTeamsInput } from "./TagOrganizationTeamCreateNestedManyWithoutOrganizationTeamsInput";
import { TaskPriorityCreateNestedManyWithoutOrganizationTeamsInput } from "./TaskPriorityCreateNestedManyWithoutOrganizationTeamsInput";
import { TaskRelatedIssueTypeCreateNestedManyWithoutOrganizationTeamsInput } from "./TaskRelatedIssueTypeCreateNestedManyWithoutOrganizationTeamsInput";
import { TaskSizeCreateNestedManyWithoutOrganizationTeamsInput } from "./TaskSizeCreateNestedManyWithoutOrganizationTeamsInput";
import { TaskStatusCreateNestedManyWithoutOrganizationTeamsInput } from "./TaskStatusCreateNestedManyWithoutOrganizationTeamsInput";
import { TaskTeamCreateNestedManyWithoutOrganizationTeamsInput } from "./TaskTeamCreateNestedManyWithoutOrganizationTeamsInput";
import { TaskVersionCreateNestedManyWithoutOrganizationTeamsInput } from "./TaskVersionCreateNestedManyWithoutOrganizationTeamsInput";
import { TimeLogCreateNestedManyWithoutOrganizationTeamsInput } from "./TimeLogCreateNestedManyWithoutOrganizationTeamsInput";

export type OrganizationTeamCreateInput = {
  name: string;
  prefix?: string | null;
  publicField?: boolean | null;
  profileLink?: string | null;
  equipmentSharesTeams?: EquipmentSharesTeamCreateNestedManyWithoutOrganizationTeamsInput;
  logo?: string | null;
  color?: string | null;
  emoji?: string | null;
  teamSize?: string | null;
  tenant?: TenantWhereUniqueInput | null;
  imageAsset?: ImageAssetWhereUniqueInput | null;
  user?: UserWhereUniqueInput | null;
  organization?: OrganizationWhereUniqueInput | null;
  goal?: GoalCreateNestedManyWithoutOrganizationTeamsInput;
  inviteOrganizationTeam?: InviteOrganizationTeamCreateNestedManyWithoutOrganizationTeamsInput;
  issueType?: IssueTypeCreateNestedManyWithoutOrganizationTeamsInput;
  organizationTaskSetting?: OrganizationTaskSettingCreateNestedManyWithoutOrganizationTeamsInput;
  organizationTeamEmployee?: OrganizationTeamEmployeeCreateNestedManyWithoutOrganizationTeamsInput;
  organizationTeamJoinRequest?: OrganizationTeamJoinRequestCreateNestedManyWithoutOrganizationTeamsInput;
  organizationTeamTasksTask?: OrganizationTeamTasksTaskCreateNestedManyWithoutOrganizationTeamsInput;
  requestApprovalTeam?: RequestApprovalTeamCreateNestedManyWithoutOrganizationTeamsInput;
  tag?: TagCreateNestedManyWithoutOrganizationTeamsInput;
  tagOrganizationTeam?: TagOrganizationTeamCreateNestedManyWithoutOrganizationTeamsInput;
  taskPriority?: TaskPriorityCreateNestedManyWithoutOrganizationTeamsInput;
  taskRelatedIssueType?: TaskRelatedIssueTypeCreateNestedManyWithoutOrganizationTeamsInput;
  taskSize?: TaskSizeCreateNestedManyWithoutOrganizationTeamsInput;
  taskStatus?: TaskStatusCreateNestedManyWithoutOrganizationTeamsInput;
  taskTeam?: TaskTeamCreateNestedManyWithoutOrganizationTeamsInput;
  taskVersion?: TaskVersionCreateNestedManyWithoutOrganizationTeamsInput;
  timeLog?: TimeLogCreateNestedManyWithoutOrganizationTeamsInput;
};
