import { EquipmentSharesTeam } from "../equipmentSharesTeam/EquipmentSharesTeam";
import { Tenant } from "../tenant/Tenant";
import { ImageAsset } from "../imageAsset/ImageAsset";
import { User } from "../user/User";
import { Organization } from "../organization/Organization";
import { Goal } from "../goal/Goal";
import { InviteOrganizationTeam } from "../inviteOrganizationTeam/InviteOrganizationTeam";
import { IssueType } from "../issueType/IssueType";
import { OrganizationTaskSetting } from "../organizationTaskSetting/OrganizationTaskSetting";
import { OrganizationTeamEmployee } from "../organizationTeamEmployee/OrganizationTeamEmployee";
import { OrganizationTeamJoinRequest } from "../organizationTeamJoinRequest/OrganizationTeamJoinRequest";
import { OrganizationTeamTasksTask } from "../organizationTeamTasksTask/OrganizationTeamTasksTask";
import { RequestApprovalTeam } from "../requestApprovalTeam/RequestApprovalTeam";
import { Tag } from "../tag/Tag";
import { TagOrganizationTeam } from "../tagOrganizationTeam/TagOrganizationTeam";
import { TaskPriority } from "../taskPriority/TaskPriority";
import { TaskRelatedIssueType } from "../taskRelatedIssueType/TaskRelatedIssueType";
import { TaskSize } from "../taskSize/TaskSize";
import { TaskStatus } from "../taskStatus/TaskStatus";
import { TaskTeam } from "../taskTeam/TaskTeam";
import { TaskVersion } from "../taskVersion/TaskVersion";
import { TimeLog } from "../timeLog/TimeLog";

export type OrganizationTeam = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  name: string;
  prefix: string | null;
  publicField: boolean | null;
  profileLink: string | null;
  equipmentSharesTeams?: Array<EquipmentSharesTeam>;
  logo: string | null;
  color: string | null;
  emoji: string | null;
  teamSize: string | null;
  tenant?: Tenant | null;
  imageAsset?: ImageAsset | null;
  user?: User | null;
  organization?: Organization | null;
  goal?: Array<Goal>;
  inviteOrganizationTeam?: Array<InviteOrganizationTeam>;
  issueType?: Array<IssueType>;
  organizationTaskSetting?: Array<OrganizationTaskSetting>;
  organizationTeamEmployee?: Array<OrganizationTeamEmployee>;
  organizationTeamJoinRequest?: Array<OrganizationTeamJoinRequest>;
  organizationTeamTasksTask?: Array<OrganizationTeamTasksTask>;
  requestApprovalTeam?: Array<RequestApprovalTeam>;
  tag?: Array<Tag>;
  tagOrganizationTeam?: Array<TagOrganizationTeam>;
  taskPriority?: Array<TaskPriority>;
  taskRelatedIssueType?: Array<TaskRelatedIssueType>;
  taskSize?: Array<TaskSize>;
  taskStatus?: Array<TaskStatus>;
  taskTeam?: Array<TaskTeam>;
  taskVersion?: Array<TaskVersion>;
  timeLog?: Array<TimeLog>;
};
