import { StringFilter } from "../../util/StringFilter";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { EquipmentSharesTeamListRelationFilter } from "../equipmentSharesTeam/EquipmentSharesTeamListRelationFilter";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { ImageAssetWhereUniqueInput } from "../imageAsset/ImageAssetWhereUniqueInput";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { GoalListRelationFilter } from "../goal/GoalListRelationFilter";
import { InviteOrganizationTeamListRelationFilter } from "../inviteOrganizationTeam/InviteOrganizationTeamListRelationFilter";
import { IssueTypeListRelationFilter } from "../issueType/IssueTypeListRelationFilter";
import { OrganizationTaskSettingListRelationFilter } from "../organizationTaskSetting/OrganizationTaskSettingListRelationFilter";
import { OrganizationTeamEmployeeListRelationFilter } from "../organizationTeamEmployee/OrganizationTeamEmployeeListRelationFilter";
import { OrganizationTeamJoinRequestListRelationFilter } from "../organizationTeamJoinRequest/OrganizationTeamJoinRequestListRelationFilter";
import { OrganizationTeamTasksTaskListRelationFilter } from "../organizationTeamTasksTask/OrganizationTeamTasksTaskListRelationFilter";
import { RequestApprovalTeamListRelationFilter } from "../requestApprovalTeam/RequestApprovalTeamListRelationFilter";
import { TagListRelationFilter } from "../tag/TagListRelationFilter";
import { TagOrganizationTeamListRelationFilter } from "../tagOrganizationTeam/TagOrganizationTeamListRelationFilter";
import { TaskPriorityListRelationFilter } from "../taskPriority/TaskPriorityListRelationFilter";
import { TaskRelatedIssueTypeListRelationFilter } from "../taskRelatedIssueType/TaskRelatedIssueTypeListRelationFilter";
import { TaskSizeListRelationFilter } from "../taskSize/TaskSizeListRelationFilter";
import { TaskStatusListRelationFilter } from "../taskStatus/TaskStatusListRelationFilter";
import { TaskTeamListRelationFilter } from "../taskTeam/TaskTeamListRelationFilter";
import { TaskVersionListRelationFilter } from "../taskVersion/TaskVersionListRelationFilter";
import { TimeLogListRelationFilter } from "../timeLog/TimeLogListRelationFilter";

export type OrganizationTeamWhereInput = {
  id?: StringFilter;
  createdAt?: DateTimeFilter;
  updatedAt?: DateTimeFilter;
  name?: StringFilter;
  prefix?: StringNullableFilter;
  publicField?: BooleanNullableFilter;
  profileLink?: StringNullableFilter;
  equipmentSharesTeams?: EquipmentSharesTeamListRelationFilter;
  logo?: StringNullableFilter;
  color?: StringNullableFilter;
  emoji?: StringNullableFilter;
  teamSize?: StringNullableFilter;
  tenant?: TenantWhereUniqueInput;
  imageAsset?: ImageAssetWhereUniqueInput;
  user?: UserWhereUniqueInput;
  organization?: OrganizationWhereUniqueInput;
  goal?: GoalListRelationFilter;
  inviteOrganizationTeam?: InviteOrganizationTeamListRelationFilter;
  issueType?: IssueTypeListRelationFilter;
  organizationTaskSetting?: OrganizationTaskSettingListRelationFilter;
  organizationTeamEmployee?: OrganizationTeamEmployeeListRelationFilter;
  organizationTeamJoinRequest?: OrganizationTeamJoinRequestListRelationFilter;
  organizationTeamTasksTask?: OrganizationTeamTasksTaskListRelationFilter;
  requestApprovalTeam?: RequestApprovalTeamListRelationFilter;
  tag?: TagListRelationFilter;
  tagOrganizationTeam?: TagOrganizationTeamListRelationFilter;
  taskPriority?: TaskPriorityListRelationFilter;
  taskRelatedIssueType?: TaskRelatedIssueTypeListRelationFilter;
  taskSize?: TaskSizeListRelationFilter;
  taskStatus?: TaskStatusListRelationFilter;
  taskTeam?: TaskTeamListRelationFilter;
  taskVersion?: TaskVersionListRelationFilter;
  timeLog?: TimeLogListRelationFilter;
};
