import { Decimal } from "decimal.js";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { OrganizationContactWhereUniqueInput } from "../organizationContact/OrganizationContactWhereUniqueInput";
import { InvoiceEstimateHistoryCreateNestedManyWithoutInvoicesInput } from "./InvoiceEstimateHistoryCreateNestedManyWithoutInvoicesInput";
import { InvoiceItemCreateNestedManyWithoutInvoicesInput } from "./InvoiceItemCreateNestedManyWithoutInvoicesInput";
import { PaymentCreateNestedManyWithoutInvoicesInput } from "./PaymentCreateNestedManyWithoutInvoicesInput";
import { TagInvoiceCreateNestedManyWithoutInvoicesInput } from "./TagInvoiceCreateNestedManyWithoutInvoicesInput";

export type InvoiceCreateInput = {
  invoiceDate?: Date | null;
  invoiceNumber?: Decimal | null;
  dueDate?: Date | null;
  currency: string;
  discountValue: Decimal;
  paid?: boolean | null;
  tax?: Decimal | null;
  tax2?: Decimal | null;
  terms: string;
  totalValue?: Decimal | null;
  status: string;
  isEstimate?: boolean | null;
  isAccepted?: boolean | null;
  discountType?: string | null;
  taxType?: string | null;
  tax2Type?: string | null;
  invoiceType?: string | null;
  sentTo?: string | null;
  organizationContactId?: string | null;
  internalNote?: string | null;
  alreadyPaid?: Decimal | null;
  amountDue?: Decimal | null;
  hasRemainingAmountInvoiced?: boolean | null;
  token?: string | null;
  isArchived?: boolean | null;
  organizationInvoiceOrganizationIdToorganization?: OrganizationWhereUniqueInput | null;
  tenant?: TenantWhereUniqueInput | null;
  organizationInvoiceFromOrganizationIdToorganization: OrganizationWhereUniqueInput;
  organizationContact?: OrganizationContactWhereUniqueInput | null;
  invoiceEstimateHistory?: InvoiceEstimateHistoryCreateNestedManyWithoutInvoicesInput;
  invoiceItem?: InvoiceItemCreateNestedManyWithoutInvoicesInput;
  payment?: PaymentCreateNestedManyWithoutInvoicesInput;
  tagInvoice?: TagInvoiceCreateNestedManyWithoutInvoicesInput;
};
