import { Decimal } from "decimal.js";
import { Organization } from "../organization/Organization";
import { Tenant } from "../tenant/Tenant";
import { OrganizationContact } from "../organizationContact/OrganizationContact";
import { InvoiceEstimateHistory } from "../invoiceEstimateHistory/InvoiceEstimateHistory";
import { InvoiceItem } from "../invoiceItem/InvoiceItem";
import { Payment } from "../payment/Payment";
import { TagInvoice } from "../tagInvoice/TagInvoice";

export type Invoice = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  invoiceDate: Date | null;
  invoiceNumber: Decimal | null;
  dueDate: Date | null;
  currency: string;
  discountValue: Decimal;
  paid: boolean | null;
  tax: Decimal | null;
  tax2: Decimal | null;
  terms: string;
  totalValue: Decimal | null;
  status: string;
  isEstimate: boolean | null;
  isAccepted: boolean | null;
  discountType: string | null;
  taxType: string | null;
  tax2Type: string | null;
  invoiceType: string | null;
  sentTo: string | null;
  organizationContactId: string | null;
  internalNote: string | null;
  alreadyPaid: Decimal | null;
  amountDue: Decimal | null;
  hasRemainingAmountInvoiced: boolean | null;
  token: string | null;
  isArchived: boolean | null;
  organizationInvoiceOrganizationIdToorganization?: Organization | null;
  tenant?: Tenant | null;
  organizationInvoiceFromOrganizationIdToorganization?: Organization;
  organizationContact?: OrganizationContact | null;
  invoiceEstimateHistory?: Array<InvoiceEstimateHistory>;
  invoiceItem?: Array<InvoiceItem>;
  payment?: Array<Payment>;
  tagInvoice?: Array<TagInvoice>;
};
