import { Decimal } from "decimal.js";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { OrganizationPositionWhereUniqueInput } from "../organizationPosition/OrganizationPositionWhereUniqueInput";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { CandidateSourceWhereUniqueInput } from "../candidateSource/CandidateSourceWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { EmployeeWhereUniqueInput } from "../employee/EmployeeWhereUniqueInput";
import { ContactWhereUniqueInput } from "../contact/ContactWhereUniqueInput";
import { CandidateDepartmentUpdateManyWithoutCandidatesInput } from "./CandidateDepartmentUpdateManyWithoutCandidatesInput";
import { CandidateDocumentUpdateManyWithoutCandidatesInput } from "./CandidateDocumentUpdateManyWithoutCandidatesInput";
import { CandidateEducationUpdateManyWithoutCandidatesInput } from "./CandidateEducationUpdateManyWithoutCandidatesInput";
import { CandidateEmploymentTypeUpdateManyWithoutCandidatesInput } from "./CandidateEmploymentTypeUpdateManyWithoutCandidatesInput";
import { CandidateExperienceUpdateManyWithoutCandidatesInput } from "./CandidateExperienceUpdateManyWithoutCandidatesInput";
import { CandidateFeedbackUpdateManyWithoutCandidatesInput } from "./CandidateFeedbackUpdateManyWithoutCandidatesInput";
import { CandidateInterviewUpdateManyWithoutCandidatesInput } from "./CandidateInterviewUpdateManyWithoutCandidatesInput";
import { CandidateSkillUpdateManyWithoutCandidatesInput } from "./CandidateSkillUpdateManyWithoutCandidatesInput";
import { TagCandidateUpdateManyWithoutCandidatesInput } from "./TagCandidateUpdateManyWithoutCandidatesInput";

export type CandidateUpdateInput = {
  rating?: Decimal | null;
  valueDate?: Date | null;
  appliedDate?: Date | null;
  hiredDate?: Date | null;
  status?: string | null;
  rejectDate?: Date | null;
  candidateLevel?: string | null;
  reWeeklyLimit?: number | null;
  billRateCurrency?: string | null;
  billRateValue?: number | null;
  payPeriod?: string | null;
  cvUrl?: string | null;
  isArchived?: boolean | null;
  minimumBillingRate?: number | null;
  organization?: OrganizationWhereUniqueInput | null;
  organizationPosition?: OrganizationPositionWhereUniqueInput | null;
  user?: UserWhereUniqueInput;
  candidateSource?: CandidateSourceWhereUniqueInput | null;
  tenant?: TenantWhereUniqueInput | null;
  employee?: EmployeeWhereUniqueInput | null;
  contact?: ContactWhereUniqueInput | null;
  candidateDepartment?: CandidateDepartmentUpdateManyWithoutCandidatesInput;
  candidateDocument?: CandidateDocumentUpdateManyWithoutCandidatesInput;
  candidateEducation?: CandidateEducationUpdateManyWithoutCandidatesInput;
  candidateEmploymentType?: CandidateEmploymentTypeUpdateManyWithoutCandidatesInput;
  candidateExperience?: CandidateExperienceUpdateManyWithoutCandidatesInput;
  candidateFeedback?: CandidateFeedbackUpdateManyWithoutCandidatesInput;
  candidateInterview?: CandidateInterviewUpdateManyWithoutCandidatesInput;
  candidateSkill?: CandidateSkillUpdateManyWithoutCandidatesInput;
  tagCandidate?: TagCandidateUpdateManyWithoutCandidatesInput;
};
