import { Decimal } from "decimal.js";
import { OrganizationWhereUniqueInput } from "../organization/OrganizationWhereUniqueInput";
import { OrganizationPositionWhereUniqueInput } from "../organizationPosition/OrganizationPositionWhereUniqueInput";
import { UserWhereUniqueInput } from "../user/UserWhereUniqueInput";
import { CandidateSourceWhereUniqueInput } from "../candidateSource/CandidateSourceWhereUniqueInput";
import { TenantWhereUniqueInput } from "../tenant/TenantWhereUniqueInput";
import { EmployeeWhereUniqueInput } from "../employee/EmployeeWhereUniqueInput";
import { ContactWhereUniqueInput } from "../contact/ContactWhereUniqueInput";
import { CandidateDepartmentCreateNestedManyWithoutCandidatesInput } from "./CandidateDepartmentCreateNestedManyWithoutCandidatesInput";
import { CandidateDocumentCreateNestedManyWithoutCandidatesInput } from "./CandidateDocumentCreateNestedManyWithoutCandidatesInput";
import { CandidateEducationCreateNestedManyWithoutCandidatesInput } from "./CandidateEducationCreateNestedManyWithoutCandidatesInput";
import { CandidateEmploymentTypeCreateNestedManyWithoutCandidatesInput } from "./CandidateEmploymentTypeCreateNestedManyWithoutCandidatesInput";
import { CandidateExperienceCreateNestedManyWithoutCandidatesInput } from "./CandidateExperienceCreateNestedManyWithoutCandidatesInput";
import { CandidateFeedbackCreateNestedManyWithoutCandidatesInput } from "./CandidateFeedbackCreateNestedManyWithoutCandidatesInput";
import { CandidateInterviewCreateNestedManyWithoutCandidatesInput } from "./CandidateInterviewCreateNestedManyWithoutCandidatesInput";
import { CandidateSkillCreateNestedManyWithoutCandidatesInput } from "./CandidateSkillCreateNestedManyWithoutCandidatesInput";
import { TagCandidateCreateNestedManyWithoutCandidatesInput } from "./TagCandidateCreateNestedManyWithoutCandidatesInput";

export type CandidateCreateInput = {
  rating?: Decimal | null;
  valueDate?: Date | null;
  appliedDate?: Date | null;
  hiredDate?: Date | null;
  status?: string | null;
  rejectDate?: Date | null;
  candidateLevel?: string | null;
  reWeeklyLimit?: number | null;
  billRateCurrency?: string | null;
  billRateValue?: number | null;
  payPeriod?: string | null;
  cvUrl?: string | null;
  isArchived?: boolean | null;
  minimumBillingRate?: number | null;
  organization?: OrganizationWhereUniqueInput | null;
  organizationPosition?: OrganizationPositionWhereUniqueInput | null;
  user: UserWhereUniqueInput;
  candidateSource?: CandidateSourceWhereUniqueInput | null;
  tenant?: TenantWhereUniqueInput | null;
  employee?: EmployeeWhereUniqueInput | null;
  contact?: ContactWhereUniqueInput | null;
  candidateDepartment?: CandidateDepartmentCreateNestedManyWithoutCandidatesInput;
  candidateDocument?: CandidateDocumentCreateNestedManyWithoutCandidatesInput;
  candidateEducation?: CandidateEducationCreateNestedManyWithoutCandidatesInput;
  candidateEmploymentType?: CandidateEmploymentTypeCreateNestedManyWithoutCandidatesInput;
  candidateExperience?: CandidateExperienceCreateNestedManyWithoutCandidatesInput;
  candidateFeedback?: CandidateFeedbackCreateNestedManyWithoutCandidatesInput;
  candidateInterview?: CandidateInterviewCreateNestedManyWithoutCandidatesInput;
  candidateSkill?: CandidateSkillCreateNestedManyWithoutCandidatesInput;
  tagCandidate?: TagCandidateCreateNestedManyWithoutCandidatesInput;
};
