import { Decimal } from "decimal.js";
import { Organization } from "../organization/Organization";
import { OrganizationPosition } from "../organizationPosition/OrganizationPosition";
import { User } from "../user/User";
import { CandidateSource } from "../candidateSource/CandidateSource";
import { Tenant } from "../tenant/Tenant";
import { Employee } from "../employee/Employee";
import { Contact } from "../contact/Contact";
import { CandidateDepartment } from "../candidateDepartment/CandidateDepartment";
import { CandidateDocument } from "../candidateDocument/CandidateDocument";
import { CandidateEducation } from "../candidateEducation/CandidateEducation";
import { CandidateEmploymentType } from "../candidateEmploymentType/CandidateEmploymentType";
import { CandidateExperience } from "../candidateExperience/CandidateExperience";
import { CandidateFeedback } from "../candidateFeedback/CandidateFeedback";
import { CandidateInterview } from "../candidateInterview/CandidateInterview";
import { CandidateSkill } from "../candidateSkill/CandidateSkill";
import { TagCandidate } from "../tagCandidate/TagCandidate";

export type Candidate = {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  rating: Decimal | null;
  valueDate: Date | null;
  appliedDate: Date | null;
  hiredDate: Date | null;
  status: string | null;
  rejectDate: Date | null;
  candidateLevel: string | null;
  reWeeklyLimit: number | null;
  billRateCurrency: string | null;
  billRateValue: number | null;
  payPeriod: string | null;
  cvUrl: string | null;
  isArchived: boolean | null;
  minimumBillingRate: number | null;
  organization?: Organization | null;
  organizationPosition?: OrganizationPosition | null;
  user?: User;
  candidateSource?: CandidateSource | null;
  tenant?: Tenant | null;
  employee?: Employee | null;
  contact?: Contact | null;
  candidateDepartment?: Array<CandidateDepartment>;
  candidateDocument?: Array<CandidateDocument>;
  candidateEducation?: Array<CandidateEducation>;
  candidateEmploymentType?: Array<CandidateEmploymentType>;
  candidateExperience?: Array<CandidateExperience>;
  candidateFeedback?: Array<CandidateFeedback>;
  candidateInterview?: Array<CandidateInterview>;
  candidateSkill?: Array<CandidateSkill>;
  tagCandidate?: Array<TagCandidate>;
};
