/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { EstimateEmailService } from "../estimateEmail.service";
import { EstimateEmailCreateInput } from "./EstimateEmailCreateInput";
import { EstimateEmailWhereInput } from "./EstimateEmailWhereInput";
import { EstimateEmailWhereUniqueInput } from "./EstimateEmailWhereUniqueInput";
import { EstimateEmailFindManyArgs } from "./EstimateEmailFindManyArgs";
import { EstimateEmailUpdateInput } from "./EstimateEmailUpdateInput";
import { EstimateEmail } from "./EstimateEmail";

export class EstimateEmailControllerBase {
  constructor(protected readonly service: EstimateEmailService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EstimateEmail })
  async create(
    @common.Body() data: EstimateEmailCreateInput
  ): Promise<EstimateEmail> {
    return await this.service.create({
      data: {
        ...data,

        organization: data.organization
          ? {
              connect: data.organization,
            }
          : undefined,

        tenant: data.tenant
          ? {
              connect: data.tenant,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        token: true,
        email: true,
        expireDate: true,
        convertAcceptedEstimates: true,

        organization: {
          select: {
            id: true,
          },
        },

        tenant: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [EstimateEmail] })
  @ApiNestedQuery(EstimateEmailFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<EstimateEmail[]> {
    const args = plainToClass(EstimateEmailFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        token: true,
        email: true,
        expireDate: true,
        convertAcceptedEstimates: true,

        organization: {
          select: {
            id: true,
          },
        },

        tenant: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EstimateEmail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: EstimateEmailWhereUniqueInput
  ): Promise<EstimateEmail | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        token: true,
        email: true,
        expireDate: true,
        convertAcceptedEstimates: true,

        organization: {
          select: {
            id: true,
          },
        },

        tenant: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EstimateEmail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: EstimateEmailWhereUniqueInput,
    @common.Body() data: EstimateEmailUpdateInput
  ): Promise<EstimateEmail | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          organization: data.organization
            ? {
                connect: data.organization,
              }
            : undefined,

          tenant: data.tenant
            ? {
                connect: data.tenant,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          token: true,
          email: true,
          expireDate: true,
          convertAcceptedEstimates: true,

          organization: {
            select: {
              id: true,
            },
          },

          tenant: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EstimateEmail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: EstimateEmailWhereUniqueInput
  ): Promise<EstimateEmail | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          token: true,
          email: true,
          expireDate: true,
          convertAcceptedEstimates: true,

          organization: {
            select: {
              id: true,
            },
          },

          tenant: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
